### ISSUE TITLE
Enhance the design

### ISSUE THREAD

**Issue by pzduniak** [lavab/web#106]
>by the way
>a friendly reminder that everything is too small now
>which is especially visible on 1920x1080

![Current design](http://qs.lc/u7mvp)
![Suggested change](http://qs.lc/ts0bj)

The changed version has some stuff moved as I was too lazy to calculate movement. but it should be easy enough to change.

**Comment by flixi** [comment]
Status?

**Comment by piggyslasher** [comment]
now with new rem units, the app looks fine on retina/non-retina. closing this.
