### ISSUE TITLE
Two blues?

### ISSUE THREAD

**Issue by flixi** [lavab/web#167]
![bildschirmfoto 2015-02-27 um 15 43 19](https://cloud.githubusercontent.com/assets/707993/6414406/6f09dd9a-be97-11e4-8405-846bc2e0e55f.png)

Please make the buttons have the same color scheme...

**Comment by piggyslasher** [comment]
fixed. please check. now i've set the remove button as a warning color. and fixed all the buttons to have a relative hover color (5% lighter)
