### ISSUE TITLE
Some sentences are written in a weird way

### ISSUE THREAD

**Issue by pzduniak** [lavab/web#216]
In my opinion, all labels like
![http://qs.lc/ht36q](http://qs.lc/ht36q)

Should be swapped to normally typed sentences:
![http://qs.lc/nf14b](http://qs.lc/nf14b)

**Comment by flixi** [comment]
@bilbof 
Can you go thruogh this file again?
https://github.com/lavab/web/blob/master/src/translations/en.toml
