### ISSUE TITLE
sign up for newsletter text

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#229]
@bilbof - you commented out said line from the toml language file. would you like me to uncomment it?

![image](https://cloud.githubusercontent.com/assets/1991125/6550061/132e1de0-c65a-11e4-986a-bb4f05a178d0.png)

Assign this issue back to me if you want me to proceed. Thanks.

**Comment by flixi** [comment]
Status? @piggyslasher

**Comment by flixi** [comment]
Status @piggyslasher ?

**Comment by flixi** [comment]
Reopen if it still persists.

**Comment by piggyslasher** [comment]
sorry I missed your previous request for status. This was something I was that Bill said he's going to go through in the translations file. Let me check.
