### ISSUE TITLE
checkbox on login screens should be aligned to info-text

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#235]
if there is info text, place checkbox as a child to it.

**Comment by flixi** [comment]
Info?

**Comment by piggyslasher** [comment]
@flixi : info text has the circle 'i' next to it.

![image](https://cloud.githubusercontent.com/assets/1991125/6764151/e8020622-cfdc-11e4-8091-0cd93109f8fe.png)

Im guessing this is what you wanted @vLooz ?

closing for now. please reopen if not complete @vLooz
