### ISSUE TITLE
Why are there two locks in my Inbox all of a sudden?

### ISSUE THREAD

**Issue by flixi** [lavab/web#245]
I just replied to an email and this is what happened.
![bildschirmfoto 2015-03-10 um 14 11 33](https://cloud.githubusercontent.com/assets/707993/6575575/2acb1b0c-c730-11e4-98e2-543b5e7109c0.png)

**Comment by let4be** [comment]
This is just a draft for displaying mixed-encryption threads, when part of emails originate from secure source and part not. Can be easily edited in jade

**Comment by let4be** [comment]
This data comes completely from API, 
secure = all
secure = none
secure = some
