### ISSUE TITLE
Emails disappear when read

### ISSUE THREAD

**Issue by bilbof** [lavab/web#254]
All of my emails that arrived before 6pm yesterday are gone.

![screen shot 2015-03-11 at 12 41 15](https://cloud.githubusercontent.com/assets/8124374/6595591/06c33020-c7ec-11e4-98e7-bd179e299950.png)

**Comment by let4be** [comment]
@bilbof could you please provide more details about this? what else is available in your inbox?
I suspect infinite scrolling issue as it was developed some time ago and wasn't tested to work with recent changes

probably @pzduniak did some cleanup or something?
