### ISSUE TITLE
Compose View Improvements

### ISSUE THREAD

**Issue by vLooz** [lavab/web#255]
Version 2.0
I'd love too see some improvements to the compose screen. The "H1-H3 headline" options won't be understood by Non-HTML-savvy people.
Please check the design mock, how it should look in the end.
![2015-03-10_compose_better text editor](https://cloud.githubusercontent.com/assets/11177812/6595683/c6d5c7a6-c7ec-11e4-8839-b9314d25f047.jpg)

**Comment by piggyslasher** [comment]
The genius behind textAngular hasn't given dropdown support for the toolbars. hence the Helvetica / size choosing can't be implemented right out the box. i also did some more research and looks like support will be included in the newer version.

@flixi had a few words to say about this on trello previous. How do we do this boss?

**Comment by flixi** [comment]
If you get to it, please change it. ;)

**Comment by piggyslasher** [comment]
@flixi i can remove those extra's that @vLooz has crossed off. You wanted blockquote though - is that necessary?

**Comment by piggyslasher** [comment]
@vLooz - so the 'A' button just makes the editor dissapear and allow sending of a blank email?

**Comment by flixi** [comment]
Nah, I don't need blockquote. @piggyslasher

**Comment by piggyslasher** [comment]
fixed the padding of the input items. will do rest when more time available.

**Comment by piggyslasher** [comment]
currently it looks like this.

![image](https://cloud.githubusercontent.com/assets/1991125/7494940/671c664e-f43d-11e4-931e-83b652302a81.png)

What do you think should the positioning of the icons in the action bar be? Align it with the left and right margins of compose? the close button looks weird not being in the corner in that case.

**Comment by vLooz** [comment]
Sometimes layout problems get solved or even don't appear, when you stick to guidelines ;-P

![bildschirmfoto 2015-05-06 um 16 44 18](https://cloud.githubusercontent.com/assets/11177812/7495658/98ec35e2-f40f-11e4-8872-08c1e50248f2.png)

**Comment by piggyslasher** [comment]
:) okay so same goes for the left side yes?
![image](https://cloud.githubusercontent.com/assets/1991125/7495890/5bdc7bba-f443-11e4-9d65-b43562d4b066.png)

**Comment by vLooz** [comment]
Yes, exactly. 
The centre of the attachment icon is 33 px from the left edge. 
The A icon centre is 44 px more to the right

**Comment by joergG** [comment]
@piggyslasher - just cleaning up the waffle-board. what's the status here? can we either move it to "shipped" or back to backlog?

**Comment by piggyslasher** [comment]
Since there isn't going to be significant changes to the editor, we can
move this to shipped. I'd say its complete. There is another task for the
editor that is open for @let4be, which we can leave open in backlog.
