### ISSUE TITLE
No yellow background during LogIn

### ISSUE THREAD

**Issue by vLooz** [lavab/web#256]
please change the background 
![2015-03-11_login_get rid of yellow background](https://cloud.githubusercontent.com/assets/11177812/6595884/0c039680-c7ef-11e4-9b28-d3909913a19f.png)

**Comment by vLooz** [comment]
Bill just told me, the yellow background is a browser things and it's hard to avoid. If you still can find a way tough, it would make me really happy :)

**Comment by bilbof** [comment]
@piggyslasher apparently this is the solution http://stackoverflow.com/questions/2781549/removing-input-background-colour-for-chrome-autocomplete

**Comment by flixi** [comment]
Looks good.
Even on production. Tested with Safari on Mac OS X 10.10
