### ISSUE TITLE
Compose: email tag styling

### ISSUE THREAD

**Issue by vLooz** [lavab/web#259]
I'm aware I've send Vik info about this already. Nevertheless this is the most actual info about this.
![2015-03-11_compose_removingaddress](https://cloud.githubusercontent.com/assets/11177812/6598844/9a19e7d2-c806-11e4-8b40-b79644992771.png)

**Comment by piggyslasher** [comment]
are you sure @fvl? this was how it was before (show 'x' on hover), and then your compose mockup had the cross showing always so i changed it. I can add the cross's hover effect. but about the hiding of the 'x' totally - is this the latest?

**Comment by vLooz** [comment]
Hey Vik, you are right. This stage is almost a month old. Nothing to change here.
The cross should always be shown.

**Comment by let4be** [comment]
also changing ui-select and text-angular related behaviors is pretty time consuming, as almost each non standard task here requires source code investigation

**Comment by piggyslasher** [comment]
closing this as the one thing that was remaining on this was the hover background on the 'x' - thats done. the colors are correct. and #261 covers the more recent guidelines.
