### ISSUE TITLE
SignUp: Align main elements throughout the process

### ISSUE THREAD

**Issue by vLooz** [lavab/web#262]
The SignUp process is great so far, I enjoy looking at every time I use it :) 
It would be even better and more calm though, when the elements like headline, dots, buttons, text fields etc. don't rearrange between the stetps, but stay in the same position. 
![2015-03-09_sign-in_allign elements](https://cloud.githubusercontent.com/assets/11177812/6602994/80577918-c81f-11e4-918b-e2cf17deb3f7.png)

**Comment by piggyslasher** [comment]
this was because you wanted the whole process to be vertically aligned. hence the autoalignment. perhaps we do away with the auto align? @vLooz

**Comment by piggyslasher** [comment]
right now, i made a small fix so that the elements are aligned from the top. its hard to align the last button because of the content above. so i'm just going to mark this done for now as aligning the button is almost impossible without using some unnecessary javascript.

**Comment by piggyslasher** [comment]
please check if youre happy or some screens are 'too high'? comment here if anything. thanks.
