### ISSUE TITLE
How are unread emails indicated?

### ISSUE THREAD

**Issue by flixi** [lavab/web#269]
![bildschirmfoto 2015-03-12 um 13 36 49](https://cloud.githubusercontent.com/assets/707993/6617815/01c9b70c-c8bd-11e4-948b-77be36f7ab2f.png)
It shows me that there is one email which is unread but it doesn't indicate which one it is.

**Comment by let4be** [comment]
Indication is not implemented yet(no styling) afaik
Though it's easy to implement the data is here
@piggyslasher ?

**Comment by vLooz** [comment]
This is how it is supposed to look like:
![inbox kopie](https://cloud.githubusercontent.com/assets/11177812/6628252/41764a4a-c904-11e4-9bbd-b29ab26cb056.png)

**Comment by piggyslasher** [comment]
yeah. there's a badge there
![image](https://cloud.githubusercontent.com/assets/1991125/6669120/344bbac2-cc32-11e4-9394-fa9c11f1ba9c.png)

It is already styled and don't show if empty.

**Comment by flixi** [comment]
When will this be fixed?

**Comment by let4be** [comment]
Due to problems with mailer and today's api downtime this hasn't been resolved yet
I will update this tomorrow
