### ISSUE TITLE
Emails sometimes don't get properly displayed, only as Mumbo jumbo or as missing images

### ISSUE THREAD

**Issue by flixi** [lavab/web#270]
![bildschirmfoto 2015-03-12 um 13 36 49](https://cloud.githubusercontent.com/assets/707993/6617842/3ecc1bf4-c8bd-11e4-8b3a-5bb2384bfce7.png)
This happens from time to time.

![bildschirmfoto 2015-03-12 um 13 40 31](https://cloud.githubusercontent.com/assets/707993/6617864/74a4721c-c8bd-11e4-8191-50e4e4e98ef5.png)
Paypal Emails are generally introduced in this format.

![bildschirmfoto 2015-03-12 um 13 36 33](https://cloud.githubusercontent.com/assets/707993/6617845/41ada1bc-c8bd-11e4-8950-afe695a8980b.png)

And there are prime examples of injectable code. ;)

**Comment by let4be** [comment]
@flixi 

1st need more data, could you please provide "source code" of this email?
open developer tools, click "find element", click on the image and post nearby html source code somewhere on pastebin

this way I will get an idea what happened here

2nd email was caused by some mailer issue most likely

3rd looks perfectly valid

**Comment by let4be** [comment]
can be related with https://github.com/lavab/web/issues/272
working on a fix

**Comment by let4be** [comment]
@flixi could you please check again?

**Comment by let4be** [comment]
please, let me know does it still happen on .co?

**Comment by flixi** [comment]
![bildschirmfoto 2015-03-12 um 17 26 35](https://cloud.githubusercontent.com/assets/707993/6622466/0acd0ffa-c8dd-11e4-9606-da35ece1d191.png)

**Comment by flixi** [comment]
![bildschirmfoto 2015-03-16 um 15 36 18](https://cloud.githubusercontent.com/assets/707993/6668339/86485b68-cbf2-11e4-80e0-78656065b4ec.png)
Still happens despite being updated, the Front End.

**Comment by flixi** [comment]
![bildschirmfoto 2015-03-19 um 13 14 40](https://cloud.githubusercontent.com/assets/707993/6730200/7ad32638-ce3a-11e4-85c6-bfde6d7b3368.png)

https://gist.github.com/flixi/1926e3cd2d17e15946c6

**Comment by flixi** [comment]
Update?

**Comment by let4be** [comment]
@flixi just checked and found few things:
1. Email with "M7Zm9udC13ZWlnaHQ6Ym9sZDsiPkjDpG5kbGVyPC9zcGFu"... is caused by some Mailer issue and has nothing to do with web - it simply came in this weird(base64) format from API
2. It looks like there was another issue with html emails - they came as fully declared pages, with head, body, title etc
Probably it could be better idea to display them in iframe

**Comment by flixi** [comment]
Sure, however this iframing things also makes for an interesting security debate, how easy is it to inject malicious code into the iframes?

**Comment by let4be** [comment]
Empty emails tracked down to the following:
normally it happens on very complex html pages due to invalid html present inside them. We use angular.js sanitizer first in order to make emails's content safe and when email contains weird html markup it kills sanitizer...

**Comment by let4be** [comment]
Good haul here, I've found a bunch of issues in email processing/filtering code
Going to spend few more hours on this

**Comment by let4be** [comment]
@flixi pls try again with the emails you're having issues with

**Comment by let4be** [comment]
update currently is on mail.lavaboom.co

**Comment by let4be** [comment]
@flixi ?

**Comment by flixi** [comment]
I can't as long as the forward feature doesn't work.

**Comment by let4be** [comment]
Just check how your emails look like(especially the one you had problem with before)
I've tried new code on some complex emails and it worked fine, probably this solved issue with some of your emails too.

**Comment by flixi** [comment]
I would but all the emails I had issues with are on .com

**Comment by let4be** [comment]
oh... and we have deployment temporary unavailable due to infrastructure update
okay, we will back to this later then

**Comment by flixi** [comment]
https://gist.github.com/flixi/d1d5818ab906c4dc6cd5
![bildschirmfoto 2015-03-27 um 14 31 02](https://cloud.githubusercontent.com/assets/707993/6868713/22f899a2-d48e-11e4-97f1-92491bd42819.png)
![bildschirmfoto 2015-03-27 um 14 31 27](https://cloud.githubusercontent.com/assets/707993/6868717/273b7cc8-d48e-11e4-8bcf-1dc65b266284.png)

**Comment by let4be** [comment]
We don't have recent updates with fixes deployed afaik

**Comment by flixi** [comment]
![bildschirmfoto 2015-04-04 um 22 40 55](https://cloud.githubusercontent.com/assets/707993/6994483/f324d4e0-db1b-11e4-9895-a6bf69ea9897.png)
https://gist.github.com/flixi/67923597481ef54acdff

**Comment by let4be** [comment]
Please, try to forward this email

**Comment by flixi** [comment]
![bildschirmfoto 2015-04-06 um 20 50 54](https://cloud.githubusercontent.com/assets/707993/7010026/c67c3bd4-dc9e-11e4-920b-d5af8c42c1e6.png)
![bildschirmfoto 2015-04-06 um 20 51 15](https://cloud.githubusercontent.com/assets/707993/7010025/c679b300-dc9e-11e4-97aa-780519a01185.png)

**Comment by let4be** [comment]
@flixi this looks like _entirely_ mailer issue, nothing to do with web here
i'm redirecting this to https://github.com/lavab/mailer/issues/35

**Comment by let4be** [comment]
Empty email caused by a bug in web, I've added logging but I guess it's not deployed as auto deployment is broken :(

**Comment by flixi** [comment]
Alright, then tell @pzduniak to deploy your code manually.

**Comment by flixi** [comment]
https://gist.github.com/flixi/444223eeab29922b65f9

![bildschirmfoto 2015-04-08 um 16 27 44](https://cloud.githubusercontent.com/assets/707993/7047401/952fc77a-de0c-11e4-8bdb-4a0a717fba82.png)

**Comment by let4be** [comment]
nothing to do here without logs

**Comment by let4be** [comment]
asked @pzduniak to help with deploy

**Comment by flixi** [comment]
Fixed as of deployment today I have no issues with that anymore.
