### ISSUE TITLE
general styling of notifications & attachments

### ISSUE THREAD

**Issue by let4be** [lavab/web#273]
![image](https://cloud.githubusercontent.com/assets/4147061/6618627/384398ee-c8d5-11e4-9875-20f427066727.png)
When images security setting is ON we block all images from external sources, need a proper stub for those images
please see src/blocks/directives/noImage.jade

**Comment by let4be** [comment]
Currently I just replace such images with some random image I've googled :)

**Comment by piggyslasher** [comment]
@vLooz - what do you think?

**Comment by andreis** [comment]
http://lorempixel.com/

**Comment by flixi** [comment]
I like lorempixel.

**Comment by piggyslasher** [comment]
we should just use a shaded div that we have text inside saying no image. no extra overhead. no external reliance. i18h. let me do this first. i have had some issues with lorempixel before. plus again - reliance on a 3rd party that knows your ip.

**Comment by andreis** [comment]
Sorry, I wasn't being serious with lorempixel, obviously.

Just follow Gmail's lead, they use a banner and empty divs where the images were, we could have something subtle like a "image blocked" label.

![gmail blocked images](https://cloud.githubusercontent.com/assets/1249760/6784908/c6915dc4-d182-11e4-8da2-c3c6b5a60953.png)

**Comment by flixi** [comment]
I like @andreis 's idea very much.
Keep it as close to the original as possible.
Though do we wantto add a button or a line of text saying to display images this once?

**Comment by vLooz** [comment]
This is a scheme, where we could show notifications like this.
For informations that are just regarding the attachments, a specific "encrypted-looking" attachment icon -see 5) - would be most intuitive from a UX pov. If thats technically possible, the user could decide wether to open the attachment right now (clicking icon, decrypting progress circle appears over icon until it's done) or later. What do you think @andreis ?
![notificationhierarchyscheme](https://cloud.githubusercontent.com/assets/11177812/6848710/24da10f8-d3cf-11e4-815c-5c45f05fee56.png)

**Comment by vLooz** [comment]
![webcrypto slow notification_5](https://cloud.githubusercontent.com/assets/11177812/6849805/95fd35de-d3d5-11e4-8746-0bba71c65bbc.png)
![webcrypto slow notification_4](https://cloud.githubusercontent.com/assets/11177812/6849806/975045e8-d3d5-11e4-95ff-6110bb50b5a2.png)

**Comment by andreis** [comment]
1. Receive 100 photos.
2. Now you have something fun to do for the afternoon!

Jokes aside, add a "decrypt all attachments" button or something

**Comment by vLooz** [comment]
:D you are right, didn't think about that.

**Comment by flixi** [comment]
:thumbsup:

**Comment by piggyslasher** [comment]
closing this issue - please refer to #358 & #410
