### ISSUE TITLE
MailClient: General design retouches

### ISSUE THREAD

**Issue by vLooz** [lavab/web#274]
Compares to the design mock there are still some things off with the mail client design. I don't know what you are working on or which glitches you are aware of already, so I apologize for any double issues :)
Please let me know, when questions arise. 

![2015-03-12_inbox retouches](https://cloud.githubusercontent.com/assets/11177812/6618779/a8cd3792-c8c5-11e4-89c4-f0bc3d2869de.png)

This is the original design mock as a reference:
![2015-03-12_inbox design mock](https://cloud.githubusercontent.com/assets/11177812/6618818/f3a68c00-c8c5-11e4-99ae-dabbf31ac3a8.png)

**Comment by let4be** [comment]
@vLooz "Encrypted thread" is indicates that user does NOT have available decrypted private key for this email
Lock icon indicates that email originates from secure source(for example from another lavaboom account), i.e. supports E2E encryption

So things are different here

**Comment by vLooz** [comment]
mmm... I don't really get this, sorry. @let4be When the user doesn't have a private key available, all E2E-Threats should be encrypted, right?

**Comment by let4be** [comment]
correct, if user doesn't have decrypted key everything remains encrypted

**Comment by vLooz** [comment]
Ok. In this case we should not let the user enter his inbox without "shouting" at him, to upload his private key. Furthermore the whole mail appears highly visible encrypted, I don't think we need an additional text here. 
Still it is a bug in my case. I had my private key in my cash and I could read Felix's Mail.

**Comment by piggyslasher** [comment]
[x] icons bigger
[x] action bar taller
[ ] align left icons to middle of logo
[ ] blue lock icon sizing
[ ] general inbox padding, sizing
[ ] missing icons in action bar of email

**Comment by flixi** [comment]
Yes, these are duplicates and offer the same functionality, so we decided to remove those.

**Comment by piggyslasher** [comment]
closing this for now as #301 is open and covers this.
