### ISSUE TITLE
Some email will not be delivered from lavaboom.com to Gmail

### ISSUE THREAD

**Issue by vLooz** [lavab/web#277]

**Comment by let4be** [comment]
Please details

**Comment by vLooz** [comment]
It turned out, that it's not a speed problem, but that some Mails are not getting through at all. They appear in Lavaboom/Sent but never reach my Gmail Inbox. 
I copied the exact content of a mail, which did not get through on the first try, and on the second try it was no problem.
I tried several attempts with different text formatting, but didn't find a clue there.

**Comment by let4be** [comment]
@vLooz sounds like https://github.com/lavab/mailer problem
Please open developer tools(F12?), wait when application loads, clear the log and then send email.
When issue appears copy contents of console logs somewhere and post them

**Comment by let4be** [comment]
basically we just need to see what's going on inside and get ID of sent email so we could track down this issue

**Comment by vLooz** [comment]
What do you need to ID them? Is sender, recipient and Subject enough?

**Comment by let4be** [comment]
the required info is in console logs(developer tools)
could be useful: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by vLooz** [comment]
mmh... not realistic, that I will be able to find it.
