### ISSUE TITLE
Settings / Profile: Get rid of pen Icons

### ISSUE THREAD

**Issue by vLooz** [lavab/web#280]
I know, I had them on my design mock in the first place, but now it feels a bit uneasy, especially because user can edit text by clicking into the fields anyways. Please get rid of them and move the text to the right, see mock. Thx!
![2015-03-12_settings_get rid of pen icons](https://cloud.githubusercontent.com/assets/11177812/6625751/5a2972a4-c8f2-11e4-98cb-11df5efc1187.jpg)

**Comment by flixi** [comment]
Exchange send with sent with Lavaboom, please. Grammarnazi.

**Comment by piggyslasher** [comment]
going to assign to @let4be  to set `user.settings.isSignatureEnabled` to true - i can't find this in the angular

@let4be : `settings.profile.jade` file man, line `35` - you'll see the model user.

For now the toggle works. Once he fixes that this issue should be closed. I am creating another issue #323 for that.

**Comment by piggyslasher** [comment]
sweet. thanks.
