### ISSUE TITLE
put ui router in html5 mode

### ISSUE THREAD

**Issue by let4be** [lavab/web#289]

**Comment by let4be** [comment]
I've added html5 support so we don't have !# anymore
This works perfectly fine on develop when serve from express.js

For production we need to configure nginx to support html5 mode:
please see: https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode

Shortly we need to serve ['css', 'img', 'js', 'partials', 'translations', 'vendor'] and index.html by direct GET requests and redirect everything else on index.html

**Comment by pzduniak** [comment]
I'll need to change the base image to something more framework-ish, gonna do it today.

**Comment by pzduniak** [comment]
nginx reconfigured

**Comment by let4be** [comment]
https://mail.lavaboom.co/verifyInvite/test/test

**Comment by andreis** [comment]
Vielen dank
