### ISSUE TITLE
Client: Icons disappear & functionality is gone

### ISSUE THREAD

**Issue by vLooz** [lavab/web#296]
I just wanted to delete a thread with 3 messages in it from Inbox. 
I clicked the delete icon and nothing happened, the message still is in Inbox and Trash is still empty. 
After I clicked the delete icon a second time, the icons in the header disappeared and would only be visible for a split second the moment I click the message. After some seconds the mail vanished from inbox, but didn't appear in Trash. The icon bar in Inbox still is gone, as well as in other empty folders.
When I changed to my Sent Folder the icon bar first was not visible, too, but when I clicked a mail, it appeared and stayed visible.

**Comment by andreis** [comment]
Where was this? .com / .io / .co ?

We're working on adding log tracking, until then you can copy and paste the console output (Cmd+Alt+I, Console tab) here (use code tags) or as a separate gist.

**Comment by let4be** [comment]
We desperately need the logs from developer console to solve such issues
Without this it's almost impossible to troubleshot

**Comment by let4be** [comment]
Impossible to track down without logs, please reopen if it happens again with logs attached
