### ISSUE TITLE
Inbox is not highlighted light grey when no mail is selected

### ISSUE THREAD

**Issue by vLooz** [lavab/web#297]

**Comment by vLooz** [comment]
![bildschirmfoto 2015-03-16 um 11 34 05](https://cloud.githubusercontent.com/assets/11177812/6664576/62a2c868-cbd1-11e4-84fa-0127aa6e0b70.png)

**Comment by let4be** [comment]
Issue is deeper, something triggers infinite $digest loop...

**Comment by let4be** [comment]
It seems to be fixed in develop during recent updates, if it's not - reopen
