### ISSUE TITLE
Inbox unread Mail counter doesn't disappear after reading and even replying the unread mail

### ISSUE THREAD

**Issue by vLooz** [lavab/web#298]

**Comment by vLooz** [comment]
![bildschirmfoto 2015-03-16 um 11 38 19](https://cloud.githubusercontent.com/assets/11177812/6664533/01a59a40-cbd1-11e4-986e-f9eb3eee1f64.png)

**Comment by let4be** [comment]
There is a bunch of problems related to this, going to address this in the nearest time.

**Comment by let4be** [comment]
related: https://github.com/lavab/web/issues/135

**Comment by let4be** [comment]
related: https://github.com/lavab/web/issues/269

**Comment by flixi** [comment]
![bildschirmfoto 2015-03-18 um 20 46 08](https://cloud.githubusercontent.com/assets/707993/6717886/e201d3bc-cdaf-11e4-8526-1e714d1a3769.png)

**Comment by flixi** [comment]
Wrong button.
