### ISSUE TITLE
No dot is shown in Usernames in settings/profile

### ISSUE THREAD

**Issue by vLooz** [lavab/web#299]
my username is felix.vlooz and when I send email to my gmail account it is shown as felix.vlooz@lavaboom.com. All fine.
However, in settings/profile under Username it is shown as felixvlooz. Would be nice if this could be consistent.

**Comment by vLooz** [comment]
![bildschirmfoto 2015-03-16 um 11 46 29](https://cloud.githubusercontent.com/assets/11177812/6664811/342572a4-cbd3-11e4-9456-26bc010b7748.png)

**Comment by let4be** [comment]
Oh, right. I "undecorate" the username before passing it to the API...
@pzduniak could we support optional dots in username on API side or should I just put original username in the settings?

**Comment by let4be** [comment]
Found it, account.styled_name
