### ISSUE TITLE
Public key not linked to some accounts

### ISSUE THREAD

**Issue by bilbof** [lavab/web#300]
Worked for Felix VL, but not for Andrei's address.

![screen shot 2015-03-16 at 11 56 20](https://cloud.githubusercontent.com/assets/8124374/6664910/0a78dd32-cbd4-11e4-85af-3dcf6cc43f43.png)

See blue lock next to Felix's address and not with Andrei's.

**Comment by bilbof** [comment]
![screen shot 2015-03-16 at 12 04 35](https://cloud.githubusercontent.com/assets/8124374/6664982/a6f1f14e-cbd4-11e4-8219-e58d5f8461ae.png)

**Comment by bilbof** [comment]
I just sent the email and it added a key for Andrei. Still a bug though.

**Comment by let4be** [comment]
When you type-in address in the from/cc/bcc fields it automatically get public key from lavaboom API
this operation is _not_ instant, so it can take some time but during this time it should display loading icon...

Please provide additional information, such as:
where did this take place? .co, .io, .com?
when it was, could be a duplicate https://github.com/lavab/web/issues/189

**Comment by let4be** [comment]
Closing this as I cannot reproduce the issue and there are no relevant logs available - please reopen if this appears again
