### ISSUE TITLE
Client UI: Please stay close to the UI design mock dimensions

### ISSUE THREAD

**Issue by vLooz** [lavab/web#301]
I noticed, that many dimensions are a bit off compared to the guidelines in my UI design mocks. 
In these guidelines I organized the dimensions and proportions with the unit x or 0,5x, 0,25x etc. 
I used x instead of specific pixels because I wasn't sure what pixel-rate to use with different screen resolutions. 

Now I learned that on normal screens, X is equal to 44 pixels (88px on retina).

I know this is a big wish and probably a lot of work, but could you please go through your code again with my guidelines at hand and change the dimensions of header, field height of list item areas in menu, etc.. to the correct pixel heights, widths etc.? These may sound like just little details changes, but will improve the overall impression of the client UI tremendously. 

Please ask me anytime, when you have questions or need more input!

Thx!

![generaldimensions_x 44px](https://cloud.githubusercontent.com/assets/11177812/6665330/7681a3fc-cbd8-11e4-80c7-6c4e3aacc66b.png)

**Comment by piggyslasher** [comment]
how did you count this as 88px in the retina fvl?

Also are you zoomed in in any way. reset by hitting cmd + 0

**Comment by vLooz** [comment]
just saw your comment now, sorry. I made a screenshot and counted pixels via the selection tool in preview. But don't worry about retina, I think just focusing on normal screens for MVP is fine.

**Comment by piggyslasher** [comment]
#342

**Comment by piggyslasher** [comment]
ive updated a lot of font-weights as well. have a check on that too. so now we have light, medium and regular on both retina and non-retina. just tested it. looks nice :)

**Comment by piggyslasher** [comment]
i'm going to close this as I'm getting more specific mockups and issues. this is too general.
