### ISSUE TITLE
Public keys don't export properly

### ISSUE THREAD

**Issue by bilbof** [lavab/web#302]
I just made a new account. This got exported as a json. I have two public keys, one of which is legacy - don't know which. I can't export the keys in a readable format so I can submit them to mit.pgp.edu.

This is a problem because most encryption between lavaboom users (A) and non-lavaboom users (B) will be manual. B will need to find A's public keys on keybase.io or another key server, or be sent the key by A. If A can't retrieve their public key manually then the key exchange fails.

Solution: we need to be able to export keys one at a time in a readable format. In the first version it was possible to download the keys as a txt file. Json probably isn't the best option as some users may not be able to read this file type.

                "pub": [
                    "-----BEGIN PGP PUBLIC KEY BLOCK-----\r\nVersion: OpenPGP.js v0.9.0\r\nComment: http://openpgpjs.org\r\n\r\nxsBNBFT9wT0BCAC9h5J7xju60DfQPQE5R6rlXaxmnALpU7TnN73IOP9a13LI\nrb/l3FmHCxj5nC0ccrnD2F6Xg2FT00A1g3EuapL6FCJ8VaEifIeroybR9XJg\n1h9WMSU+N5B/SAJ5fZx/xz/Gg592ZYmXsKsyPdlvNTC6YMaghb3gmGlFZ4D/\nocnpLQi9V+iaK6/BYvVE98SS9GmRW+wb8WDQUuVGsKLo/T2OwklUwVnQ1ktj\nDY2ggowYDrja+yJwNTZAwbnGfKU4jiWEW8Cc/EPmHbFgGWzhErrOaHQXwmRY\n/VRDjmvA8GKOHxuLE1tDLcx2OLJHKi3YlT12YiZGfdv1AHUEHIiryktnABEB\nAAHNGGJpbGwgPGJpbGxAbGF2YWJvb20uY29tPsLAcgQQAQgAJgUCVP3BPgYL\nCQgHAwIJEJLVkzhJ/4zeBBUIAgoDFgIBAhsDAh4BAAB5ugf+M13KDhOJ86Cu\nh+TTt6gd5Bxy4UDM1pifqZNPj6Mm00tzUaLXLLEz4zzHLFzojJUbCPn3bp8l\nkw5jJ8yqW5LSIfOfEYsrkEHK99ekR96Vj0CYYzusmfWd2IskMjX5BXBkv9YH\nhq+aD+8u5OzSXCtr2IJzMZqwa4o/ILAn6DprBm7uA1aeutom++fBVbE1IuxP\nz7KOKGiohcHMon8PVCZg2096FZSVs2G/YRaWSsOanuPhs4kLcyM6+LEMMmeq\n9hh9/pGvC+zTYuE94lPbacccuxDBh6xh+Xk5pQqShJOoIbDWdxW1bOeJOdI3\n6zsXs89Qo8TFCh2M67B0N8LEe1y/hs7ATQRU/cE9AQgAyYcRqcsMbtHHSgSq\nNVPn6Xmxk4eUw0tLD6Sk1m90Smq+0ahNZLaKK3g9UmxtYASTlt1FlZ5DxWGo\n6BXGyVI4hPevPQv9uXt2UKipsCH1hasvm5+C0VHsTwbWwt5eI8bm7BnQgYH5\nJ0GLN3LcUph22aGhAgJ2UhQHfxN2holx8/bEdsTXQR3lOLfVQrPbpifY7jV8\n/hbdPqzIp7+L30fbWUJACYlzlvr5vLpzQQMtkRuD6p6UqcJ9RnEswCcUF1Qe\ndQM2bk9bmGtHHBAw2QeFqx5H/K28/HSrkkXIyHuc7XJxQQN6ZcRBau5WRwer\n7LODnxRJSwcaYYfOEmqt8nvADQARAQABwsBfBBgBCAATBQJU/cE+CRCS1ZM4\nSf+M3gIbDAAATNYIAI+LPjLClcOxY8Por3KP2yjb1mfWj98R8/syaDG9lbJi\ndgk/CjYgEKwC5GcX+ccJh9KAYSpZ5CMeWwogNaraPVy8N26Ejp1nwcSMG8Y5\nezLWOJ7BjwXW4afZaT+IXA1xZbENEIwKoPedrGKuoQi2ewiGR62BojR/NPoe\nIZHHK/P4AaYXtLvWFypge53vgDPlrLyqIPxAdGhdLzInjgnSr7hojnUeYz9K\nKylneAk6W2nk2SL1K06NLN6hK0XKGcGxgMPanXR/x+WMoHxPQgDwYWboCopz\nUH1sd4/r4+yskfmzHd2JNXGZQifha+MS3uo2dvXnHgb8ejT9kNS8ZXpFHyc=\r\n=sTZd\r\n-----END PGP PUBLIC KEY BLOCK-----\r\n\r\n",
                    "-----BEGIN PGP PUBLIC KEY BLOCK-----\r\nVersion: OpenPGP.js v0.9.0\r\nComment: http://openpgpjs.org\r\n\r\nxsFNBFUGthUBEADDvD6FNi9CSLC7xMsZxtOQLzzGMwGLQOzr2PAGxFKmU1Iw\npFGQUMhDRSlTyJjsEpEi3iAU2l/FI+OWogKJ9euRNym3Cbge+nS1wFfNLF5Y\nmHC279qKvziqZ5HPWiwEXAP5DZ/FsfyT/oWBzWX7LBAas6VRAvzRT6TH7w0N\n8nmPRElqfeZoSZ5xaVXdzPE3sf2JT46bnZ+9XsaIW9fS6ca7uVqg3x7THCVk\nhZrs3+H4vAoipBTqQClKKm/dNmQ3Nb3MSS8l8xVXC+cQtnGDh1elyZPKYxJL\nfj2u+TS2v3xNUvMMxAtKeiqK5pP/TWdiip2xMQToFyY4O4aLOgglNYW6oBlF\n10Wbo3NS17PigvVTol1FaAezEdXq1ETu69fnr/PNRUMYMfTF9Myne502berZ\nhivO844ygOeN+w1Pcd4oI05GjQE5bDWmBHMZpcDr4bd9D+sQoqK6RVTDEKez\nEq8iVSjc/GiUp/DCe6LFhadEj+QKz15nnKM6ouPSsyAcWqIlmHdVj/yeBqvR\npLdaD1vOimRjWsg8nshqHfqyP5u0Rq6Y8PZ1hdqt0GftGuITl8GNDHP2Rar8\n7d3417oA0W8DCBv8VSNk8z1AU9waRSu++dWx86288rw4xR6pMK6He3ZSugmb\ngPwRH3on4+zHvoAIR1rHSNmtAOirTcsZo1TNOQARAQABzRhiaWxsIDxiaWxs\nQGxhdmFib29tLmNvbT7CwXIEEAEIACYFAlUGthcGCwkIBwMCCRBpe99Ubs2v\npwQVCAIKAxYCAQIbAwIeAQAAB7sQAKBkCzoa78PeUWiVxRdxf3LJ5j32J50+\nZB4keut2EGnYbz+9j18Uir+rhh31aHHBB+e8cZh0dzLyF7n77qAYynoWNdPg\ndKEzeYdViamM/kWbfUO+o/3MXCj1KIlUrrK+T1HU5DSiROzROpYvyoXqs+Yj\nLV3V3eJz6qlALctTwBh/iM4yJymw95Iwf80DWhXNQhSkBfSAtE2vylMdJY6o\ntehxnWwpkcPZqVGG7Pwn4R810N5O31wewWdwPabUX6o9OPsXbtZI5fUc8a24\nT0Hy1yieJjO1hl7rJtYBP+lmYfP7tdDwiVOq1Wvz8V6uDREod/K8qctt3fmF\n0Y9fXE2OJa4PPBaNZC0lHR6ZIm4YccnGMqXpQISqku6q0IyXa4AtuqJsIA0D\nQWCKiUe0e4G/M3fYHpdLVRw4xNEv85YB5V39NXna7vVAeIN6nPZ9t6RC62jT\n5tR8iO8/ICMJT1sQv15XdqzGLunDbBq8OlTQF9spuUoz+foxzmgBMuBhYx23\n4pWatjmIFnhODZvlG+Ik9kuRJaMPxQvzM6nysnBuLkH9jrfRmLkdK508fnF2\nMaWecV5AeQAUdG+b441P7zuLRhBms885Mjm7ebYswek2n/vgilmxQ+uNVct4\n/hc3Mh7DdMx5Chrgm/lE5coc4wNsqe7jRHyiMrCD1MfXSblHGXKnzsFNBFUG\nthUBEADX06XT6TYJOOQt9Hg/62/9p85capLtYI2hf1a5w3Utvu1rNzBHkiC2\nCzRZ9bYN0vixYmMFODAj2hNeIf6xgTxHB/03n2bJBppVGleHBLFxAKpdnGYj\n9Qdp7Ck+jNa7zPhtZnrbI1Rq9kIf3hWkj2WP5zEqVkYGHqbgFjZ4PDUkXwdS\nOvuYw0RPQdWr/xO92LUDk2J/nT6scc059jQce/7tc3cgRKA19ZD0WvBbBRFr\noritZce3G0Fg1z6BsiNKPF4VJtuvt0RIPI5vlPmaWD6LtS/fuX2VtgWFT8Hk\n4Hy4xlu7WfPCPAMmgxPZLpoA+E+K+Sgy/+wFpFDs/6j+ofiWLYV2IlpgxC0o\ndMS0ZbWseTxX/K46oHO42lT2aZo8gmFce2ujJnJCNDUYESiyZjO5hncC32An\n1J16X+SqyrCb15sa12FgnXSaMNihmzqT9ZwLkQc/UOX22ZjsTBZKTCQIUMQQ\n7QK6b1ylTEGuvT4u1pMh41rx42Nj2Jsd2vuDA/N+Mlx+r1JacIw3cf4copAQ\nQMTzwF+ZICuZ+jCZvOUJk+I9yxOewq0A4BoC7V8UYRqCFgBLiuCuTRj6bXPD\nB+dzCE00YQynKMqH28jWXJQjoSAqktQ2wTKFyqS487s6UeTlY3VEaUwDBqRA\nm8YzkRfJGsYNCzjyShUeODNbiZeNQwARAQABwsFfBBgBCAATBQJVBrYZCRBp\ne99Ubs2vpwIbDAAAGbUQALUZ4mXEVOmKwn2E0iWawj/BGoeptv4k0lnZV2oF\nd0Zz56W8pmP7hGwZN61NFAYo3Iv9bx8x9KHXYVDbwj94BZK9DSU1kJ9Q3Xmn\n/q5o94YJRVI7rqyS6497EhLLQZFzREGZwcTQeZjthNBeSyWRFyvVh6V+yHk2\noEyuupfXybX93+EZs+ZfoLeZEo2WzjjdKxMICWiVdWsJ8Y0b0T3q8YNlecKl\nO1SBN3KlQ5XmtvYEbch+WkOCWO49hvzKxq4VGGiqmHURo7wZENORMS/3UvnR\nbtyJM5tmM7NYTc8So9cY635uYsFE6Kcrt8fKPDN3gPd0k2OaqmK0dC0nYUIi\n8U2MpLXhQtfV4aq5Sq0qZOAai1yJPVf82g1EOueiGp8eMmqkZO4LRtgrTaei\nulbWTQlC86jGKK8pbuwx4JwM1cKIr3u9kNtZRgfwXCeBnd8v+rDFaL2zOYJs\n3QUQmH+2Ypc9SeUy5Bs0oGDOlY3jObHhhbf/IFNSnO0Cdrw/fdc0jpyz9xn4\nt/fwKdihb/7ZlKE9MpRTuSCB3i/WtXcOUTPkxm/+e+fAF7VQpYoJZDaQLxBD\n8ipeQxtdEJ/I6OlfdxKYnvZ7qjcfukmZ6Un+OV41rN7FrmP2fV/vbv6c2zMN\nphk+C6O+uKDPInBOisdzC9JgUidiZSAaMLEoS9+4Yzlq\r\n=ALsq\r\n-----END PGP PUBLIC KEY BLOCK-----\r\n\r\n"
                ]

**Comment by bilbof** [comment]
![screen shot 2015-03-16 at 12 29 23](https://cloud.githubusercontent.com/assets/8124374/6665512/8fdb2632-cbda-11e4-85fc-71691dfc357d.png)
![screen shot 2015-03-16 at 12 39 49](https://cloud.githubusercontent.com/assets/8124374/6665511/8fd8c1e4-cbda-11e4-821b-6a85209759a3.png)

**Comment by let4be** [comment]
The thing is, this kind of keys export was just for our internal use as suggested by @andreis 
so we export public + private key pair with some sort of meta information on top of it

What do you think can we do there @andreis?

**Comment by andreis** [comment]
We should let users download or copy-paste individual keys.

**Comment by let4be** [comment]
added new button, not sure about UX here
does it look ok(on .co) @vLooz ? 
probably we could add new popup where user could copy paste or download the key?

**Comment by andreis** [comment]
FvL is working on this now, we'll basically makes some changes to how we display keys and move everything non-key related to a new `Settings` section, `Security`

**Comment by flixi** [comment]
Status @andreis?

**Comment by andreis** [comment]
No idea. @vLooz ?

**Comment by let4be** [comment]
Let's decide what format do we want to see and where
Currently we have custom key export/import format and I would suggest to keep it but add a separate export action for keys that are going to be imported on such services as https://pgp.mit.edu

**Comment by let4be** [comment]
Probably this should be available from settings && contacts pages only

**Comment by andreis** [comment]
Let's wait for FvL's designs.

**Comment by piggyslasher** [comment]
closing this: please refer to #326
