### ISSUE TITLE
Contacts functionality

### ISSUE THREAD

**Issue by flixi** [lavab/web#303]
In the dropdown, underneath Add a public key should be request public key, which then in turn should popup a new compose window with a pre filled text and the attached public key of the account that initiated it.

**Comment by let4be** [comment]
Are there any designs how it should look like? @mlooz

**Comment by vLooz** [comment]
mlooz is my brother Moritz, who offered to look for bugs in later stages. Pls don't link him right now ;-) 

I'm doing improvements of the design and workflow of the contact section. I'll add flixi's idea and send you the design mocks and guidelines hopefully end of the day.

**Comment by let4be** [comment]
sooorry :)

**Comment by flixi** [comment]
@vLooz Can you share your designs with us?

**Comment by vLooz** [comment]
Design sheets are https://trello.com/c/61OAUNQF/40-303-contact-functionality

I'm aware that a lot of this is not MVP, but the basic key adding functionality should be implemented. 
Please let me now via Slack, when you guys need feedback. Thx

**Comment by piggyslasher** [comment]
@flixi - this milestone is lavaboom 2.0 so should i treat this as important? i'm running of other important tasks.

**Comment by flixi** [comment]
Yes. Please.

**Comment by piggyslasher** [comment]
getting there. added dropdown support. should be done tomorrow. then will assign to @let4be 

![image](https://cloud.githubusercontent.com/assets/1991125/6971687/d556ae64-d9b0-11e4-9148-44409cf34e27.png)

**Comment by piggyslasher** [comment]
do we need the option for remove key? it is not in the new design. currently there is a remove key button.

new design
![image](https://cloud.githubusercontent.com/assets/1991125/7008766/358347ce-dcc8-11e4-8c51-5e6563cc660d.png)


current design
![image](https://cloud.githubusercontent.com/assets/1991125/7008811/617e3a5a-dcc8-11e4-8c5a-c815927d841a.png)

**Comment by piggyslasher** [comment]
current status:
![image](https://cloud.githubusercontent.com/assets/1991125/7009475/1520e7fc-dccd-11e4-992f-97ca428f5b4e.png)

![image](https://cloud.githubusercontent.com/assets/1991125/7009537/99639d52-dccd-11e4-8deb-18a0c5bbd7c8.png)

little more work left. but we're getting there.

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/7011019/3a3b77b8-dcd8-11e4-9cd0-390c03696989.png)

@vLooz - more to go but now all dropdowns follow your guidelines, including the one in compose.

**Comment by vLooz** [comment]
Looking good @piggyslasher! Great work! 
If you could replace the "upload key Icon" with the "Upload PublicKey-icon" from here: https://trello.com/c/ZrFuUKAO/42-new-icons-2, this is good for MVP.

**Comment by piggyslasher** [comment]
i believe for MVP only this part needs the finishing touches.

**Comment by piggyslasher** [comment]
we can't actually follow the widths you've mentioned in your design. because some of our widths are fluid. things like icons and the navigation panel on the left have fixed widths. they increase/decrease depending on the screen-size. but the heights are fine.

**Comment by vLooz** [comment]
As long as the widths are consistent through all settings and contact screens, it doesn't matter if they are fixed or depended on the general screen widths.

**Comment by flixi** [comment]
Can you fix the text though, up there?

**Comment by piggyslasher** [comment]
text boss? how do you mean? the gap between the paragraphs?

**Comment by flixi** [comment]
encrypted emails -> encrypt -(ed)emails

**Comment by piggyslasher** [comment]
i think the missing word is 'send'. will do that.

**Comment by piggyslasher** [comment]
- [ ] text for dropdown is now (@flixi):
![image](https://cloud.githubusercontent.com/assets/1991125/7200274/0c6a8e4c-e52e-11e4-9cae-89103e58994e.png)

**Comment by flixi** [comment]
Good.

**Comment by piggyslasher** [comment]
please comment on this 2.1 issue #325 if you have any further queries. i will be updating those mocks with the missing ones from trello
