### ISSUE TITLE
recipient is not shown in "Sent" Mail detail view

### ISSUE THREAD

**Issue by vLooz** [lavab/web#308]
![recipient is not shown in sent mail detail view](https://cloud.githubusercontent.com/assets/11177812/6729356/e7b30542-ce31-11e4-86f1-260b88b0bfac.png)

**Comment by let4be** [comment]
caused by https://github.com/lavab/api/issues/108

**Comment by flixi** [comment]
![bildschirmfoto 2015-03-19 um 13 15 12](https://cloud.githubusercontent.com/assets/707993/6730190/567be680-ce3a-11e4-9cbf-d75671b232b2.png)
![bildschirmfoto 2015-03-19 um 13 15 22](https://cloud.githubusercontent.com/assets/707993/6730191/569bbc94-ce3a-11e4-82c6-a61cf2b5f7f5.png)
![bildschirmfoto 2015-03-19 um 13 15 26](https://cloud.githubusercontent.com/assets/707993/6730192/569d56c6-ce3a-11e4-976b-14ed192b3953.png)

**Comment by let4be** [comment]
Known issue, please see: https://github.com/lavab/api/issues/107

p.s.
Please @flixi create separate issues for the things not related to the current issue
keeping different things in the same issue on github makes almost impossible to track them/find them
