### ISSUE TITLE
Encrypted email isn't shown in "sent" folder, whereas unencrypted emails are being shown alright

### ISSUE THREAD

**Issue by flixi** [lavab/web#309]
![bildschirmfoto 2015-03-19 um 13 15 12](https://cloud.githubusercontent.com/assets/707993/6730287/57cfa728-ce3b-11e4-8d67-f0b124ee19ae.png)
![bildschirmfoto 2015-03-19 um 13 15 22](https://cloud.githubusercontent.com/assets/707993/6730286/57cdf2ca-ce3b-11e4-81a2-f658d3f80e68.png)
![bildschirmfoto 2015-03-19 um 13 15 26](https://cloud.githubusercontent.com/assets/707993/6730285/57cbc81a-ce3b-11e4-81a6-8f196cfd25b0.png)

**Comment by let4be** [comment]
caused by: https://github.com/lavab/api/issues/107
as soon as this resolved this will be auto-fixed
