### ISSUE TITLE
Logout button is being hidden

### ISSUE THREAD

**Issue by let4be** [lavab/web#311]
@piggyslasher I once fixed this but it somehow came back...
![image](https://cloud.githubusercontent.com/assets/4147061/6730593/2a10de10-ce4f-11e4-8d0b-f089a9a0996c.png)

**Comment by piggyslasher** [comment]
@let4be i'm not seeing this. not sure where youre seeing this bug. is anyone else seeing this?

**Comment by flixi** [comment]
Nope.

**Comment by let4be** [comment]
This thing appears only when you hover over links i.e. for example "Inbox" label
I'm uing chrome from windows

**Comment by flixi** [comment]
Can't seem to reproduce.
Even though I tried under my vm in chrome running windows 8.1.
Neither in Safari with changed User Agent settings to Chrome Windows in the Developer toolkit.

**Comment by piggyslasher** [comment]
just checked on chrome/win7 - cant replicate. are you having some customized setting for you status bar?

**Comment by let4be** [comment]
Same thing happens from firefox, opera and internet explorer on my machine
When you hover links this things overlays and hides logout button
Solution: move logout button to the other place

**Comment by let4be** [comment]
There was a idea somewhere to swap "Lavaboom 2015" and Logout button in places

**Comment by piggyslasher** [comment]
i believe @vLooz wanted the logout button to be stuck to the bottom of the screen.

**Comment by piggyslasher** [comment]
its more good for ux to bleed to the edge to the screen. but then again. i never saw this issue happen.

**Comment by let4be** [comment]
have no idea why only I have this issue - it's the same on all browsers

**Comment by piggyslasher** [comment]
slack has the logout button in the same place as well. i think this should just be left alone. its the the standard browser status bar.
![image](https://cloud.githubusercontent.com/assets/1991125/6764761/f4a1bf0c-cffb-11e4-84e3-3902dc60f1f5.png)
@flixi

**Comment by flixi** [comment]
I would leave this issue open for now. Let's see whether or not others also have the same issue.

**Comment by piggyslasher** [comment]
i've changed it to a <button> tag and moved it back to the bottom. works.

**Comment by bilbof** [comment]
Haha, this is why the logout button is 10px from the bottom of the page?
