### ISSUE TITLE
Include the name of the node that actually serves you the interface

### ISSUE THREAD

**Issue by flixi** [lavab/web#313]
For example served by maggie or marge or homer...
![bildschirmfoto 2015-03-19 um 17 45 00](https://cloud.githubusercontent.com/assets/707993/6735756/a89aa19c-ce60-11e4-9c3c-3aeb6d72e394.png)
Similiar to this.
Include it right below the menu.

**Comment by let4be** [comment]
@pzduniak where could I take this information from?
I've tried /info and /me API calls but it seems there is no required information
tho, /info has

docs_url: "https://docs.lavaboom.io/"
message: "Lavaboom API"
version: "v0"

But I guess it's different from what we would like to see

**Comment by let4be** [comment]
If we want to show exactly the node's name which gives us static assets, hm... we could for example pass the node name in `server` http response header

**Comment by andreis** [comment]
Yeah, the header idea is the most practical imho

**Comment by let4be** [comment]
now web reads X-Powered-By header ;)

could be useful for further customization:
https://github.com/lavab/web/blob/develop/src/translations/en.toml#L11-11
https://github.com/lavab/web/blob/develop/src/blocks/inbox/emails.jade#L7-7
https://github.com/lavab/web/blob/develop/src/index.jade#L48-48
