### ISSUE TITLE
should we really restrict the display name's length

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#314]
![image](https://cloud.githubusercontent.com/assets/1991125/6747928/def1bc34-cf1a-11e4-9c9f-695689b48255.png)

**Comment by let4be** [comment]
Probably we should not, it's easy to change
All validation rules for login/signup are declarative and defined inside jade files, please see:
src\blocks\login\details.jade

for displayName field we currently have minlength=4

**Comment by flixi** [comment]
Yes, 4 is alright. 1-3 displaynames length are reserved for employees and freelancers.

**Comment by let4be** [comment]
nice @flixi :)

**Comment by let4be** [comment]
But I guess we have only client side validation now, so later if we're going to impose any restrictions we will have to add server side validation
This data is being stored in unencrypted way(under user.settings) so we can do this
