### ISSUE TITLE
Duplicated buttons?

### ISSUE THREAD

**Issue by let4be** [lavab/web#315]
What is the purpose of the same star, spam and delete buttons on the top panel?

![image](https://cloud.githubusercontent.com/assets/4147061/6747914/c5f82184-cef0-11e4-9c91-4276fc48c316.png)

I suppose one group is for threads and another is for emails inside thread, but this would sound weird...

**Comment by let4be** [comment]
I mean how could it be possible to mark just a single email inside a thread as spam or delete a single email from somewhere in the middle of thread's conversation...

**Comment by vLooz** [comment]
It's supposed to be the same functions @let4be. 

I think it's not a bad thing to be able to delete a single mail from a thread. 
Is that a technical problem?

We don't need the double STAR and SPAM though, I agree with you. 
Get rid of them in the right header.

**Comment by vLooz** [comment]
Github Bug... have to write the same thing again.

I agree with you. Get rid of the STAR and SPAM button in the right header
