### ISSUE TITLE
Reply button doesn't work properly

### ISSUE THREAD

**Issue by flixi** [lavab/web#317]
Please make sure that stuff like the emails contents are indented with a line (html) or a > (plaintext) are displayed and sent upon hitting reply.

**Comment by let4be** [comment]
I've added "reply" and "reply to" but can't test it - Mailer is dead

**Comment by flixi** [comment]
Try again please.

**Comment by let4be** [comment]
Just checked - the same, mailer doesn't work at all
I will try to do some synthetic tests on mock data(but it's still way too slow for our needs)

**Comment by let4be** [comment]
Mailer is working again, just checked on some emails - seems to work
It's in develop, but not deployed so can be tested only locally

**Comment by let4be** [comment]
implemented, need feedback on this before closing as I feel something might be missing here

**Comment by flixi** [comment]
So, I'm not sure whether or not this is implemented.
And if it is, then we can close it.
But it seems that you do not get to see the original message upon hitting reply.
Plus, I get neither the message nor all of the senders when I hit reply all.

**Comment by let4be** [comment]
Currently it does not show original message in compose screen - same as in gmail when using reply to.
but the original message user replied to should be visible when delivered
Regarding reply to all going to fix this

**Comment by flixi** [comment]
Show it please.

**Comment by let4be** [comment]
OK this should be fixed in develop.
Now all emails user sends looks exactly as what is going to be send for direct/reply to/reply to all/forward email types.

I will push everything to master in the nearest time and Pitor will deploy it
