### ISSUE TITLE
Print output doesn't work

### ISSUE THREAD

**Issue by flixi** [lavab/web#318]
If I type in cmd + p I get this as an output.
http://qs.lc/yyqjh
I would like it to print out the email that I just selected.
With our Logo ontop.

**Comment by let4be** [comment]
This can be achieved with some css media query magic, I guess

**Comment by piggyslasher** [comment]
yes. css media queries.

okay. will work on this over the weekend.

**Comment by vLooz** [comment]
Is this really a MVP feature? Just wondering :)

**Comment by flixi** [comment]
Yes, I need it in order to print some receipts, especially those from github and from harvest.

**Comment by piggyslasher** [comment]
almost complete. now displaying only the email with borders/shadows removed. only request not implemented is the logo on top. just the regular logo we're using now is fine yes?

**Comment by piggyslasher** [comment]
okay, with logo now, but i think we need to use a different logo. maybe a black/white one.

**Comment by piggyslasher** [comment]
@vLooz - can you have a quick check on the output? wanna close this. main this that remains is the logo that looks very print-unfriendly.

also there's a lot of improvements that can be done

  - set font to helvetica, arial
  - unstyle links (maybe we shouldn't unstyled completely, but maybe make it a lighter gray)
  - maybe show attachments as a normal list

but for now, for MVP, please give me your input. notable on page margins, vertical spacing. just a rough list will do.

**Comment by flixi** [comment]
where is it implemented?

**Comment by piggyslasher** [comment]
its already in the main develop branch. just press ctrl+p

**Comment by piggyslasher** [comment]
multi-page print output needs to be fixed. will work more on it tomorrow

**Comment by flixi** [comment]
:thumbsup:

**Comment by piggyslasher** [comment]
going to close this for now. please re-open if you see any issues. i've created another issue #371 for the issue with the logo.
