### ISSUE TITLE
Please add tooltips or titles to the buttons in compose window

### ISSUE THREAD

**Issue by flixi** [lavab/web#320]
![bildschirmfoto 2015-03-20 um 15 14 11](https://cloud.githubusercontent.com/assets/707993/6753098/f4ecbc20-cf13-11e4-82fd-3679e39cac12.png)

"Add CC,BCC" "Send" "Discard" Make those i18n please.

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/6757185/22c81a58-cf6a-11e4-8c74-39e9fbd3ef6f.png)

will move all modals a few pixels down (i want to do this and check if i break anything but tooltip functionality is working)

**Comment by piggyslasher** [comment]
@vLooz

**Comment by piggyslasher** [comment]
going to close this as it doesnt hide on the top of the browser anymore. modal windows are now have more space on top to show stuff.

![Uploading image.png . . .]()
