### ISSUE TITLE
images inside email (i.e. drag image into compose) takes 3+ minutes to decrypt

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#321]
I have a 145kb image that i dragged into an email and it didnt take this long the last time. is it because our keys are bigger now?

**Comment by let4be** [comment]
@piggyslasher most likely this is the problem because your browser uses plainjs openpgp implementation - its VERY slow
could you please try to reproduce the same issue and issue with slow key generation on mail.lavaboom.co? or on .com?

**Comment by let4be** [comment]
added separate issues with more details
https://github.com/lavab/web/issues/339
https://github.com/lavab/web/issues/340
