### ISSUE TITLE
inbox keeps showing zero emails after i switch labels.

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#322]
I just sent myself two emails and both were listed. But when I switch labels or refresh the page I lose my emails.

![image](https://cloud.githubusercontent.com/assets/1991125/6756681/6c8cbc10-cf66-11e4-8fa4-c1e690dcbd70.png)

Let me know If I am doing something wrong because I can't test my inbox styling now. Thanks.

This is on dev branch, which is working with .com api.

**Comment by piggyslasher** [comment]
to add to that - sent messages are also empty

**Comment by let4be** [comment]
I'm looking into this, couldn't reproduce exactly this but found something else - probably related

**Comment by let4be** [comment]
Empty sent messages caused by API bug - nothing can be done here until it's fixed
Regarding empty Inbox it's weird, I could suspect some cache issue but if it was cache issue page refresh would fix it...

**Comment by let4be** [comment]
Issue was tracked down to this:
https://github.com/lavab/api/issues/111
