### ISSUE TITLE
Gulpfile.coffee

### ISSUE THREAD

**Issue by andreis** [lavab/web#327]
Would rewriting the Gulpfile in coffee be useful?

http://pem-musing.blogspot.de/2014/02/a-gulp-of-coffee-your-gulpfile-in.html

Just an idea.

**Comment by let4be** [comment]
No. I keep away from coffee and advice this everyone
But gulpfile needs some refactoring, cleanup and moving to es6, see https://github.com/lavab/web/issues/290
