### ISSUE TITLE
I think we should show who youre logged in as somewhere on the screen

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#329]
like "Logout Vik" in the logout area, or somewhere to indicate the current account. I believe this is quite important.

assigning to you @flixi so you weigh in.

**Comment by piggyslasher** [comment]
@vLooz

**Comment by let4be** [comment]
Support this, now it's hard to identify which account you are on.

**Comment by vLooz** [comment]
I suggest to connect it with the Logout Button - like it's done in Slack. 
We could also have a "change account" option here.

Is that technically feasible? @pzduniak @let4be 

![bildschirmfoto 2015-03-22 um 12 54 29](https://cloud.githubusercontent.com/assets/11177812/6769236/e00c1ed8-d092-11e4-8afc-7c63bd6af124.png)

**Comment by flixi** [comment]
I like the idea, however regarding switching accounts that'S not an MVP feature.

**Comment by andreis** [comment]
:+1:

**Comment by let4be** [comment]
implemented, if this needs additional styling open new issue

**Comment by vLooz** [comment]
What do you guys think about this apporach @flixi @bilbof @andreis ?
![new user logout area](https://cloud.githubusercontent.com/assets/11177812/6809989/5a8dee8a-d25e-11e4-906e-ad8aadf4b216.png)

**Comment by let4be** [comment]
Looks good, @piggyslasher style this when you get time
