### ISSUE TITLE
"Put back to inbox" button needed for Spam and Trash

### ISSUE THREAD

**Issue by vLooz** [lavab/web#330]
Once I have deleted a mail or marked it as spam, I can't "unspam" or "undelete" it. 
We need buttons for this!
An easy fix probably would be to put them into the v-dropdown menu in the left header.

Here are screens of the problem
![bildschirmfoto 2015-03-22 um 11 42 16](https://cloud.githubusercontent.com/assets/11177812/6769005/a5e42dcc-d088-11e4-94fa-7e5bfb61cff8.png)
![bildschirmfoto 2015-03-22 um 11 42 56](https://cloud.githubusercontent.com/assets/11177812/6769006/a6085b98-d088-11e4-842f-f9ef17b0f6f2.png)

**Comment by let4be** [comment]
um, to implement this we first need to know original label of the thread
For example it could be SENT only or INBOX only

another solution would be not remove original labels when we move thread to SPAM/TRASH just filter out such threads client side

**Comment by let4be** [comment]
api modification required for proper implementation: https://github.com/lavab/api/issues/113

**Comment by let4be** [comment]
Filtering could be done on client side but it over-complicates things(and kills performance) as we rely on offset/limit and this will break if perform client-side filtering, i.e. we will have to make subsequent request(s) without any guarantees.

**Comment by vLooz** [comment]
hey guys, I made some new icons, which where missing so far. Find them here as SVG's:

https://trello.com/c/uFc9lUin/41-new-icons

the surrounding measurements of the icons are 22px x 44px

Ask me, when we need to fiddle them into the Icon font @piggyslasher

**Comment by andreis** [comment]
AFAIK @pzduniak just implemented the necessary functionality, so it should be possible now.

**Comment by vLooz** [comment]
Can we implement these 2 buttons now? From my POV they are among the most important missing features for MVP. @piggyslasher

**Comment by piggyslasher** [comment]
ive assigned it to @let4be - he has to display them based on the angular router :)

**Comment by let4be** [comment]
though we need proper icons @piggyslasher

**Comment by piggyslasher** [comment]
Its there already. `.icon-empty-trash` and `.icon-put-back`
```less
.icon-empty-trash:before {
	content: "\e60a";
}

.icon-put-back:before {
	content: "\e60b";
}```

**Comment by piggyslasher** [comment]
nvm, i did it.

**Comment by piggyslasher** [comment]
@vLooz 

![image](https://cloud.githubusercontent.com/assets/1991125/6992367/69a87c90-dafc-11e4-873c-50713340c515.png)

all good?

**Comment by vLooz** [comment]
looking great @piggyslasher :-)

**Comment by vLooz** [comment]
The "Put back" apparently was lost during moving the icons.
Please bring it back for Trash and Spam @piggyslasher

**Comment by flixi** [comment]
Status?

**Comment by let4be** [comment]
huh, it was fixed long ago

**Comment by let4be** [comment]
@piggyslasher please close your own issues if they are implemented/fixed
