### ISSUE TITLE
Hide Menu-items and Icons, until they working properly

### ISSUE THREAD

**Issue by vLooz** [lavab/web#331]
I think it might be confusing and frustrating, when the user sees e.g. the Drafts feature in the menu bar and expect them to be implemented, but they aren't. 

Spam works one way, however I can't put a mail back to inbox, once it was moved to Spam. See issue #330. 

In my opinion we should hide items in the menu bar and the connected icons in the left header until the regarding feature work properly. What do you think @andreis, @flixi ?

![bildschirmfoto 2015-03-22 um 11 54 46](https://cloud.githubusercontent.com/assets/11177812/6769101/191b2034-d08e-11e4-88f2-51f6c2a94ce7.jpg)

**Comment by flixi** [comment]
THis should not be too much work!

**Comment by let4be** [comment]
Spam is basically ready and can be included in the MVP, just need one API feature implemented:
https://github.com/lavab/api/issues/113

**Comment by bilbof** [comment]
Haha, @vLooz you're 3 days ahead of me.  https://github.com/lavab/web/issues/351

**Comment by let4be** [comment]
new labels workflow implemented, trash && spam should work properly now
buttons are being hidden if nothing selected
