### ISSUE TITLE
SECURITY: I can view an entirely different mailbox

### ISSUE THREAD

**Issue by flixi** [lavab/web#332]
So, here is the steps I underwent.
Logged in as hello@lavaboom.com. Logout.
Logged back in as felix, and this is what I saw.
![bildschirmfoto 2015-03-22 um 14 36 08](https://cloud.githubusercontent.com/assets/707993/6769563/435b3b28-d0a1-11e4-8e4c-1fe9f8f2739f.png)
This isthe Inbox from the hello account.
Triedd it now multiple times, and it seems to always be this result, if I log in as hello first.
If I don't log in as hello first nothing will happen and it'll just show me the respective inbox.
![bildschirmfoto 2015-03-22 um 14 41 57](https://cloud.githubusercontent.com/assets/707993/6769571/b1f6ac70-d0a1-11e4-8cf4-8c1b67c7dee4.png)

THere seems to be a thread mismatch happening, it seems as thugh the inbox is still in the browsers cache and gets loaded from there rather than executing a command.

**Comment by let4be** [comment]
It seems to be fixed in develop during recent updates, if it's not - reopen
