### ISSUE TITLE
sometimes upon refresh, we can see the email itself before the threads load.

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#335]
![image](https://cloud.githubusercontent.com/assets/1991125/6770294/cd52cfee-d0f6-11e4-99e8-a26ca2e65c40.png)

not sure what to do with this one. should we force hide the email till threads load?

**Comment by let4be** [comment]
We request data from API in parallel, so it's quite common to get mail list for thread before all threads for given label
We can of course hide emails until all threads are ready, but imho it's fine to see emails before threads loaded

**Comment by flixi** [comment]
Yes, please do that, as it seems odd to the average user.

**Comment by flixi** [comment]
Should not make too much work, if it does though please do not do it.
