### ISSUE TITLE
App becomes unresponsive for minutes when i open an email with an embedded image

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#338]
took 9 minutes to view this email. even loading spinner isnt shown as there's so much cpu being taken up by decoding the embedded image.

possible solution
- store img's src as another variable in email or as an array of variables.
- load/decrypt email, then put the loading indicator in place of images while the src is being decoded
- set decrypted src attribute of image after decrypting image.

if this isnt done, the user is pretty much going to think the apps busted. as nothing is tell him that something is being done.

**Comment by let4be** [comment]
As I said before such kind of issues are related with fall back to plain js openpgp(instead of web crypto) implementation, no need to open ticket for each one ;)

**Comment by piggyslasher** [comment]
tab goes blank but it still using cpu on emails with multiple images

**Comment by piggyslasher** [comment]
sorry! i forgot the dupe.

**Comment by let4be** [comment]
added separate issues with more details
https://github.com/lavab/web/issues/339
https://github.com/lavab/web/issues/340
