### ISSUE TITLE
Debug a case when openpgp fallbacks to plain-js

### ISSUE THREAD

**Issue by let4be** [lavab/web#340]
The support is available but on some machines it fallbacks to plain-js

**Comment by let4be** [comment]
Regarding @piggyslasher report this has been caused by:
http://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features

i.e. openpgp uses web worker in order to perform crypto calls(key generation, encryption, decryption) and on develop they are being hosted on unsecure origin...
so basically this is develop only problem

**Comment by let4be** [comment]
Why this happens on his machine but it doesn't on mine?
Because of this:
> “Secure origins” are origins that match at least one of the following (scheme, host, port) patterns: 
(https, *, *)
(wss, *, *)
(*, localhost, *)
(*, 127/8, *)
(*, ::1/128, *)
(file, *, —)
(chrome-extension, *, —) 

I access my development configuration on localhost(I have gulp running inside VM with proper NAT setup)

**Comment by let4be** [comment]
So basically solution to this problem is accessing Lavaboom on localhost when you running develop build locally.

**Comment by let4be** [comment]
You can setup NAT if you run inside VM
or simply alert web/gulp/config.js with proper values for 
livereloadListenAddress: '127.0.0.1',
listenAddress: '127.0.0.1'
and add this to .gitignore!

**Comment by piggyslasher** [comment]
hrmm. things _do_ seem faster. sadly, it still takes about 45s - 1min seconds to decrypt emails with images.

**Comment by let4be** [comment]
@piggyslasher do you see any warnings displayed?
