### ISSUE TITLE
Reduced Mail display for MVP: without 2 lines of mail content preview

### ISSUE THREAD

**Issue by vLooz** [lavab/web#342]
The 2 lines of mail content preview are not possible for MVP, so we don't show them. 

To avoid touching an issue more times than necessary however, I'd suggest to implement the Mail list view UI design as close as possible to the final version. 
Just do not show the mail preview. It will leave a blank space then, but we can just fill it once we have the preview functionality in place. 

Your ideas @andreis @flixi ?

This is the UI for a version without preview (it's the original just without preview :-) @piggyslasher 

![mvp mail display without content preview](https://cloud.githubusercontent.com/assets/11177812/6779131/2ca1353c-d159-11e4-9dd7-3a2c669f3b1e.png)

**Comment by flixi** [comment]
I like the idea. It leaves room for the future.

**Comment by piggyslasher** [comment]
getting there :) I've also made a lot of the dimensions follow your mock exactly
![image](https://cloud.githubusercontent.com/assets/1991125/6814201/812b7536-d2b7-11e4-8132-0c1d4ba92725.png)

**Comment by piggyslasher** [comment]
will mark this complete and work in #301
