### ISSUE TITLE
attachment icon wont show in thread list

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#346]
![image](https://cloud.githubusercontent.com/assets/1991125/6808614/ee5fd598-d28f-11e4-8397-0f2803946027.png)

its because
```thread.attachmentsCount : undefined```

even in the email you sent to me @let4be, which has 2 attachments - not sure if this is you or @pzduniak - pls assign accordingly :)

**Comment by let4be** [comment]
https://github.com/lavab/api/issues/116
Okay, first it was renamed on API side from attachments_count to files_count, but it still doesn't work. Going to take count from the manifest
