### ISSUE TITLE
Encryption keypair must be decrypted at every login with Sync enabled.

### ISSUE THREAD

**Issue by bilbof** [lavab/web#349]
Every time I login I have to go to Settings:Keys and decrypt my keypair. However my keypair is already in my browser cache so this shouldn't be necessary.

**Comment by let4be** [comment]
It entirely depends on "this is private PC" checkbox you see when you login.

Basically when Sync is enabled it simply means that we will store a copy of *encrypted* private key on the server side. 
So when you login for the first time with "remember me" ticked web client remembers the *authentication token* it gets from the server not the plaintext password(security reasons)

So when your decrypted private key is not available, you will have to do one of this things:
- decrypt it manually after Sync restored it(under settings)
- logout from account and login again, thus providing a password web client uses to decrypt restored private key and cache it under session/local storage(depends on "this is private PC" checkbox)

**Comment by let4be** [comment]
In summary:
when you have Sync enabled and login with "this is private PC"(not ticked)  && "Keep me logged in"(ticked) it will remember you but won't save decrypted private key longer than for one browser session.

**Comment by let4be** [comment]
probably we could show some warning or make such behavior not default(for pro users only)
ideas welcomed
@andreis @flixi

**Comment by bilbof** [comment]
Ah, this is pretty unclear, but I got it to work. There's no point keeping you logged in if you have to type in your password again, right?

Could we remove the tickbox 'keep me logged in' at login?
Possible replacement is a prompt the first time user logs out of service with options 'keep me logged in' + 'log me out'. The prompt would inform users that they're going to be kept logged in.

Is this some security feature though? :disappointed:

@vLooz we're talking about an annoying security feature that keeps you logged in but encrypts all your emails. UX advice needed :smile:

**Comment by andreis** [comment]
I'm also in favour of removing the "keep me logged in" field, especially since we have such a large and obvious logout button.

**Comment by flixi** [comment]
In terms of security it makes more sense to logout the user and to not allow him or her to be kept login.
Therefore I am 1 in favor of removing the keep me logged in functionality at the beginning and further more to do not display any prompt ever!

**Comment by let4be** [comment]
So if I understood correctly:
- remove "remember me" checkbox
- treat "this is private computer" as "remember me"
basically if computer is not private there is not reason to remember user ;)

**Comment by flixi** [comment]
Yes. ;)
