### ISSUE TITLE
Reply to misunderstanding? / Moving reply buttons to new position

### ISSUE THREAD

**Issue by let4be** [lavab/web#350]
Currently we have those 3 buttons
![image](https://cloud.githubusercontent.com/assets/4147061/6826302/825708b2-d311-11e4-9d50-08a16c10bcd1.png)

"reply to", "reply to all emails" and "forward thread"
It's all good and nice but how am I going to use "reply to" button to reply to some **particular** email

I think "reply to" button should be located inside each email

@vLooz, @andreis , @flixi ?

**Comment by andreis** [comment]
Or just do what Mailbox does and do both. Email-specific buttons can be visible on hover (desktop) or when viewing a particular email (touchscreen), thread-specific buttons reply to / forward the last email in the thread.

**Comment by let4be** [comment]
hm... I thought "Forward to" should forward the whole thread
@andreis ?

**Comment by vLooz** [comment]
I agree with @andreis, In this case we should have the 3 buttons inside every mail. Let me create a mock

**Comment by flixi** [comment]
Nope, forward should definitely engulf the whole thread up until the email selected.
It might happen that I do want to forward a specific part of a conversation to a tird party without compromising the whole conversation.

Soo, I agree with @andreis regarding the hover or selected emails fields.

**Comment by vLooz** [comment]
Here you go. Note that I moved the remaining "move to trash" icon to the left and combined them with the icons from the left header. Would that be an easy or big change for you guys? @let4be @piggyslasher 

![2015-03-26_move 3 buttons into mail-01](https://cloud.githubusercontent.com/assets/11177812/6845770/2f18d818-d3b8-11e4-8c6c-27a5c6dccd66.png)
![2015-03-26_move 3 buttons into mail-02](https://cloud.githubusercontent.com/assets/11177812/6845771/301a9314-d3b8-11e4-93ad-a80799beab30.png)

**Comment by flixi** [comment]
Awesome work, as always, I'm really really impressed.

**Comment by piggyslasher** [comment]
so am i :) but whats the deadline for this. it super easy moving the buttons in the action bar (black bar on top) but the 3 buttons at the bottom of the email - mvp? tomorrow?

**Comment by piggyslasher** [comment]
and super thanks for the measurements @vLooz

**Comment by piggyslasher** [comment]
#358 i've created a new issue about the attachments styling because thats easy. i can do that by tomorrow. please mark this with a version deadline so i'll know. thanks.

**Comment by vLooz** [comment]
What do you guys think, is this MVP or not? @flixi @andreis

**Comment by let4be** [comment]
I already moved reply to, reply to all, forward buttons inside each email ;)
Some styling required though @piggyslasher

**Comment by andreis** [comment]
Not really MVP, but good to have, so work on it if you don't have anything else to do

**Comment by piggyslasher** [comment]
@let4be - which branch have the buttons been moved in? i pulled from develop - dont see the change.

**Comment by piggyslasher** [comment]
i've created the three new buttons in the mail action bar - you can link them when you move the controller code @let4be - assigning to you now. i'm creating a separate issue called 'mail button-group styling'

#370
