### ISSUE TITLE
Do we need the Spam folder and Spam menu item before spam filtering is implemented?

### ISSUE THREAD

**Issue by bilbof** [lavab/web#351]
Right now the user experience is the same for spam.
1. Get spam
2. Hit button to move spam to other folder ( :recycle: / :put_litter_in_its_place: or :no_entry_sign: )
3. Spam goes to another folder

There's no filter with spam assassin set up yet, maybe we should wait until it's ready before providing 'mark as spam' as an option? It implies we're ready to deal with it.

I know @andreis thinks we should leave it in. @flixi and @vLooz thoughts?

**Comment by vLooz** [comment]
Agreed@bilbof 
From a UX pov I'd definitely take out everything from the Interface, that is not working yet.

**Comment by bilbof** [comment]
:+1:

**Comment by flixi** [comment]
Spam filtering works!
![bildschirmfoto 2015-03-25 um 15 27 43](https://cloud.githubusercontent.com/assets/707993/6827313/0c19769e-d307-11e4-9fe6-caf1ebbeb26f.png)

**Comment by bilbof** [comment]
Awesome! :+1:

**Comment by bilbof** [comment]
Did you email Susan back? Sounds like a sweet deal.
