### ISSUE TITLE
mail-list-group's isLoadingSign stays visible after emails are loaded.

### ISSUE THREAD

**Issue by bilbof** [lavab/web#355]
![screen shot 2015-03-25 at 16 43 33](https://cloud.githubusercontent.com/assets/8124374/6828491/801a8bf8-d30e-11e4-98b9-438ca6e66634.png)

**Comment by let4be** [comment]
This supposed to be fixed in develop
where did you test? CD is currently broken and mail.lavaboom.co has some ancient version on it...

**Comment by flixi** [comment]
It's on .com

**Comment by let4be** [comment]
Fixed
