### ISSUE TITLE
cannot scroll to bottom of the mail view

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#356]
![image](https://cloud.githubusercontent.com/assets/1991125/6828899/17383a58-d34b-11e4-9e8a-d25a33c891ec.png)

check height of details pane - somethings wrong. probably need to set height of parent to 100%

**Comment by flixi** [comment]
Same here.

**Comment by piggyslasher** [comment]
sorry about this. i know the solution, just want to cleanup the code - there's too much unwanted html nesting. will fix by tomorrow/friday.
