### ISSUE TITLE
how should we show email threads that are partly encrypted?

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#357]
![image](https://cloud.githubusercontent.com/assets/1991125/6831789/826eb4ac-d35d-11e4-930b-84cef4d6c0f9.png)

currently we show lock / unlock combination. not sure how to proceed? should we just show an unlock icon?

**Comment by let4be** [comment]
Actually I think this is not even supported API wise - it was just somewhere in initial thoughts
now when we have at least one unsecured destination in the from/cc/bcc we send email as unencrypted

**Comment by flixi** [comment]
Yes, that means that in theory the whole email can be read if there is one receiver who cannot receive encrypted emails.

**Comment by piggyslasher** [comment]
so boss, we show two icons? or just the unlocked one.

**Comment by piggyslasher** [comment]
sorry, @flixi

**Comment by vLooz** [comment]
On the long run, we want the user to feel save once s/he sees the closed lock icon and a bit unsafe when there is open lock. Ideally the user would feel the need to invite the unsafe contacts to Lavaboom too ;-) 
2 locks would be confusing here. I'd go with the open lock!

**Comment by piggyslasher** [comment]
got it. and we're going with gray all the way ya? no more blue/orange? if yes, im gonna remove the code for that. :)

**Comment by vLooz** [comment]
blue = safe / locked icon
grey = unsafe / unlocked icon

**Comment by piggyslasher** [comment]
like so @vLooz ? if yes, i'm closing this. thanks.

**Comment by vLooz** [comment]
Awesome work @piggyslasher !!! :-) I like it a lot! 

3 little things left, than it's perfect! :-) 

1) Change the orange to the same grey, you gave the star 
2) Replace the date for the actual day with the time (e.g. 5:16 pm) and the last day with "yesterday" :-)
3) Is it possible, to replace the full name+email address (e.g. piggyslasher <piggyslasher@lavaboom.com>) with just the name (in this case just piggyshlasher)? This would look a lot cleaner.

**Comment by piggyslasher** [comment]
1 & 2 is already done @vLooz 
for 3) I'm assigning to @let4be

**Comment by let4be** [comment]
sure
