### ISSUE TITLE
style attachments as per @vlooz new mockup

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#358]
not yellow, but gray with a shadow.

**Comment by flixi** [comment]
https://github.com/lavab/web/issues/273

**Comment by vLooz** [comment]
This is the styleguide for how to position the attachment icons and regarding text @piggyslasher 

![358 attachment styleguide](https://cloud.githubusercontent.com/assets/11177812/6895422/5f5ad816-d6e0-11e4-8e49-c84c6a7d5372.png)

![attachmenticon_lock](https://cloud.githubusercontent.com/assets/11177812/6895423/6185ea40-d6e0-11e4-97ba-60f7b75c0f0d.png)

other attachments types Icons to come...

**Comment by flixi** [comment]
Status @piggyslasher ?

**Comment by piggyslasher** [comment]
i have a branch where I've been working on this. I will check with @let4be on how to use different classes for helping me style this. I have all the svg images ready.

**Comment by piggyslasher** [comment]
@let4be - im just finishing it up. Basically we don't need the extra modal anymore. currently you can put the decrypting status as a third line of text. But what i need is a data attribute like data-progress="30" for 30% and also a 'decrypting' class when the attachment is decrypting. Will let you know when its on develop.

**Comment by piggyslasher** [comment]
![webcrypto slow notification_5](https://cloud.githubusercontent.com/assets/11177812/6849805/95fd35de-d3d5-11e4-8746-0bba71c65bbc.png)
![webcrypto slow notification_4](https://cloud.githubusercontent.com/assets/11177812/6849951/51b42134-d3d6-11e4-9739-f88b00be8e23.png)

Decrypting progress design

**Comment by piggyslasher** [comment]
@let4be - here goes. please let me know if you have any questions.

1. here's the default display:
![image](https://cloud.githubusercontent.com/assets/1991125/7472269/600675d2-f363-11e4-851e-c61bb8111e3e.png)
2. When we add a `.decrypting` class to the .attachment, you will then see the progress indicator:
![image](https://cloud.githubusercontent.com/assets/1991125/7472284/884f7c32-f363-11e4-94c9-662776ac6042.png)
3. Now we can set the data-progress attribute (in _attachment_progress.jade) to the percentage of decryption.
The previous image is with `data-progress="1"`.
![image](https://cloud.githubusercontent.com/assets/1991125/7472309/c0485582-f363-11e4-8576-f9af688a7ca8.png)
The next image is with 40:
![image](https://cloud.githubusercontent.com/assets/1991125/7472317/d2c8df2e-f363-11e4-9285-0248dea65a42.png)
![image](https://cloud.githubusercontent.com/assets/1991125/7472321/db8bfdd0-f363-11e4-8485-7c567cbeabea.png)

Hope that makes sense. Assigning to you for now. Let's not do the 'click to decrypt' part yet. I will figure out a good way to do it.
