### ISSUE TITLE
please re-iterate the steps to setup the system locally

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#359]
i really wanna do this in one command. im sure @let4be can give me some ninja command here. this is actually for @vLooz to get this working on a fresh mac.

first lets clone the repo

```git clone https://github.com/lavab/web.git```

then lets checkout `develop`

```git checkout develop```

then lets install `gulp` globally

```npm install --global gulp```

then

```cd ~/web/ && npm install && gulp```

i hope these are the steps we need. @vLooz is getting the following error

```[18:35:07] Browserify compile error: Cannot find module 'mimelib' from '/Users/Felix/web/src/js/apps/AppLavaboom/factories' 
     in file /Users/Felix/web/src/js/apps/appLavaboom.js```

**Comment by let4be** [comment]
I just cloned the repo and made a fresh install - everything works as expected
Please make sure you installed **all** npm dependencies, there are lots of them and if it failed to install one due to some network error it can cause weird errors.

we have mimelib listed in package.json

**Comment by let4be** [comment]
Hm, it seems 
running "bower install" before "gulp" could help

**Comment by let4be** [comment]
For some weird reason it fails in part of tries without this(gulp has built-in bower install, but it seems to have some issues)
