### ISSUE TITLE
Style email replies

### ISSUE THREAD

**Issue by let4be** [lavab/web#360]
I've implemented 'reply to' email and 'reply to all', please see:

direct email:
https://github.com/lavab/web/blob/develop/src/blocks/inbox/directEmail.jade#L1-1
replied email:
https://github.com/lavab/web/blob/develop/src/blocks/inbox/repliedEmail.jade#L1-1

We need to style this accordingly:
- collapsable signature(if there was a signature attached)?
- replies collapsed by default?

@vLooz, @piggyslasher 

Currently there is no version where you can see this in-live, so it will be available as soon as deployment fixed.

**Comment by vLooz** [comment]
@let4be collapsed signature is a good idea. Will work on that. 
I'd suggest to have collapsed signatures only when replying though, otherwise users could get the feeling, their signature isn't there in the first place.

**Comment by piggyslasher** [comment]
just wrap replies in <blockquote> tag.

Next just add a <button>...</button> a button with three dots. i can then add the collapse function to the button and the blockquote that follows... plus we already have a nice styling for blockquotes.

**Comment by piggyslasher** [comment]
nice. i see your code @let4be - let me play around with this.

**Comment by flixi** [comment]
Not MVP though

**Comment by piggyslasher** [comment]
can we close this @let4be?
