### ISSUE TITLE
Unit tests for important crypto operations

### ISSUE THREAD

**Issue by let4be** [lavab/web#362]
Could be nice to have unit tests for:
- [ ] key generating
- [ ] encrypting
- [ ] decrypting

and make tests execute as a separate gulp task

**Comment by hyzhak** [comment]
@let4be are there any edge cases which you be covered by those tests?

**Comment by let4be** [comment]
just cover basic operations such as 
key generation(`generateKeys`),
 decryption(`decodeRaw`) and
 encryption(`encodeWithKeys`)

there are also key decryption authenticateByEmail, authenticate
and `changePassword`

which would be nice to have covered

**Comment by let4be** [comment]
Okay, closing this for now(merged into develop)
