### ISSUE TITLE
Enable <title> tag to display stuff at certain actions

### ISSUE THREAD

**Issue by flixi** [lavab/web#365]
Please insert a title="LAVAB_LOGOUT" or "LAVAB_COMPOSE" or similar to the appropriate functions. It's going to be way easier to determine then where to click to achieve the desired functionality.
Especially in the compose window, as the icons are not that clear. One may confuse the bcc and cc icon with the deliver icon. So please enable the title'S to display strings out of the toml file.

**Comment by piggyslasher** [comment]
we can use tooltips like we are using in the compose screen. show we just
use them?

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/6900333/68c5b94a-d738-11e4-9792-bd480dffd40b.png)

here's how its being done now.

**Comment by flixi** [comment]
Yes, please.

**Comment by piggyslasher** [comment]
this was fixed in a previous issue #320 

about your compose and logout request - are you referring to the left sidebar? i cant find buttons anywhere else that do this.

**Comment by piggyslasher** [comment]
you mean in the condensed layout when the left sidebar only has icons showing?

**Comment by flixi** [comment]
Yes. Condensed. It's unclear what does what

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/6924057/5bb823b6-d808-11e4-97e3-a7e69d814a99.png)

**Comment by flixi** [comment]
:thumbsup:
