### ISSUE TITLE
None of my folders have accurate numbers of emails.

### ISSUE THREAD

**Issue by bilbof** [lavab/web#366]
![screen shot 2015-03-30 at 15 02 35](https://cloud.githubusercontent.com/assets/8124374/6896643/d706f996-d6ed-11e4-87fb-d091cf45d3cb.png)
I have about 20 emails in my inbox in total.

**Comment by let4be** [comment]
If this repeats after you refresh the page(F5) this is API related problem, please report it to https://github.com/lavab/api/issues

**Comment by let4be** [comment]
Actually API should not send unread email count for Spam/Trash at all, as I stated it here:
https://github.com/lavab/api/issues/114

**Comment by bilbof** [comment]
This is definitely an API problem - I can't receive emails. Just tested.

**Comment by flixi** [comment]
Mailer had a DNS issue.

**Comment by bilbof** [comment]
Now no emails appear.

**Comment by bilbof** [comment]
![screen shot 2015-03-31 at 11 25 15](https://cloud.githubusercontent.com/assets/8124374/6915938/a468c644-d798-11e4-9703-34cf6e3991d6.png)

**Comment by let4be** [comment]
Not an issue, backend had temporary problems afaik
