### ISSUE TITLE
forward/reply/reply-all touch up

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#370]
now it looks like this:

![image](https://cloud.githubusercontent.com/assets/1991125/6904782/f94dacbc-d755-11e4-87ff-c4eb93edba20.png)

needs to be
![image](https://cloud.githubusercontent.com/assets/11177812/6845771/301a9314-d3b8-11e4-93ad-a80799beab30.png)

**Comment by piggyslasher** [comment]
@vLooz - i love the new design, however, a new user is left wondering - how the heck can i reply. I think this should just be shown always. Its light and doesn't congest the design.

also i think we should put back the three reply, reply all, forward icons back on the top action bar.

1. its always in the same place - people don't need to scroll down to the end of the email
2. this would just reply, reply-all to the most recent email received (which will of course have all the previous correspondence at the bottom of it).

@flixi @let4be

**Comment by flixi** [comment]
Yes. I Like it.

**Comment by vLooz** [comment]
You are right, that let the buttons disappear is probably confusing for some users @piggyslasher 
I see two options here:

1) We place it back into the main action bar on top, like Vik suggested
2) We place it as a half transparent overlay at the bottom of the correspondence, independent of mail positions. Like in the Mailbox Client :-)

![bildschirmfoto 2015-04-01 um 12 13 00](https://cloud.githubusercontent.com/assets/11177812/6939144/d2915b22-d869-11e4-85a4-cd55dbe9d841.png)

**Comment by piggyslasher** [comment]
for example this email - i cant see the buttons till i scroll down. And on a touchpad mac (without a mouse attached, you don't see a scrollbar till you actually scroll).

![image](https://cloud.githubusercontent.com/assets/1991125/7264587/981c891a-e8bf-11e4-8078-13e84b8ba14e.png)

I think we should do both options :) have it on top of the page in the action bar as well so we don't have to scroll down. And also have it at the end of each mail to reply to that particular email (maybe you have a different set of recipients in one of them and you only want to reply to _them_ - very necessary in corporate & social emailing). Then again maybe I'm just being traditional. It all depends on user feedback. Perhaps @mlooz can give his views.

after scrolling down I have this, which is also quite welcome.
![image](https://cloud.githubusercontent.com/assets/1991125/7264629/1862e826-e8c0-11e4-9dff-e4d29bf28aa9.png)

Gmail provides this feature by having a text box in each email and also a main forward/reply/reply all on top _and_ the main text box at the bottom.

**Comment by piggyslasher** [comment]
assigning back to @vLooz as this is already in develop.

**Comment by vLooz** [comment]
From my POV, to see the reply buttons all the time has priority 1. To be able to reply only to a specific mail, and their recipients, has priority 2.

So we could do something Mailbox does and show an Overly reply button field hovering over the mail thread as soon as it gets to long too be fully shown in the preview window. The user then can reply instantly to the whole thread without scrolling.
When she wants to reply to a specific mail, she has to scroll until she sees the reply buttons at the end of this mail.
![bildschirmfoto 2015-04-22 um 11 47 21 kopie](https://cloud.githubusercontent.com/assets/11177812/7271794/3d865b1c-e8e6-11e4-9c0e-f5918f8c6aac.png)

**Comment by piggyslasher** [comment]
okay that looks amazing. i think thats the best solution that covers all aspects. let me know if I can proceed.

**Comment by vLooz** [comment]
Here you go @piggyslasher 
The Reply buttons hovers 16px above the window buttom.
box shadow: 0px 2px 5px 0px rgba(0,0,0,0.25) #000000

![2015-04-22_move 3 buttons into mail-03](https://cloud.githubusercontent.com/assets/11177812/7272586/46720e32-e8ec-11e4-89d7-d8cac6b7ec8c.png)

**Comment by mlooz** [comment]
It appears I'm late to the party. Still, my views:
I  consider emails, not threads, to be the fundamental unit of emailing. An option to only forward one email instead of an entire thread is important to me. Since almost everyone quotes the entire previous communication when replying, it is within one email anyway and the thread view is redundant.
Thus, I would really like to have individual forward/reply/reply-to-all buttons for emails.
I would have preferred the thread-global button set in the action bar for consistency with the rest of the interface, but a hovering button set is also fine. :-)

**Comment by vLooz** [comment]
You got a point there @mlooz. 
I'd suggest to just add the delete icon as a fourth icon to the reply/forward box in the bottom right corner of every single mail.

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/7290415/d9a05528-e9b0-11e4-9556-84dfca262968.png)

here's the first draft.

**Comment by vLooz** [comment]
Looking good@piggyshlasher! We're getting close :-)

As we've also discussed in https://github.com/lavab/web/issues/502#issuecomment-95485365 I think we need a delete icon in the icon-group at the lower-right of every mail. 
Is the "delete a single-mail out of a thread" function implemented @let4be? 

If yes, please add the delete icon to this group @piggyslasher. 
See design draft:

![bildschirmfoto 2015-04-23 um 11 15 17](https://cloud.githubusercontent.com/assets/11177812/7294045/3a39de38-e9aa-11e4-802d-eff1e86599a3.png)

**Comment by piggyslasher** [comment]
If it is supported by the API its very fast for me to add the delete icon. @pzduniak?

**Comment by pzduniak** [comment]
https://github.com/lavab/api/blob/master/setup/setup.go#L513

**Comment by piggyslasher** [comment]
please check develop

**Comment by vLooz** [comment]
I would really like the delete icon like stated before. Is there any technical issue preventing this from being implemented @pzduniak @let4be 

Right now the lower middle button-row (whole thread) doesn't work. Is there a reason for that?

**Comment by piggyslasher** [comment]
apologies. shouldnt have closed this. the buttons werent mapped to their functions yet.
@vLooz yes - there is a reason for both.

1) i've now added the delete button, but I need @let4be or Eugene to add the function into the model.
2) same problem as 1) the reply all and forward function has not been mapped to a per email basis in the current system.

i have added a mock function to just show an alert saying 'not implemented'. assigning to @let4be 
this could also be a nice task for eugene to start with. @andreis?

**Comment by piggyslasher** [comment]
@hyzhak - what do you think of this?
