### ISSUE TITLE
need black/white print-friendly logo

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#371]
try pressing ctrl+p on an email and you'll see a very unprintable lavaboom logo on top of the first page.

i checked trello but cant find this version of the logo.

**Comment by vLooz** [comment]
This is probably more printer-friendly @piggyslasher 

![2015-03-27_logo_onwhite kopie](https://cloud.githubusercontent.com/assets/11177812/6914999/a99b4fea-d790-11e4-9895-632a55db1544.png)

**Comment by vLooz** [comment]
![2015-03-31_lavaboomlogo_bw-04](https://cloud.githubusercontent.com/assets/11177812/6915058/44b183e6-d791-11e4-87e8-42650d948766.png)

**Comment by piggyslasher** [comment]
@vLooz can i please have an svg of the gray one?

**Comment by vLooz** [comment]
sure. will send it on slack
