### ISSUE TITLE
left panel fixes

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#373]
I've updated the heights/paddings to what you requested @vLooz 

![image](https://cloud.githubusercontent.com/assets/1991125/6905058/ee4ecc36-d757-11e4-99b1-a755ea57b881.png)

what do you think?

please add more comments here so i can tweak the measurements

**Comment by vLooz** [comment]
Looking good @piggyslasher!
The icons and the Logo aren't perfectly center aligned though. Can you move the icons a tiny bit to the right? Thx!
![ee4ecc36-d757-11e4-99b1-a755ea57b881](https://cloud.githubusercontent.com/assets/11177812/6915113/b1a3282e-d791-11e4-8ac9-74575980afb7.png)

**Comment by piggyslasher** [comment]
i think i got it right. please check on retina. on non-retina its aligned. if its not i need to edit the svg and move it slightly.
