### ISSUE TITLE
The blue read icon in the email

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#380]
Currently when we receive a new email, we arent redirected to it - so in the list it stays unread - there's a blue icon next to it (when mail starts working again i can give you a screenshot of this. however when you actually click on the email, the email status becomes unread before it is displayed.

![image](https://cloud.githubusercontent.com/assets/11177812/6830817/ae9dd864-d31c-11e4-98ec-36ec1506dc78.png)

therefore the blue icon on the left never really has the chance to be shown (because the email is already marked as read before it starts decrypting). how do we proceed? just have a blank area on the left?

now, i didnt test this but if *im on an active thread, i.e. a correspondence with @let4be - what we can do is show the unread icon _if_ the user is on the thread with the new inbound email? i just checked it - if im on a current thread and the recipient replied, it doesnt auto update at the top.*

**Comment by piggyslasher** [comment]
i checked the factory and there's no read function in the email.

**Comment by vLooz** [comment]
hmmm... I think @piggyslasher is right here. Just get rid of the blue icon then!

**Comment by piggyslasher** [comment]
adding a wont fix label for now. if you have other thoughts, let me know @let4be

**Comment by let4be** [comment]
so @piggyslasher are you saying that email becomes _read_ before actually being shown to the user? hm... I will check

**Comment by let4be** [comment]
related: https://github.com/lavab/web/issues/400
