### ISSUE TITLE
General: Please move Server Infos to the left bottom

### ISSUE THREAD

**Issue by vLooz** [lavab/web#384]
![bildschirmfoto 2015-04-01 um 18 24 32](https://cloud.githubusercontent.com/assets/11177812/6945808/9ab387e2-d89c-11e4-9a1b-d0a873367bce.png)

**Comment by piggyslasher** [comment]
@let4be - what should we do here because its following the notifications system. anyway you can separate the server info? assigning to you for now.

**Comment by piggyslasher** [comment]
@vLooz also server info is just for development build - not production (.com build).

**Comment by vLooz** [comment]
Ah, ok. So it will not be visible in the official version? @piggyslasher

**Comment by piggyslasher** [comment]
no it won't. but i'm re-assigning this to myself because i can use it to style general notifications.

**Comment by let4be** [comment]
server info will be both on dev and prod
Just in dev it's Darth Vader ;)

**Comment by piggyslasher** [comment]
do we need this?

**Comment by flixi** [comment]
Yes, we do, as it proves to the User that it's actually our js they are getting.
Make sure this doesn't get displayed during login though, please.
![bildschirmfoto 2015-04-06 um 17 58 59](https://cloud.githubusercontent.com/assets/707993/7010417/5036cd7e-dca1-11e4-8b55-daa2b41390da.png)

**Comment by piggyslasher** [comment]
its been removed from login in the latest dev build. for starters, if the user wants to know if he's using our js, it would be good to show it early before any credentials are passed. Ideally in the login screen, not the screen you pasted above, but the one with the username/passphrase. maybe a small message at the bottom.

**Comment by flixi** [comment]
Yes, but make sure it doesn't shift the thing to the right.

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/7257341/9afd7b0e-e887-11e4-9ba5-ec072f7ec44a.png)
