### ISSUE TITLE
General: Double check all instances Icons the same size (e.g. TrashCan Icon)

### ISSUE THREAD

**Issue by vLooz** [lavab/web#385]
![bildschirmfoto 2015-04-01 um 18 27 44](https://cloud.githubusercontent.com/assets/11177812/6945851/f13a5104-d89c-11e4-9c4e-656ce35f71b9.png)

**Comment by piggyslasher** [comment]
we changed the entire icon system and unified their sizes to 22x22, 44x44 etc. this issue was fixed in the process.
