### ISSUE TITLE
Inbox: Get rid of the „Sort by…“ dropdown. Newest Mails are on top in MVP 

### ISSUE THREAD

**Issue by vLooz** [lavab/web#388]
![bildschirmfoto 2015-04-01 um 18 19 42](https://cloud.githubusercontent.com/assets/11177812/6946135/89034f44-d89e-11e4-8ec7-c8a2338c5025.png)

**Comment by piggyslasher** [comment]
commented it out @let4be 
fixed (hidden) for now @vLooz
