### ISSUE TITLE
Compose: Please no auto-replace in any other field then the recipients! 

### ISSUE THREAD

**Issue by vLooz** [lavab/web#389]
I wrote a mail with the About "Test 2" today.
When composing another mail, and typing "test" in the about field, it would be auto-replaced with "Test 2". 

Please get rid of any auto-replace / auto-correct features in any of the fields, apart of the recipient fields.

**Comment by piggyslasher** [comment]
@vLooz - is this for the subject field?

**Comment by vLooz** [comment]
Yes, I have this problem when typing the subjects @piggyslasher

**Comment by piggyslasher** [comment]
fixed. also - i will mark issues with the 'ready' when i complete them - but they're not in the main development branch yet. when i _close_ an issue, that means you can sync your code (using the github app or the command i gave you), and then re-run your local copy by using the command i gave you. in fact, you can just use the one command without opening the github app.

**Comment by piggyslasher** [comment]
please check this again :) on my side i dont see any autocomplete results. re-open if its not fixed. thanks.
