### ISSUE TITLE
Compose: Make Font in About field a bit thicker

### ISSUE THREAD

**Issue by vLooz** [lavab/web#390]
It's a bit too thin to be readable (at least on retine)

![bildschirmfoto 2015-04-01 um 17 12 03 kopie](https://cloud.githubusercontent.com/assets/11177812/6946266/58532a94-d89f-11e4-9345-8e51902c266e.png)

**Comment by piggyslasher** [comment]
will check this. i need to update the code in the compose field for the new font weight system.
