### ISSUE TITLE
Compose: Get rid of the „Add CC and BBC“ button in header

### ISSUE THREAD

**Issue by vLooz** [lavab/web#391]
Get rid of the „Add CC and BBC“ button in header

![bildschirmfoto 2015-04-01 um 17 12 03 kopie 2](https://cloud.githubusercontent.com/assets/11177812/6946440/8a18998c-d8a0-11e4-8f42-d9f2eee15691.png)

Instead create 2 separate buttons for at the right end of the recipient field. See design mocks below:

![bildschirmfoto 2015-04-01 um 18 49 24](https://cloud.githubusercontent.com/assets/11177812/6946443/8f518508-d8a0-11e4-8b40-71e8194e8457.jpg)

When there is no CC or BCC field selected, it looks like on the left. 
Once you hit the "CC-button", the button itself disappears and a new field below recipient comes up with an "X" at the right end. 
Once you hit "BCC", same happens, just with a BCC field. 
When you want to get rid of the CC and BCC fields again, you hit the "X" at the end of the fields.

**Comment by piggyslasher** [comment]
an early version of this is on develop. just created two buttons and basic styling. rest i will do in 2.1

for now the 'x' button is still a _clear all_ field rather than a hide CC or BCC function.

**Comment by piggyslasher** [comment]
done. on develop.
