### ISSUE TITLE
Contacts: Double check "Sort by name" functionality

### ISSUE THREAD

**Issue by vLooz** [lavab/web#392]
When contacts are sorted by last name, the order of the letters ist still by first name.

![bildschirmfoto 2015-04-01 um 18 55 24](https://cloud.githubusercontent.com/assets/11177812/6946471/cc0fb8de-d8a0-11e4-93b4-6d65a962ca39.png)

**Comment by piggyslasher** [comment]
assigned to @let4be

**Comment by let4be** [comment]
@vLooz where does this happen? I can't reproduce this locally on develop branch

**Comment by let4be** [comment]
and this should not happen at all, as there is sorting implemented on letters
https://github.com/lavab/web/blob/develop/src/js/apps/AppLavaboom/controllers/ctrlContactList.js#L94-94

**Comment by vLooz** [comment]
This happened on Viks local branch the date I issued this. If thats not the case anymore, close the issue :-)

**Comment by let4be** [comment]
I can't reproduce it on develop, probably his local branch was outdated
If this appears again - reopen
