### ISSUE TITLE
Contacts: Double check Lock Icons functionality

### ISSUE THREAD

**Issue by vLooz** [lavab/web#393]
Lock icon in contact list is blue, even if there is no public key for any of the contacts email addresses.

![bildschirmfoto 2015-04-01 um 18 57 35](https://cloud.githubusercontent.com/assets/11177812/6946519/348ffe5a-d8a1-11e4-9d6d-4fc28526726a.png)

**Comment by piggyslasher** [comment]
re-assigning to @let4be
