### ISSUE TITLE
Settings: Change Chapter (general, profile, keys…) height to 88px high

### ISSUE THREAD

**Issue by vLooz** [lavab/web#395]
![bildschirmfoto 2015-04-01 um 17 11 27 kopie](https://cloud.githubusercontent.com/assets/11177812/6946589/b7081c96-d8a1-11e4-99b2-c29e4987de16.png)

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/6967383/7932f846-d991-11e4-971a-0be8f86070fe.png)

**Comment by vLooz** [comment]
Much better! :-) thx! 
Still there is a little irregularity around the settings button. If you have time, you might wanna double check, if all the folder areas (Inbox, Sent, Starred...) have 44px as a height. Suuuper low priority though :-)
![7932f846-d991-11e4-971a-0be8f86070fe](https://cloud.githubusercontent.com/assets/11177812/6967553/51bb0366-d960-11e4-9bb7-8600abed116b.png)

**Comment by piggyslasher** [comment]
lol. i noticed it and am trying to check which rogue element is causing this madness. should be a quick fix.

**Comment by piggyslasher** [comment]
lol - it was the gray border on the left taking up a pixel.

![image](https://cloud.githubusercontent.com/assets/1991125/6967955/9b2a1548-d995-11e4-92d1-6a27a4cbd387.png)

**Comment by piggyslasher** [comment]
erm you think the last item should be have the border _inside_ or is this fine? im moving on to other tasks now. will gat back to this based on what you say.

**Comment by vLooz** [comment]
now it's looking good. As long as the borders are aligned, I'm happy :) Thx man!
