### ISSUE TITLE
Sanitizer gets crazy and wipes most of the styling from emails

### ISSUE THREAD

**Issue by let4be** [lavab/web#406]
I'm not sure yet what's going on but formatting of forwarded emails which look nice on my gmail is screwed
Going to check this and how it relates to security

**Comment by let4be** [comment]
https://github.com/angular/angular.js/issues/10406

**Comment by let4be** [comment]
http://stackoverflow.com/questions/10421168/security-risk-xss-with-style-attributes

**Comment by let4be** [comment]
Basically this is considered a security risk, we need to decide how far we want to go in email's styling

**Comment by flixi** [comment]
Opinios @pzduniak @piggyslasher ?

**Comment by let4be** [comment]
As an experiment I'm going to fully preserve styles inside html tags, and we will see how it goes regarding display and security

**Comment by let4be** [comment]
Also see https://github.com/lavab/web/issues/432

**Comment by let4be** [comment]
Okay this is more or less settled for now - we're going to support styled(with warning and confirmation) emails, current styling-preserve implementation turned out to work pretty well afaik
