### ISSUE TITLE
Styling for notifications

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#410]
![image](https://cloud.githubusercontent.com/assets/11177812/6848710/24da10f8-d3cf-11e4-815c-5c45f05fee56.png)

**Comment by piggyslasher** [comment]
there is initial styling for notifications now. this is above the emails. @vLooz  i don't think we can do 3) because it covers the action bar. I think we should just do 2) instead of 3). check the initial notification styling when i push the changes later tonight.

**Comment by vLooz** [comment]
See #384

**Comment by piggyslasher** [comment]
@let4be how about this for more control over modals? like yes/no. it even prevents closing if necessary.

http://dwmkerr.github.io/angular-modal-service/

**Comment by vLooz** [comment]
Do you need a separate styleguide for this or can you use the existing SignUp structure @piggyslasher?

**Comment by piggyslasher** [comment]
just give me improvements when i complete the initial coding @vLooz .

for now we have no modal notifications yet.

**Comment by vLooz** [comment]
Alright. Let me know when you finished coding

**Comment by flixi** [comment]
Is that done yet?

**Comment by piggyslasher** [comment]
we have styling for the notifications above the email area. there arent any other notifications that we have at the moment.

we also have self-dismissing notifications that dissappear after 3 seconds.

**Comment by flixi** [comment]
Is the ability to implement such notifications there though? So theoretically anyone could actually use these to style his or her own notifications?

**Comment by piggyslasher** [comment]
well. things like 'contact saved' is  self dismissing notification because its a pain to keep clicking 'ok' in those situations. I'm not sure if anyone can use these notifications. If i made a chrome plugin or something then yes i can use this same styling. or if i had access to the javascript.

the notifications is all decided by one central notification service. if there is a timeout in the notification (lets say 3seconds, then the notification is displayed for 3 seconds) or else (ie, timeout is 0), there's an OK button for dismissing it.

**Comment by flixi** [comment]
Nope, I'm talking about implementation of the notifications, so that a developer would be able to call upon a class with a random notification and thus it would create a nice notification?

**Comment by piggyslasher** [comment]
yes. he just needs to call the notification service and set the text and the timeout if any. he can call it from anywhere in the application.

**Comment by flixi** [comment]
we can close this then...

**Comment by piggyslasher** [comment]
problem is that __this__ is also a notification. we haven't completed that yet.

![image](https://cloud.githubusercontent.com/assets/1991125/7162169/b62e15da-e3c5-11e4-8ede-cdd9f16c6428.png)

from #462. Maybe we can close this and only have that open. But this issue is a general issue has about 2-3 notification styling so I thought I'd keep it open.

**Comment by flixi** [comment]
Did you implement a simple way to call the notifications though?
As you said I should be able to create a notification now, add some text, two buttons with text then add the class of popup notification and ultimately receive a notification that is styled like the one above.

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/7200762/923be8c8-e532-11e4-9b53-ed99a024e323.png)

@let4be for now we can just have this as a normal notification on the email area right? no need for a dialog for this just yet. at least we show the user a notification with no timeout.

**Comment by flixi** [comment]
Yes, this looks really great!

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/7248838/9022b9d6-e848-11e4-8228-2f29bd224239.png)
marking this as ready - @vLooz will close this in a few minutes so you can check. to see an example, try deleting a contact.

**Comment by piggyslasher** [comment]
closing this for now. its on develop. will create a new issue later with just the remaining notification styling. also when @let4be gets back I'm just going to ask him how I can customize the template inside the dialog so we can have icons, etc.
