### ISSUE TITLE
username julia and verification token don't match

### ISSUE THREAD

**Issue by flixi** [lavab/web#422]
![bildschirmfoto 2015-04-07 um 16 46 59](https://cloud.githubusercontent.com/assets/707993/7025769/138a0b7a-dd46-11e4-94ea-1e374503f04b.png)
https://gist.github.com/flixi/64949585d59d182909c1

**Comment by piggyslasher** [comment]
im also having this problem with 'piggyslasher'

**Comment by piggyslasher** [comment]
@pzduniak

**Comment by pzduniak** [comment]
Fixed
