### ISSUE TITLE
Display only from address

### ISSUE THREAD

**Issue by flixi** [lavab/web#424]
![bildschirmfoto 2015-04-08 um 16 32 26](https://cloud.githubusercontent.com/assets/707993/7047464/fdf5b120-de0c-11e4-8b26-e11fec6d4dd9.png)
Make sure the from email address is the one that gets pulled if you hit the reply button.

**Comment by pzduniak** [comment]
I could easily remove it from members, but I'd rather have it done in the frontend, so that we can easily add multi-address feature later. You might be interested in `GET /addresses`.

**Comment by let4be** [comment]
I will just take required addresses from the thread's manifest

**Comment by pzduniak** [comment]
That won't work, as thread manifest = manifest of the first email.

2015-04-09 8:51 GMT+02:00 let4be <notifications@github.com>:

> I will just take required addresses from the thread's manifest
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lavab/web/issues/424#issuecomment-91129938>.
>



-- 
Piotr Zduniak
piotr@zduniak.net
http://zduniak.net

**Comment by let4be** [comment]
riight, email's manifest

**Comment by let4be** [comment]
so
reply to = email's manifest [to]
reply to all = members without self
