### ISSUE TITLE
Sent: Encrypted Mail preview is not shown 

### ISSUE THREAD

**Issue by vLooz** [lavab/web#431]
When I want to read a mail I've sent encrypted, the mail preview is blank. 
This does not happen with unencrypted mails.

![bildschirmfoto 2015-04-09 um 11 14 04](https://cloud.githubusercontent.com/assets/11177812/7063779/c5796e70-dea9-11e4-9d0b-40ec67065dfe.png)

**Comment by let4be** [comment]
Most likely mailer/api related, @pzduniak ?

**Comment by flixi** [comment]
https://github.com/lavab/web/issues/309

**Comment by pzduniak** [comment]
API doesn't do anything with the encrypted emails - it just saves them.

2015-04-11 12:44 GMT+02:00 Felix Mueller-Irion <notifications@github.com>:

> #309 <https://github.com/lavab/web/issues/309>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lavab/web/issues/431#issuecomment-91825122>.
>



-- 
Piotr Zduniak
piotr@zduniak.net
http://zduniak.net

**Comment by let4be** [comment]
Confirmed to be API/Mailer related the same old bug
I've checked it a week before and it was fixed, looks like it pops up again
redirecting this to: https://github.com/lavab/api/issues/107
