### ISSUE TITLE
Reply Mail: Recipient Address is shown in a weird way

### ISSUE THREAD

**Issue by vLooz** [lavab/web#443]
I send a Mail from Lavaboom to my Gmail Address. I replied from Gmail to Lavaboom. All fine. When I wanted to re-reply from Lavaboom back to Gmail, the recipient field was showing weird data and was far too long for the compose/reply window.

![bildschirmfoto 2015-04-09 um 19 15 59](https://cloud.githubusercontent.com/assets/11177812/7072492/29f102da-deed-11e4-8b22-547f9f6ee13d.png)

**Comment by let4be** [comment]
Are you sure this appears on the latest develop branch, because I fixed the same issue in
https://github.com/lavab/web/commit/ef74ad3877cc977c3b617120502ae597bc286412

**Comment by vLooz** [comment]
It appeared yestrday on the branch, I synced via github from Vik.

**Comment by flixi** [comment]
Is this a prod bug?

**Comment by flixi** [comment]
@vLooz ?

**Comment by vLooz** [comment]
Couldn't reproduce it anymore. Looks like the guys have solved this.
