### ISSUE TITLE
Settings-keys new layout isues

### ISSUE THREAD

**Issue by let4be** [lavab/web#446]
![image](https://cloud.githubusercontent.com/assets/4147061/7083365/7a84df92-df69-11e4-8f10-dda2cebc99c3.png)

1. Send public key
1.a. fix the icon
1.b. what is the purpose of this button? (I have no idea)

~~2. Clicking on 
![image](https://cloud.githubusercontent.com/assets/4147061/7083375/9f575bba-df69-11e4-8856-9aaf43b37a04.png)
has no effect in collapse/unfold - need to fix~~
This seems to be working.

~~3. Algorithm field is empty~~

**Comment by vLooz** [comment]
Friendly reminder that I'd like it to look like this ;-)
![bildschirmfoto 2015-04-10 um 15 57 54](https://cloud.githubusercontent.com/assets/11177812/7089197/67523c90-df9a-11e4-81d1-3b4704984368.png)

**Comment by flixi** [comment]
![bildschirmfoto 2015-04-13 um 11 28 11](https://cloud.githubusercontent.com/assets/707993/7125335/5076acd4-e230-11e4-9f34-b9a61944a419.png)

**Comment by flixi** [comment]
https://gist.github.com/flixi/0d1f3581d244ad4224d6

**Comment by vLooz** [comment]
I have the same gibberish. 
This styleguide is out for almost a month. If they are any problems or doubts preventing you from implementing the key section exactly(!) like this, please let me know. If not, please adjust the UI to my styleguide asap! @piggyslasher :-)
![2015-03-18_settings_keys_dialogs](https://cloud.githubusercontent.com/assets/11177812/7132543/9396fb18-e28a-11e4-9cc4-45b3bba3ff91.png)

**Comment by piggyslasher** [comment]
this is how it looks on my side.

![image](https://cloud.githubusercontent.com/assets/1991125/7150491/2f3f671c-e34e-11e4-9502-01ad201c7d4a.png)

I'm not sure why you're seeing gibberish. @andreis - can you make sure @vLooz is on the latest?

Theres more refinements to do but yes. the collapse/expand system works.

**Comment by piggyslasher** [comment]
i've tried all known browsers on Mac and cannot replicate this issue. are you guys using a local copy? or the develop branch? or .com or .co?

here's the latest:
![image](https://cloud.githubusercontent.com/assets/1991125/7151633/db990cdc-e35f-11e4-8da5-37c5cdef6fa7.png)

@let4be have we decided on the 'decrypted' field? To be honest I'm only following @vLooz's layouts and the decryption system was not there in the latest mockups. Can you please discuss and let me know if it is necessary?

Also - regarding the expiry date. Do we have this?

**Comment by piggyslasher** [comment]
>As far as I see it, your orange and blue buttons below the key sections are not necessary at all, because all the functions are covered by the options in the styleguide. Please correct me if I am wrong here.

I never added these buttons. The were added by @let4be 

Now we have the + and - buttons but you only refer to them for pro users. So I'm really not sure what to do here.

What I've done so far is this. I've styled whatever I can to include all the functionality that you've added to your final mockup.

here's what the latest work looks like:

![image](https://cloud.githubusercontent.com/assets/1991125/7151896/06db65c6-e364-11e4-89d7-59b749bc9382.png)

**Comment by piggyslasher** [comment]
pull request #478 closed.

**Comment by mlooz** [comment]
Commenting here since the other one was a duplicate.
I'm working on the .com version with Firefox on Ubuntu 14.04.

Setting style="overflow: hidden" works!

Toggling the key information now changes the style from "overflow: hidden; height: 0px;" to "style="overflow: hidden; height: auto;" and back, both looking as they should. :-)

**Comment by piggyslasher** [comment]
i believe youre seeing an older version on .com - there's tones of small fixes I did over the weekend. why do you pull fresh from git? 

you wont have this issue if you use the latest version.

https://github.com/lavab/web has the instructions on how to setup. It is actually _very_ easy.

```git clone https://github.com/lavab/web.git && cd ~/web/ && git checkout develop && npm install -g gulp && npm install && gulp```

**Comment by mlooz** [comment]
I had to strongarm gulp into accepting an older node.js version, but now it works and looks right. Thanks! :-)

**Comment by vLooz** [comment]
I did indeed looked at the .com version instead of your local branch @piggyslasher. Apologies for giving unfair feedback because of this! 
Even though the .com version is what beta testers see and test right now. I doesn't make much sense to let them give feedback to a version, that is not up to date, right? I've just talked to FMI about this and I think we need to get the deployment to .com quicker or at least more structured. Otherwise I see people commenting on old versions happening over and over again.

**Comment by piggyslasher** [comment]
I know. Last time the mail.lavaboom.co version was up to date with my changes on the development branch. Now its not automatic anymore. I don't really want to update the .com myself as @let4be should do that. He's more well versed with whats working underneath and whats not.

@pzduniak - any idea about when .co will reflect develop?

**Comment by piggyslasher** [comment]
- [ ] add expiry date to expanded view.
  - [ ] add encryption strength to expanded view.

**Comment by piggyslasher** [comment]
assigning to @let4be for those extra fields.
