### ISSUE TITLE
Why is a Mail from gmail shown as encrypted?

### ISSUE THREAD

**Issue by vLooz** [lavab/web#449]
I sent a mail from my gmail account to my lavaboom account. The mail appeared as encrypted in my inbox, which obviously can't be true.

![bildschirmfoto 2015-04-13 um 11 13 20](https://cloud.githubusercontent.com/assets/11177812/7112882/9d978310-e1ce-11e4-8584-ccf9bf748fe7.png)

**Comment by let4be** [comment]
Blame the API and thread.secure field, the web is just display what API has sent

**Comment by let4be** [comment]
To be totally sure in this I need logs... or at least thread ID so @pzduniak may check this too in the database

Could you please provide the full address of this page with opened thread @vLooz ?
It should contain the thread ID

**Comment by vLooz** [comment]
How do I find out the thread ID?

**Comment by let4be** [comment]
I meant this
![image](https://cloud.githubusercontent.com/assets/4147061/7113638/832989a0-e1de-11e4-87aa-bb3b1e076eeb.png)

**Comment by vLooz** [comment]
https://mail.lavaboom.com/label/Inbox?threadId=R9s5Qq8ezabuHNBEnFfS

**Comment by let4be** [comment]
@pzduniak could you pls check the thread.secure field for this thread?

**Comment by let4be** [comment]
Another explanation would be that you have correct imported public key for felix.vlooz@gmail.com
which is possible

**Comment by vLooz** [comment]
Am I the only one having this issue?

**Comment by let4be** [comment]
I couldn't reproduce this, let's wait for @pzduniak

**Comment by flixi** [comment]
Nope, it seems to be a very common issue.
https://github.com/lavab/api/issues/124

**Comment by let4be** [comment]
This maybe the cause as well, I'm not sure what is the status of lavab/api#124
Personally I havent' encountered it for a while

**Comment by flixi** [comment]
Every Email that comes in gets classified as encrypted at first.
