### ISSUE TITLE
Misc: Only show "served by <server>" notification once per day

### ISSUE THREAD

**Issue by andreis** [lavab/web#450]
Let's limit the "served by cow" notifications to one per day. Implementation suggestion:

* add fields to AppData; e.g. `app_data.notif.served_by.interval` (seconds) and `app_data.notif.served_by.last` (Unix time)
* on login:
```
if time.now().seconds() - served_by.last > served_by.interval then
  served_by.last = time.now().seconds()
  display notification
```

@Im4JAR is a non-tech member of our team that has been learning JS and would like to help. I was thinking we could give him this as a small introductory task. Whatcha think @let4be?

**Comment by andreis** [comment]
Correction: the display interval might have to be in `account.setting` instead of `app_data`. Or just a preference "show who is serving your data" and standardize on 1 day intervals.

**Comment by let4be** [comment]
what is the point of this @andreis ? I don't understand, I think this just will bring confusion...
@flixi ?

**Comment by andreis** [comment]
Not sure what's unclear. I'm suggesting we only show the "served by" stuff once per day. The settings part (to disable "served by" notifications) is completely optional. Setting the interval by the user sounds pretty silly in hindsight, yes.

**Comment by let4be** [comment]
we probably should just move this notification is the less annoying place - this is what I suggest

**Comment by let4be** [comment]
![image](https://cloud.githubusercontent.com/assets/4147061/7114360/2a386dc8-e1e5-11e4-833a-b29da88e2fc6.png)
will this work for us?

**Comment by andreis** [comment]
Yeah, that was how it was intended in the first place. That however means no JS task for @Im4JAR  :(

**Comment by let4be** [comment]
There is a
https://github.com/lavab/web/issues/362
;)
