### ISSUE TITLE
Translation files don't seem to load properly

### ISSUE THREAD

**Issue by andreis** [lavab/web#451]
`You server today is cow, happy mailing..SERVED_BY_TEXT`

![screen shot 2015-04-13 at 11 37 15](https://cloud.githubusercontent.com/assets/1249760/7113190/936f27d2-e1d1-11e4-8c74-d48741d3c120.png)

https://gist.github.com/andreis/8d0c852bdbe8d47f7b01

**Comment by let4be** [comment]
what... how did this ever happen? :|
