### ISSUE TITLE
Feature request: Display `web` version above "Logout"

### ISSUE THREAD

**Issue by andreis** [lavab/web#453]
This will help with caching issues, and more. Since we're using semver, just have a metadata/manifest file that can be accessed by angular, and we update it manually together with `CHANGELOG` when bumping versions.

**Comment by andreis** [comment]
Ideally pre-`1.0.0` we'd have it right on the screen, somewhere on the left panel (useful for screenshots), and after 1.0 we can move it to Settings.

**Comment by let4be** [comment]
![image](https://cloud.githubusercontent.com/assets/4147061/7114360/2a386dc8-e1e5-11e4-833a-b29da88e2fc6.png)
will this work for us?

**Comment by andreis** [comment]
Yes. How did you do it btw? @let4be

**Comment by let4be** [comment]
https://github.com/lavab/web/blob/develop/manifest.json
But manifest.json used to serve a different purpose before so it was in .gitignore ^^
fixed

**Comment by let4be** [comment]
I guess I will need to write some script to do a fast
bump manifest.json, change change log, add tag, commit all this and then push into develop

probably a separate gulp task 'deploy'

**Comment by andreis** [comment]
I'm pretty sure you're looking forward to rewriting all of Lavaboom as gulp tasks. :smile

**Comment by let4be** [comment]
I just think our gulp file isn't big and complex enough ;) yet...

**Comment by flixi** [comment]
It'S not on 'prod' yet though?

**Comment by flixi** [comment]
@let4be

**Comment by let4be** [comment]
should be on master branch from yesterday
