### ISSUE TITLE
Cannot get past "Invite code" thingy

### ISSUE THREAD

**Issue by 3nsoft** [lavab/web#456]
When doing 'gulp develop' and 'gulp serve', cannot get past invite codes. Below is log from a console on Firefox 37.0.1:
...
- GET http://localhost:5000/partials/validationMessages.html  200 OK
- Calling accounts.create.register [Object { ... }] ... utils.js (line 682)
- Error: Translation 'LAVABOOM.API.ERROR.ACCOUNTS.CREATE.REGISTER.400' not found!

    callee$3$0$()            utils.js (line 578)
    tryCatch()                 utils-vendor.js (line 2)
    invoke()                utils-vendor.js (line 2)
    onFulfilled()               utils.js (line 74)
    processQueue()               utils-vendor.js (line 16289)
    scheduleProcessQueue/<()               utils-vendor.js (line 16305)
    $RootScopeProvider/this.$get</Scope.prototype.$eval()               utils-vendor.js (line 17507)
    $RootScopeProvider/this.$get</Scope.prototype.$digest()               utils-vendor.js (line 17323)
    $RootScopeProvider/this.$get</Scope.prototype.$evalAsync/<()            utils-vendor.js (line 17546)
    completeOutstandingRequest()utils-vendor.js                (line 7965)
    Browser/self.defer/timeoutId<()utils-vendor.js                (line 8353)
    throw new Error("Translation '" + name + "' not found!");   utils-vendor.js (line 14696)

- accounts.create.register error: Object { body={...},  headers={...},  id="1",  more...} utils.js (line 710)

Is there a way to by pass this by setting something in local setting files? Just for development.

**Comment by flixi** [comment]
As far as I know, there is certainly something planned for that in the very near future to run your own api container and then also dockerize the front-end container. I would give it a week more or so... @andreis

**Comment by flixi** [comment]
Have a look at https://www.github.com/lavab/oss
