### ISSUE TITLE
Cannot read any encrypted emails

### ISSUE THREAD

**Issue by flixi** [lavab/web#457]
![bildschirmfoto 2015-04-13 um 22 37 18](https://cloud.githubusercontent.com/assets/707993/7125076/553a8f12-e22e-11e4-9222-49237a48171e.png)
https://gist.github.com/flixi/402a49c47511762bd52f
I can't tell whether or not my keys are decrypted because of the bug I reported to @let4be

**Comment by flixi** [comment]
https://mail.lavaboom.com/label/Inbox?threadId=fVm7ZpRs4I9oTI8VmEcT

**Comment by flixi** [comment]
Suddenly it worked again.

**Comment by flixi** [comment]
Let's look into that later on.

**Comment by let4be** [comment]
Should be fixed, if it's not open another issue
