### ISSUE TITLE
Some important functionality has been removed in the new settings/keys design

### ISSUE THREAD

**Issue by let4be** [lavab/web#458]
It used to have "decrypt this key" and "key encryption status"
Was it removed on purpose @piggyslasher and @vLooz ? are we going to have this implemented some other way?

**Comment by vLooz** [comment]
The new key dialogue mockups look like this for over a month: 
See: https://github.com/lavab/web/issues/326

The key encryption status could be indicated by the lock icons color. Like this.
![bildschirmfoto 2015-04-14 um 09 39 13](https://cloud.githubusercontent.com/assets/11177812/7132502/2adc9e34-e28a-11e4-97fb-b6c9c4443981.png)

What would a normal user need to decrypt keys? @let4be 

![2015-03-18_settings_keys_dialogs](https://cloud.githubusercontent.com/assets/11177812/7132463/d0ec95dc-e289-11e4-88b9-f32fdc7b45a5.png)

**Comment by let4be** [comment]
Thank you, @vLooz
 
but we need a way to indicate undecrypted keys, and a way to manually decrypt encrypted keys - i.e. entering their password

I can add the field like it was before - "enter key's password" for each undecrypted key

Will it work @vLooz ?

**Comment by vLooz** [comment]
Why do we need this? @let4be Aren't the keys auto-encrypted with your account password all the time?

**Comment by let4be** [comment]
They are, but we support this feature for pro-users
They can have keys protected with passphrase different from account's password, so they go to settings and decrypt them manually

**Comment by let4be** [comment]
this is also handy feature to know your key status, because if there was some bug/issue and you see all your emails encrypted - this may be useful to know your key encrypted/decrypted status

**Comment by vLooz** [comment]
I see. But like @flixi said at the end of the https://github.com/lavab/web/issues/326 thread, we don't want to focus on pro user features, before we have it done right for the normal users. 
I will bring those buttons back in a pro-user styleguide later.

Why can't we use the color codes, I've posted, for the key encryption status?

**Comment by let4be** [comment]
closing this and moving to #326
