### ISSUE TITLE
Contacts: implement "request key"

### ISSUE THREAD

**Issue by let4be** [lavab/web#460]

**Comment by let4be** [comment]
To be discussed how this should be implemented as sending public key over regular email cannot be considered safe, do we really want to go this way?

**Comment by let4be** [comment]
same question about https://github.com/lavab/web/issues/459

**Comment by mlooz** [comment]
Maybe you've discussed this already, but can you tell me why you don't consider sending public keys over regular emails to be safe? Many people share their public keys over open keyservers.

If you already have signatures on your key, than anyone intercepting the message could see who considers you trustworthy. However, for this case a stripped version of the key could be created and right now we are not adding signatures anyway.

**Comment by let4be** [comment]
for example:

Alice sends her public key to Bob. 
Smith is in between, reads sent public key, replaces it with own
Bob has no idea that this happened and uses received public key of an attacker to encrypt emails and send them to Alice
As Smith has complete control over Bob's communication channel - i.e. can read/replace the data he can easily gather encrypted email, decrypt with his own private key and then re-encrypt with original public key that Alice has sent.

Though, even sending public keys to unsecured emails would provide more security than un-encrypted communication

**Comment by mlooz** [comment]
Yes, the old man-in-the-middle attack. Thank you for thinking of this!

In the non-lavaboom world, three solutions for this problem exist:
**Fingerprints**: Show the fingerprint of received public keys for contacts. Alice and Bob can then compare the fingerprints of the original in Alice's account and the received one in Bob's account. They don't need a secure connection for this, only one which cannot be manipulated. A phone call would work, as long as they know each other's voices. If Smith replaced Alice's key with his own, they will notice.
*To implement for this:* Show fingerprint in contacts section, add option to mark key as untrusted/trusted. Add infographic to explain this to users who are curious.

**Socialist millionaire algorithm:** Used by the OTR protocol to authenticate users to each other if they have a shared secret. Works over insecure channels.
*To implement*: Protocol, explanation, interface

**Key signing and web of trust**: Necessary if Alice and Bob don't have a manipulation-proof connection. If Bob has verified the public key of Matt and Matt in turn has verified the key of Alice and signed it with his key, Bob can infer that the key he got is indeed from Alice. At least, if he trusts Matt. Of course one can extend this chain with additional participants between Bob and Alice, but with increasing length the risk of someone untrustworthy or [careless](https://xkcd.com/364/) rises. To mitigate this risk, everyone signs the keys of everyone they trust, then multiple paths exist between each pair of keys.
*To implement*: Key signing, trust levels, path finding in web of trust.

For the MVP, I suggest the first option. It is needed anyway for the third one and is commonplace in the non-lavaboom crypto ecosystem.

**Comment by mlooz** [comment]
Yes, the old man-in-the-middle attack. Thank you for thinking of this!

In the non-lavaboom world, three solutions for this problem exist:
**Fingerprints**: Show the fingerprint of received public keys for contacts. Alice and Bob can then compare the fingerprints of the original in Alice's account and the received one in Bob's account. They don't need a secure connection for this, only one which cannot be manipulated. A phone call would work, as long as they know each other's voices. If Smith replaced Alice's key with his own, they will notice.
*To implement for this:* Show fingerprint in contacts section, add option to mark key as untrusted/trusted. Add infographic to explain this to users who are curious.

**Socialist millionaire algorithm:** Used by the OTR protocol to authenticate users to each other if they have a shared secret. Works over insecure channels.
*To implement*: Protocol, explanation, interface

**Key signing and web of trust**: Necessary if Alice and Bob don't have a manipulation-proof connection. If Bob has verified the public key of Matt and Matt in turn has verified the key of Alice and signed it with his key, Bob can infer that the key he got is indeed from Alice. At least, if he trusts Matt. Of course one can extend this chain with additional participants between Bob and Alice, but with increasing length the risk of someone untrustworthy or [careless](https://xkcd.com/364/) rises. To mitigate this risk, everyone signs the keys of everyone they trust, then multiple paths exist between each pair of keys.
*To implement*: Key signing, trust levels, path finding in web of trust.

For the MVP, I suggest the first option. It is needed anyway for the third one and is commonplace in the non-lavaboom crypto ecosystem.

**Comment by mlooz** [comment]
Yes, the old man-in-the-middle attack. Thank you for thinking of this!

In the non-lavaboom world, three solutions for this problem exist:
**Fingerprints**: Show the fingerprint of received public keys for contacts. Alice and Bob can then compare the fingerprints of the original in Alice's account and the received one in Bob's account. They don't need a secure connection for this, only one which cannot be manipulated. A phone call would work, as long as they know each other's voices. If Smith replaced Alice's key with his own, they will notice.
*To implement for this:* Show fingerprint in contacts section, add option to mark key as untrusted/trusted. Add infographic to explain this to users who are curious.

**Socialist millionaire algorithm:** Used by the OTR protocol to authenticate users to each other if they have a shared secret. Works over insecure channels.
*To implement*: Protocol, explanation, interface

**Key signing and web of trust**: Necessary if Alice and Bob don't have a manipulation-proof connection. If Bob has verified the public key of Matt and Matt in turn has verified the key of Alice and signed it with his key, Bob can infer that the key he got is indeed from Alice. At least, if he trusts Matt. Of course one can extend this chain with additional participants between Bob and Alice, but with increasing length the risk of someone untrustworthy or [careless](https://xkcd.com/364/) rises. To mitigate this risk, everyone signs the keys of everyone they trust, then multiple paths exist between each pair of keys.
*To implement*: Key signing, trust levels, path finding in web of trust.

For the MVP, I suggest the first option. It is needed anyway for the third one and is commonplace in the non-lavaboom crypto ecosystem.

**Comment by flixi** [comment]
Not MVP! But soon afterwards it's worth having an in-depth discussion about this.

**Comment by mlooz** [comment]
Wow @let4be, you've been an issue-closing machine this morning! :-)

**Comment by let4be** [comment]
Yeeep :)
Thought this needs to be checked - I'm not sure did I meet the expectations with request public key/send public key.

- Request public key opens the compose screen with prefilled to
- Send public key opens the compose screen with prefilled to and attached public key

we probably may want to add default subject/bodies if so just open a separate issue for this

**Comment by flixi** [comment]
Is this in dev or on .com?

**Comment by let4be** [comment]
Currently only on develop branch, I'm finishing with some other tasks and then merging( ~ in a hour or so), after this we can deploy
