### ISSUE TITLE
Contacts: what to do if user enters the same emails twice?

### ISSUE THREAD

**Issue by let4be** [lavab/web#461]
There are some cases here:
- user adds the same email twice for the same contact(probably warn user somehow?)
- user adds the same email that already exists in another contact(probably warn user somehow?)
- user adds email that previously existed as so called "hidden contact"(supposed to replace hidden contact?)

Ideas?

**Comment by piggyslasher** [comment]
1. user adds  same email twice - warn him with a notification with timeout.
2. user adds same email that exists in another contact? let it happen. its up to a user how messy he wants to keep his contact list - but I like showing an intelligent button like 'Merge duplicate' when this happens. This means that if we have things like CSV import and stuff, managing your contact duplicates is a breeze.
3. hidden contact is definately already removed when you add a hidden email address into a real contact. i just checked that. also we've remove the whole hidden/private concept. now it just shows email address alone for hidden and name, email for private contact without any labels.

Here's whats on develop
![image](https://cloud.githubusercontent.com/assets/1991125/7260095/450e9bca-e89a-11e4-8dd0-83917e372086.png)

**Comment by let4be** [comment]
btw if we don't have hidden contacts anymore, should I make them visible in contacts list?
so user could give them names or delete the same as with other contacts

**Comment by let4be** [comment]
@vLooz what do you think?

**Comment by vLooz** [comment]
Is it possible to autosave only those contacts, the user actually did send an email to?
So instead of saving all hidden contacts, we'd only save those, which were actually used.

**Comment by let4be** [comment]
This is already implemented like this @vLooz - we save only those used in `to`/`cc`/`bcc` fields when email has been successfully sent
