### ISSUE TITLE
Contacts: something to prevent accidental remove/restore removed contacts

### ISSUE THREAD

**Issue by let4be** [lavab/web#462]

**Comment by let4be** [comment]
The subjects, it's super easy to remove contact and there is not way back

**Comment by piggyslasher** [comment]
i think we need to the yes/no notification. again - should we have a modal popup or the notification yes/no bar?

@vLooz 

The notification bar on top of the main pane seems to not block the user from doing other things. if we have a modal notification then it needs to be acted on before the user can do anything else.

Another way is an undo button that is shown for 10 seconds after a contact is deleted. Like how gmail and android do it.

**Comment by vLooz** [comment]
I'd go with the modal notification with yes/no @piggyslasher

**Comment by vLooz** [comment]
Something like this until I come up with something more specific :)
![bildschirmfoto 2015-04-15 um 16 13 39](https://cloud.githubusercontent.com/assets/11177812/7160600/6aa89eea-e38a-11e4-8ed3-823e09c15749.png)

**Comment by flixi** [comment]
Add "There is no way back."

**Comment by piggyslasher** [comment]
@let4be can we use this service so that we can have different kinds of dialogs?

http://codepen.io/m-e-conroy/pen/rkIqv

**Comment by flixi** [comment]
Yes. @piggyslasher that'S exactly what I talked about!

**Comment by piggyslasher** [comment]
yes boss. right now we have only the notification above the mail panel:

![image](https://cloud.githubusercontent.com/assets/4147061/7114437/ee3672ec-e1e5-11e4-8de2-de200e778fa3.png)

if we have this service (http://codepen.io/m-e-conroy/pen/rkIqv) we have the modal notifications as well. Will wait for @let4be to give input on this. But the good thing is that he has setup a notification service which centralizes all this stuff so we can add this functionality into one place.

**Comment by let4be** [comment]
@piggyslasher, service added

**Comment by let4be** [comment]
I'm pushing some more for this in the nearest hour or so:
- proper i18n integration
- example of use in settings/security

**Comment by let4be** [comment]
Anyway I we could consider making a "trash can" for contacts, or something that would help users to restore accidently removed contacts
What do you think, @vLooz ?

**Comment by vLooz** [comment]
I think we should do a warning popup like I posted above. When the user still wants to delete it then, it's ok to be not restorable.

**Comment by piggyslasher** [comment]
great. now we have this thanks to @let4be:
![image](https://cloud.githubusercontent.com/assets/1991125/7200112/4b92d55e-e52c-11e4-9e6e-9bbcaf266652.png)

I'm going to close this task because #410 covers this problem with styling.
