### ISSUE TITLE
If nameless contact exists, "To"-Field does not allow entering an address

### ISSUE THREAD

**Issue by mlooz** [lavab/web#469]
If a contact without a name exists, the To-Field does not allow entering an address.

In the To-Field, {{$select.getPlaceholder()}} is shown when the field is empty. When starting to enter an address, only suggestions for hidden addresses are shown. Clicking on the suggestions has no effect, hitting enter opens the CC/BCC fields and deletes the address I typed. Thus, it is not possible to enter a To-address.

What should happen: Prevent user from creating a contact without a name or handle it gracefully if he does.

Priority: Not dramatic, since I was breaking the interface on purpose. :-)

**Comment by let4be** [comment]
nice one, @mlooz 
Will fix

**Comment by mlooz** [comment]
Awesome, it works now!
Thanks, that was quick! :-)
