### ISSUE TITLE
PGP Key information is shown even when field is collapsed, mixing with other email adresses

### ISSUE THREAD

**Issue by mlooz** [lavab/web#471]
Steps to reproduce:
1. Create user with two addresses.
2. Add public key to first address.
![key-overlay](https://cloud.githubusercontent.com/assets/450175/7136656/6002c27c-e2b3-11e4-9f66-9649a664a75c.png)

**Comment by let4be** [comment]
oh this bug... I cannot reproduce it and having problem to fix it, probably @piggyslasher has the same issue?
It seems to be css related, I tried one simple fix but doesn't seem it helped

please your OS, browser version, branch on what you're testing

**Comment by let4be** [comment]
Basically collapse directive uses height: 0 when item is collapsed but it seems Safari(afaik only it has the problem) refuses to obey this setting

I've tried adding display: none to collapsed items and it's weird it doesn't help
https://github.com/lavab/web/blob/master/src/less/quirks.less#L11

**Comment by mlooz** [comment]
I'm testing it on Ubuntu 14.04, the issue happened with both Firefox 37.0.1. and Chrome 41.0.2272.118.
Can test more versions when I get to my other computer.

**Comment by let4be** [comment]
well... I've tested on all possible browsers on windows - not reproducable, let's wait for @piggyslasher input

**Comment by piggyslasher** [comment]
I have to test this again. When i left this last friday, it was working on all browsers. it pretty much uses the same code as contacts, which was also working. should be a quick fix.

**Comment by mlooz** [comment]
This seems to be an OS issue. On Ubuntu 14.04., the bug appears on all browsers I tested (Firefox, Chrome, Epiphany) both in the contacts and key settings.

**Comment by piggyslasher** [comment]
it doesnt seem to be an OS issue - as @flixi & @vLooz have seen it on their macs before.
[!image](https://cloud.githubusercontent.com/assets/707993/7125335/5076acd4-e230-11e4-9f34-b9a61944a419.png)

**Comment by piggyslasher** [comment]
please continue commenting on #446 @mlooz 

Thanks for all your effort!
