### ISSUE TITLE
"Send public key" button in Settings->Keys has trashcan icon otherwise used for deletion

### ISSUE THREAD

**Issue by mlooz** [lavab/web#476]
This is not an outright bug, but may confuse a user. If a user sees the trash can icon first in these settings and then assumes that this icon is associated with sending, there will be a bad surprise when it deletes something. A contact, for example.
@vLooz  Is this on purpose?

**Comment by piggyslasher** [comment]
no. the icons were not correct. fixed on my branch.

**Comment by piggyslasher** [comment]
i think some icon changes got lost in last weeks merge

now it looks like this:

![image](https://cloud.githubusercontent.com/assets/1991125/7152089/75b153e0-e367-11e4-8ed4-15040c19dce8.png)

closing this issue for now.

**Comment by vLooz** [comment]
Nice work @piggyslasher! Looking great!
