### ISSUE TITLE
Inbox threads are sorted by date of first message, should be date of last message

### ISSUE THREAD

**Issue by mlooz** [lavab/web#479]
Steps to reproduce:
1. Send first email (E1) from external address to lavaboom account
2. Send second email (E2) with different subject from external address to lavaboom account
3. Reply to E1 from lavaboom account, let's call this email E3
4. Reply to E3 from external account to lavaboom account (E4), use same subject as E1

Now emails E1, E3 and E4 should be in one thread on top. Instead, the thread of E2 is above.

This will be annoying if you have so many threads that some are scrolled out of view and you have to scroll all the way through your emails to look for new ones.

Proposed Category: Usability
Proposed Priority: Annoying

**Comment by flixi** [comment]
Agreed. Display the latest received email ontop, differentiate the sorting, so that it sorts via newest email instead of first email received.

**Comment by flixi** [comment]
Is this issue pushed to .com?

**Comment by let4be** [comment]
not yet, will merge today later with the other fixes/improvements

**Comment by flixi** [comment]
Great. ;)

**Comment by mlooz** [comment]
I'm afraid the "modified"-date is not the best choice here, as it updates on any modification. If you open a thread with previously unread emails, or delete and restore it, it will be placed at the top of the inbox again.

**Comment by let4be** [comment]
Then this is the task for @pzduniak as I have a choice only from data_created and date_modified, afaik

**Comment by flixi** [comment]
Moved.

**Comment by mlooz** [comment]
Deleting and restoring a thread still moves it to the top of the inbox in 5fc6a4ba51923c58f5cdf429e2e7647d72f68691.
