### ISSUE TITLE
Missing mouseover texts on top panel icons

### ISSUE THREAD

**Issue by mlooz** [lavab/web#480]
Steps to reproduce:
1. Open any non-empty email folder
2. Hover mouse over icons in top panel

The same applies for the contacts section.
Mouseover text is especially necessary for the trash can, as it is an unusual symbol for deletion

**Comment by piggyslasher** [comment]
1. i think the recycle bin, trash system in all the OSs use the trash can icon.
2. however for consistency since we have tooltips on other icons in the action bar (the black bar), this would take only a minute or two for me to add.

**Comment by mlooz** [comment]
1. True, the recycle bin itself is often represented by a trash can. I haven't seen it before for the *act of deletion*, though.
2. Consistency is always good! If you could add these, this would be awesome.

**Comment by piggyslasher** [comment]
will do

**Comment by mlooz** [comment]
Much easier now, thanks! :-)
