### ISSUE TITLE
No visual indication that a missing subject prevents the email from being sent

### ISSUE THREAD

**Issue by mlooz** [lavab/web#485]
When the subject is missing, it is not possible to send the email. This is indicated by the grayed out send icon, but there is no indication for the reason.

Possible Solution: Flash a red border around the subject line, or open a window asking for the subject, or just allow sending without subject.

I would favour the third or the second option, as flashing red always implies a user error. It is technically possible to send emails without subject lines and other email programs allow it.
Proposed labels: styling-required, enhancement

**Comment by flixi** [comment]
@vLooz @piggyslasher @let4be

**Comment by vLooz** [comment]
I would definitely go with the third version: Make it possible to send emails anyway, even without subject line and without text. The empty subject line could be auto-replaced with (no subject), like it's done in other mail clients.

**Comment by flixi** [comment]
Agreed.
