### ISSUE TITLE
Clicking anywhere after entering an address in the To-field deletes the address

### ISSUE THREAD

**Issue by mlooz** [lavab/web#486]
Steps to reproduce:
1. Compose a new email. Type an address in the To-Field.
2. Without clicking on the suggestions, click on the subject line or email body.

What happens: Address is deleted, even if it was complete

What should happen: The same behaviour as happens when hitting Tab or Enter: Address is transformed into new hidden contact 

Browser: Firefox on Ubuntu 14.04
Version: Both .com and 0.2.3 on local copy of development branch, commit 8da83c00384b41f7b86feb8c164ed248491fd7aa

Proposed Labels: enhancement, low-priority

**Comment by let4be** [comment]
That turned out to be quite interesting task ;)

**Comment by mlooz** [comment]
"Interesting" as in "way more work than it looks from the outside?" ;-)
