### ISSUE TITLE
Member list filtering should use GET /addresses

### ISSUE THREAD

**Issue by pzduniak** [lavab/web#488]
![Current result](http://qs.lc/l6eh9)

Maybe we could display it in an other way?

**Comment by flixi** [comment]
This is an alternate email address, so the pz-account also uses piotr as receipient.

**Comment by pzduniak** [comment]
dm me on slack for alternate email mappings to test them

**Comment by pzduniak** [comment]
It's low priority because we won't initially provide alt mappings to users.

**Comment by let4be** [comment]
Do you refer to the search box on the top of the page?
Actually search functionality is kind of incomplete now because it looks only in _downloaded_ threads/emails

**Comment by pzduniak** [comment]
Take a look at the screenshot please.

**Comment by flixi** [comment]
The way it is displayed inside the Email list.

**Comment by let4be** [comment]
So we want to show just piotr@lavaboom.com as another email is an alias, right?

**Comment by flixi** [comment]
nope, piotr is the alias we just want to display the from address.
