### ISSUE TITLE
Contacts with both, a secure and a non-secure email are shown as unsecure in the List.

### ISSUE THREAD

**Issue by vLooz** [lavab/web#489]
I think we should show contacts with multiple saved email addresses, among which are non-pgp addresses, should be shown as secure (closed lock) in the Contact list. 

2 reasons for this:

1)When the user writes a new mail and selects a recipients address, the locks indicate which one is secure and which not. I find it unlikely, that the user will confuse a safe address with an unsafe one.

2) Once a Contact already has one pgp-address connected (probably Lavaboom), there is no need for the user to do something about it (e.g. invite her to Lavaboom). From my POV we shouldn't confuse him by showing the Contact as insecure.

What do you think @flixi @pzduniak ?

**Comment by piggyslasher** [comment]
maybe we can do this - no icon for insecure, orange for semi-secure and blue for secure? just a thought.

**Comment by vLooz** [comment]
I don't think we need a semi-secure here. Once the contact has at least one secure email address, secure communication is possible @piggyslasher

**Comment by let4be** [comment]
Agree., will push a fix soon

**Comment by vLooz** [comment]
nice!
