### ISSUE TITLE
Make Roboto font use on-site version rather than from google

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#490]
We discussed this and I'm going to use embedded dataURI versions. Im just adding it so I have it on my list.
Why? Same reason we're embedding external images.
1) no external parties can have any record of users IP
2) not depending on external resources

Why not?
1) Roboto font can be cached on many computers and devices from Google (when user visits other websites which uses Roboto from Google) - i.e. no need to use extra bandwidth to reload this.
2) Don't stress our servers with another call for a pretty heavy file.

What need to be done (pretty easy stuff actually)
  - [ ] Convert Roboto to dataURI and put it in /fonts folder
  - [ ] Link the dataURI in our CSS file. Separate font CSS file. I know its one extra request but performance benchmarks suggest that this is necessary to not slow down font load time and FOUT ([Flash of unstyled text](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CB0QFjAA&url=http%3A%2F%2Fpaulirish.com%2F2009%2Ffighting-the-font-face-fout%2F&ei=fDwvVaCyDcy3uASfkoDYDA&usg=AFQjCNGsd5OKPcChVsEJ5KNgwwdtFQqeXw&sig2=oetoV2y788mBczuz_tlqLA&bvm=bv.91071109,d.c2E))

@andreis @pzduniak @flixi

**Comment by flixi** [comment]
If the User has Roboto in his cache somewwhere it means that the font is not reloaded and thus creating no time constraints.

**Comment by piggyslasher** [comment]
yes. thats true. _if its cached_. if not it loads from google.

**Comment by piggyslasher** [comment]
also - android devices already have Roboto. if i use the dataURI version the font is _always_ downloaded once into the cache - even if it exists locally.

**Comment by flixi** [comment]
dataURI it is then.
I'm sure our servers can handle the amount of requests.

**Comment by piggyslasher** [comment]
Thanks boss. 2.1?

**Comment by piggyslasher** [comment]
closing this as #840 is newer.
