### ISSUE TITLE
Mail can't be delivered to Lavaboom

### ISSUE THREAD

**Issue by vLooz** [lavab/web#493]
I've send a Mail from my Gmail account (felix.vlooz@gmail.com) to my Lavaboom account (felix.vlooz@lavaboom.com). After a while I got this Notification Mail. 
The same happened, when I tried to send a mail to Moritz (moritz@lavaboom.com) from the very same gmail account. 
Do you have a clue what's causing this? @pzduniak @andreis ?

This is an automatically generated Delivery Status Notification

THIS IS A WARNING MESSAGE ONLY.

YOU DO NOT NEED TO RESEND YOUR MESSAGE.

Delivery to the following recipient has been delayed:

     felix.vlooz@lavaboom.com

Message will be retried for 2 more day(s)

Technical details of temporary failure: 
read error: generic::failed_precondition: read error (0): error

—— Original message ——

DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=date:mime-version:message-id:from:to:content-type
         :content-transfer-encoding;
        bh=6hbrGxKqhKljWWbFtUJkWEJSx8ud/RxrgnMujhODWOg=;
        b=LXE4vLeHj4cyrLGm1ejleK0y9K3cCmZ3hLVer31AXDs9kXvZCTcHTE+k0mNhn+H9ym
         0V+/0fFscxRrbpuidFGExUX+b8ly5QV3uzfELqDy6/sgXXC+ZqIHoaGkwr7bBecg4iai
         7W4wOIoZZHoD0dQ+INmAt4Lw7pXfKULTk9AeBwmhxUVpiP6hw1nXRLUcQojWmX62bs9R
         mZmUqYWHFe/++7dF3P1uUJzUY8UVyt8BGU9+WM8TDH/JgBUeQEIo36J8GwR932DQ7cYj
         Hq2f78VNdXf2siBWBw7p/3soIs8u7JM8nOnh670sukj+yP3Z+s+zT7qNX41H0rgn7PT0
         E9lw==
X-Received: by 10.55.16.140 with SMTP id 12mr51078500qkq.39.1429109962511;
        Wed, 15 Apr 2015 07:59:22 -0700 (PDT)
Return-Path: <felix.vlooz@gmail.com>
Received: from hedwig-66.prd.orcali.com (ec2-54-85-253-215.compute-1.amazonaws.com. [54.85.253.215])
        by mx.google.com with ESMTPSA id a62sm3320633qge.49.2015.04.15.07.59.19
        for <felix.vlooz@lavaboom.com>
        (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Wed, 15 Apr 2015 07:59:20 -0700 (PDT)
Date: Wed, 15 Apr 2015 07:59:20 -0700 (PDT)
X-Google-Original-Date: Wed, 15 Apr 2015 14:59:19 GMT
MIME-Version: 1.0
X-Mailer: Nodemailer (0.5.0; +http://www.nodemailer.com/)
Message-Id: <1429109959338.e3c66df5@Nodemailer>
X-Orchestra-Oid: 51270399-C6BF-45E2-B1CB-AD70CEF8A0C4
X-Orchestra-Sig: 7a645161b8295d75e538d5b6bf3be1bdcc0c6c88
X-Orchestra-Thrid: E6210077-4984-4FD7-AE0A-A5A0B2B8433E
X-Orchestra-Thrid-Sig: f5b7fd797d49af2cc6a7b5c58616e5d3c9e20dff
X-Orchestra-Account: 9781cf09de892023b6d735c587d9172d4485eb7e
From: „Felix von Looz“ <felix.vlooz@gmail.com>
To: „Felix von Looz“ <felix.vlooz@lavaboom.com>
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

—— End of message ——

**Comment by let4be** [comment]
@vLooz we have https://github.com/lavab/mailer/issues for such kind of stuff,
could you please post mailer issues there? web already has enough its own...

**Comment by flixi** [comment]
Moved.
