### ISSUE TITLE
Can't seem to sync any sent emails, if I hit the folder sent, it won't show me anything past that date.

### ISSUE THREAD

**Issue by flixi** [lavab/web#498]
![bildschirmfoto 2015-04-17 um 13 39 13](https://cloud.githubusercontent.com/assets/707993/7201444/6fed5ac0-e507-11e4-8952-f3b252ea2e33.png)

**Comment by let4be** [comment]
Hm... does it have less emails than it should to? It could be caused by API

**Comment by flixi** [comment]
Yes, it does.

**Comment by let4be** [comment]
Related logic has been updated, is it still the case?
