### ISSUE TITLE
action button styling differences between contacts and emails

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#502]
not sure if this is important but i feel that it needs a mention.

in contacts we have the trash symbol in the mid-pane like so:
![image](https://cloud.githubusercontent.com/assets/1991125/7215336/abdde064-e605-11e4-95ce-ccb8b9264c44.png)

Whereas in the emails system we have it here:
![image](https://cloud.githubusercontent.com/assets/1991125/7215337/c4257cea-e605-11e4-9abd-cc582f718655.png)

**Comment by vLooz** [comment]
You are right @piggyslasher, thats not consistent. I think we should move the icons in the inbox to the left, too.

**Comment by piggyslasher** [comment]
lol. because the icons in the inbox _were_ on the left and you moved it into the email area. To be honest its more of @let4be's work than mine because he needs to move the code between controllers. I've assigned it to him.

**Comment by mlooz** [comment]
Does this mean it is impossible to delete a single email, just entire threads?

**Comment by flixi** [comment]
Yes, but it'S the same way GMAIL handles it.

**Comment by vLooz** [comment]
Connected to this discussion: https://github.com/lavab/web/issues/370#issuecomment-95421677

**Comment by let4be** [comment]
um, so should I move icons back where they were?... we need to decide on something
are we going to show icons for both contact and email on the left or on the right?

**Comment by let4be** [comment]
@vLooz

**Comment by vLooz** [comment]
Get rid of the "star" and the "trash" icon (the functionality is covered in the contact sheet) and move the "new contact" icon the the left end of the right panel (same position of the trash icon in inbox)

**Comment by piggyslasher** [comment]
just one thing. The new contact is not actually an action on a contact. its an action for creating a new contact. In this case, it would be better to have the new button in the middle panel. whereas all buttons in the right panel are for actions on the current contact being viewed. If we are getting rid of star and trash, it would be okay to just keep the add new contact button in the middle. just my two cents :)

**Comment by vLooz** [comment]
Alright, let's do it like @piggyslasher suggested then!
