### ISSUE TITLE
SearchField: no shadows

### ISSUE THREAD

**Issue by vLooz** [lavab/web#509]
Situation:
When I click into the search field, additional vertical shadows appear at its left and right border. See screenshot.

Please remove them! :-)

![bildschirmfoto 2015-04-22 um 15 55 40](https://cloud.githubusercontent.com/assets/11177812/7276141/1ca3b2ba-e908-11e4-8a4d-ac1bebf33341.png)

**Comment by piggyslasher** [comment]
fixed. this was default focus styling. but now its not having the shadow. the icon is also 44x44px. closing this issue.
