### ISSUE TITLE
Mail threads: Make separations more clear

### ISSUE THREAD

**Issue by vLooz** [lavab/web#510]
Status Quo:
When I write an email, I get an reply and reply to this replay again, it all gets into one pretty long mail, which is a bit messy optically hard to separate.
![bildschirmfoto 2015-04-22 um 15 39 55](https://cloud.githubusercontent.com/assets/11177812/7276253/b21bede4-e908-11e4-9e2c-e1dbbe5a622c.png)

How I'd like it  to be:
![2014-11-28_lavaboom_ui-inbox2-01 kopie](https://cloud.githubusercontent.com/assets/11177812/7276318/16e7f3b2-e909-11e4-9c4b-a89642d576b7.png)

**Comment by piggyslasher** [comment]
yes. i asked @let4be before if the reply could give me a tag to suppress and hide the previous emails. Something like a collapse/expand function.

currently how its above is how our api works. reply will include previous email inside the body. let me check the code and see if i can do anything from my side.
