### ISSUE TITLE
Inbox: Flat when nothing is selected, shadows for the selected on. No blue frame!

### ISSUE THREAD

**Issue by vLooz** [lavab/web#511]
Status Quo:
1) When not selected and not hovered over, the mails all appear flat.
2) When hovered over, the mail 'pops' up, by getting a shadow to the top and bottom and a blue line appears.
3) When clicked, nothing happens. Once I remove the cursor, all mails appear flat again.

![bildschirmfoto 2015-04-22 um 16 06 10](https://cloud.githubusercontent.com/assets/11177812/7276395/a2e17686-e909-11e4-9d9c-c786d2a66252.png)

How I'd like it to be:
1) all great. Nothing to change here
2) When hovered over, the mail 'pops' up, by getting a shadow to the top and bottom. NO blue line please, just remove it.
3) Once clicked, the shadow stays until another mail is clicked or the Inbox is left.

![2014-11-28_lavaboom_ui-inbox2-01 kopie](https://cloud.githubusercontent.com/assets/11177812/7276375/713d5ab4-e909-11e4-86da-11b7566c458a.png)

**Comment by piggyslasher** [comment]
there is currently no 'active' state in emails so we can't 'select' an email by clicking on it. I will check with @let4be if its possible to do this. it should be. just need to catch the clicks without interrupting anything else inside from not being clicked (i.e. links / reply / forward etc)

**Comment by piggyslasher** [comment]
- [x] no blue frame
  - [x] shadow on hover
  - [ ] mail should be 'active' when clicked on.
