### ISSUE TITLE
Inbox/Mail Preview: Please bring back the blue or grey locks :-)

### ISSUE THREAD

**Issue by vLooz** [lavab/web#512]
Status Quo:

![bildschirmfoto 2015-04-22 um 16 13 35](https://cloud.githubusercontent.com/assets/11177812/7276566/c85aadb4-e90a-11e4-9cfc-8790a4915c62.png)

How I'd like it better:

![2014-11-28_lavaboom_ui-inbox2-01 kopie 2](https://cloud.githubusercontent.com/assets/11177812/7276558/b363f730-e90a-11e4-938a-0a340a8fb570.png)

**Comment by flixi** [comment]
Where does this happen?

**Comment by vLooz** [comment]
Mail preview (Inbox, Sent etc)

**Comment by flixi** [comment]
.com or dev-branch?

**Comment by piggyslasher** [comment]
Im making an update. It should be on develop in a few hours. This icon is
there but its hidden. Let me check if I can get it to display properly.

**Comment by piggyslasher** [comment]
I'm adding a blocked label to this. I have styled the icons but unfortunately the API still needs this per-email encrypted/unencrypted check.

@let4be @pzduniak

**Comment by flixi** [comment]
Don't get why it's blocked?

**Comment by piggyslasher** [comment]
we don't have per-email isSecure() method (to determine lock/unlocked icon). Also per-email favorites doesn't exist.
