### ISSUE TITLE
Logout sometimes hangs with "Initialization failed..."

### ISSUE THREAD

**Issue by mlooz** [lavab/web#513]
Happened on Firefox and Chrome, both on .com and c62b90f3b4b60186b13afe458b8d56f3e0062a44
![2015-04-22-16-49](https://cloud.githubusercontent.com/assets/450175/7277352/da395b5c-e90f-11e4-8615-61455ac87481.png)

**Comment by flixi** [comment]
Can you please provide some logs?

**Comment by mlooz** [comment]
What kind of logs?
Here is a log of the Firefox developer consoler, it might be of help:
https://gist.github.com/mlooz/b3d747f964f6a5c6cbc7

**Comment by flixi** [comment]
Yes, I have encountered this bug as well, on Safari and Chromium.

**Comment by piggyslasher** [comment]
got this on .com too - although i dont get it on local. on .com the log is:
![image](https://cloud.githubusercontent.com/assets/1991125/7332152/dfbbae1c-eb63-11e4-82c3-c45bbf3b28e6.png)

**Comment by let4be** [comment]
Its es6 method of string, but string object is null for some weird reason
