### ISSUE TITLE
suddenly, this email from days ago appeared between today's emails

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#515]
![image](https://cloud.githubusercontent.com/assets/1991125/7279146/62a2dc8e-e94c-11e4-815d-2eecdb9f1da9.png)

as you can see the dates - this shouldnt be in this order. i cant replicate this again but it happen.

**Comment by piggyslasher** [comment]
again, this email was already there. just on this refresh it appeared in this order.

**Comment by mlooz** [comment]
Did you modify it in any way, for example answering it?

This happens to me regularly on c62b90f3b4b60186b13afe458b8d56f3e0062a44 and .com.

Reading, answering and restoring from trash will put the email back to the top of the inbox. See also https://github.com/lavab/web/issues/479

**Comment by piggyslasher** [comment]
i might have restored it from trash. you might be right. will check this later.

**Comment by piggyslasher** [comment]
#525 might be related. But I have sent 4 or 5 test emails around today and this hasn't happen. Will keep a lookout.

**Comment by let4be** [comment]
This is caused by how API implements sorting
