### ISSUE TITLE
Attachments don't work

### ISSUE THREAD

**Issue by flixi** [lavab/web#517]
I posted on slack about this already. The file sizes between the two files is quite a lot.
First PDF was 752 KB big and only displayed white nothingness. The next one downloaded from Gmail, the exact same document was 488 KB and had all the information displayed neatly.

Plus on Safari you can't even download the files. It displays te downloading thing in the browser however there is no file download triggered.

**Comment by let4be** [comment]
confirmed, it seems attachment gets corrupted somewhere

**Comment by let4be** [comment]
Interesting will have to use openpgp.js Message class directly, as mentioned here: https://github.com/openpgpjs/openpgpjs/issues/162

**Comment by let4be** [comment]
The problem with binary attachments should be solved,
could someone check attachments downloading from osx and safari?

**Comment by flixi** [comment]
Yes @piggyslasher can you do the honors?

**Comment by let4be** [comment]
This one should work better, but again not sure about safari

**Comment by piggyslasher** [comment]
I have checked this. mentioned on the #web channel on slack. the PDF attachments don't work.

Now I've tested again - no attachments work. Not JPG or PDF or even zip.
![image](https://cloud.githubusercontent.com/assets/1991125/7481388/21c37056-f3a2-11e4-8c78-680d697a32b5.png)

On latest develop branch.

**Comment by let4be** [comment]
Someone from windows and Firefox/Chrome? probably it's safari only issue now

**Comment by piggyslasher** [comment]
doesnt work on chrome/osx. firefox/osx and safari/osx

**Comment by piggyslasher** [comment]
i.e. attachments *work* but cant be opened.

**Comment by flixi** [comment]
I just had someone complaining on Firefox and OS Win 7 Prof.

**Comment by let4be** [comment]
This seems to be a generic problem with saving js generated data - tons of browser incompatibilies, going to address whole bunch of such issues soon

**Comment by flixi** [comment]
Grand.

**Comment by piggyslasher** [comment]
cool. because it just simply doesnt work for me. zip, pdf whatever. other than an embedded image nothing can be attached. tested a few files.
