### ISSUE TITLE
request: guidelines for the logo

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#520]
![image](https://cloud.githubusercontent.com/assets/1991125/7332148/568d565e-eb63-11e4-8416-5dec8cd96245.png)

so i'm a sucker for performance, so i've reduced the logo size without the illustrator shadows from 60kb to about 5kb (removed the drop shadows from the SVG and want to add it using css).

thing is, i've also separated the actual logo from the lavaboom text in the logo to two separate files. this is because the login page will load faster because it only uses the 'flaming icon' part of the logo.

![image](https://cloud.githubusercontent.com/assets/1991125/7332186/9854c6e2-eb65-11e4-8ef4-dd07b422edb0.png)

![image](https://cloud.githubusercontent.com/assets/1991125/7332207/2d1dff7c-eb67-11e4-8da4-f4692ae2add0.png)

so if you can give me guidelines for the logo with respect to the compose button, that would be great. jus give me a screenshot with your amendments with corrections of spacing/measurements on them. don't need to give me the actual end output with actual measurements. whatever is easy for you.

p.s. i know the compose and other left-panel icons are off size because of the new icons - am still working on that to be 22x22px right now @vLooz

**Comment by vLooz** [comment]
Here you go @piggyslasher 
![520 logo-position_guidelines](https://cloud.githubusercontent.com/assets/11177812/7350836/ea64d8f8-ed01-11e4-9e1d-e8377bca3769.png)

**Comment by piggyslasher** [comment]
great. this is more than enough. thanks :)

**Comment by piggyslasher** [comment]
looking good for now. please re-open if you see any issues.
