### ISSUE TITLE
sorting of emails is weird again.  as you can see emails are not sorted reverse chronologically.

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#525]
No email actions such as forward or reply were sent for this to happen. not even compose in the past two days.
![image](https://cloud.githubusercontent.com/assets/1991125/7395909/e591f750-eecf-11e4-8aa6-2517a0094784.png)

**Comment by piggyslasher** [comment]
sorry. i thought that was when we make replies and forwards. this is basically an untouched list. haven't made any email actions for 3 days.

**Comment by mlooz** [comment]
Steps to reproduce:
1. At time T1, send email from Lavaboom account to external account
2. At time T2, reply from external account to Lavaboom account
3. At time T3, open email in Lavaboom for the first time

What happens:
Time T1 is shown in the inbox (left panel), time T2 is shown in the email itself (right panel), time T3 is used to sort the threads in the inbox. 

What should happen:
Time T2 is used for everything.

@pzduniak As mentioned in #479, this requires api support.

**Comment by mlooz** [comment]
@piggyslasher you were right, it also happens without replies and forwards or reading previously unread emails. Steps to reproduce were "wildly clicking on different folders while scrolling up and down", which is unfortunately not reliable.

**Comment by let4be** [comment]
This is caused by how API implements sorting

**Comment by piggyslasher** [comment]
@pzduniak

**Comment by piggyslasher** [comment]
closing this as dupe. please #515
