### ISSUE TITLE
request: guidelines for settings middle navigation

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#527]
![image](https://cloud.githubusercontent.com/assets/1991125/7404628/77038c9c-ef18-11e4-86ec-e8c849084c3c.png)

Just need this tiny guideline. Please point me to the right image if you've already done it. I can't find it on slack.

**Comment by vLooz** [comment]
The settings guidelines were under the first Illustrator-Files I gave you. The ones with the green lines, showing x and 1/2x etc. I will make them more easy to understand though, give me 20mins

**Comment by vLooz** [comment]
Here you go @piggyslasher 

![bildschirmfoto 2015-04-30 um 09 27 51](https://cloud.githubusercontent.com/assets/11177812/7408252/3d54a9c4-ef1b-11e4-84ba-aa3f4f673fc8.png)

**Comment by piggyslasher** [comment]
looks perfect now:)

![image](https://cloud.githubusercontent.com/assets/1991125/7409428/04493b84-ef59-11e4-889e-621cb67eb9da.png)
