### ISSUE TITLE
Connection error handling

### ISSUE THREAD

**Issue by let4be** [lavab/web#535]

**Comment by flixi** [comment]
Can you describe this please?

**Comment by let4be** [comment]
Currently some issues possible when connection is dropped, this may cause unexpected behavior
- if connection drops during loading threads or emails this action hangs with "loading" sign forever
this can be cured with page-refresh, but the proper way is to reject those "actions" when connection is lost

**Comment by flixi** [comment]
Ahkay. Not MVP though.

**Comment by let4be** [comment]
This is actually more important @flixi because the same may happen during signup...

**Comment by let4be** [comment]
I made sure api-client-js tracks connection state properly so this problem shouldn't totally break the application like it did before
