### ISSUE TITLE
Feature Request: Import Public Keys From Keyserver

### ISSUE THREAD

**Issue by jrselzer** [lavab/web#538]
An option to import PGP keys from public key servers would be nice. Unexperienced users might not be willing to export keys from a keyserver into a file and to import the file into Lavaboom's GUI.

**Comment by mlooz** [comment]
I also would like to have this, mentioned in https://github.com/lavab/web/issues/495.

**Comment by jrselzer** [comment]
OK, let's mark #538 as a duplicate and close it.
