### ISSUE TITLE
Backup Key Pair - no visible result

### ISSUE THREAD

**Issue by jrselzer** [lavab/web#539]
OS: Win 7
Browser: Firefox 37.0.2

Settings > Keys > Backup Key Pair doesn't tell me whether it succeeded or not. Above that I'd like to know where it stored the backup so I can copy the files to a pen drive.

**Comment by pzduniak** [comment]
It just downloads a file, so it seems that there's something wrong with FF (similar to what happens when you try to save anything in Safari on OS X),

**Comment by let4be** [comment]
Local generated file download feature has lots of problems with browser compatibility, this should help:
https://github.com/lavab/web/commit/a49b25a39b2da79c026921fff190bebe2bde2ae4
Safari probably will need browser detection and special hack to make this work as intended
