### ISSUE TITLE
Send Public Key - no visible result

### ISSUE THREAD

**Issue by jrselzer** [lavab/web#540]
OS: Win 7
Browser: Firefox 37.0.2

Settings > Keys > Send Public Key shows no result. Has the key been sent to Lavaboom's keyserver, has it been sent to a public keyserver, was it intended to be sent by mail to another address but failed?

**Comment by let4be** [comment]
This is still not implemented feature,
@flixi should it simple open a compose screen with attached public key?

**Comment by let4be** [comment]
Duplicate of https://github.com/lavab/web/issues/459
