### ISSUE TITLE
Sent mails suddenly disappearing

### ISSUE THREAD

**Issue by jrselzer** [lavab/web#541]
OS: Win 7
Browser: Firefox 37.0.2

A sent message suddenly disappeared from sent folder.

**Comment by jrselzer** [comment]
After some clicks mails are being displayed again. Currently no idea how to reproduce this behavior.

**Comment by let4be** [comment]
Related logic has been updated, is it still the case?

**Comment by jrselzer** [comment]
No further incidents of this type noted. I'll keep an eye on it and file an issue when it happens again.
