### ISSUE TITLE
No access to "Contacts" and "Settings"

### ISSUE THREAD

**Issue by jrselzer** [lavab/web#543]
OS: Ubuntu 14.04
Browser: Chromium

Contacts and Settings buttons are shown in left navigation bar, but are deactivated.

**Comment by pzduniak** [comment]
Could you list out steps to reproduce? Everything works here.

![It works here](http://qs.lc/ccd9h)

**Comment by jrselzer** [comment]
1) Open browser
2) Enter https://lavaboom.com as URL 
3) Click "log in"
4) Wait for GUI to open
5) Move mouse over fields in navigation bar
6) Mouseover effects visible for "Compose", "Inbox", "Sent", "Starred", "Spam". No mouseover for "Trash", "Contacts" and "Settings". Clicking on these fields gives no results.

I use

Chromium 41.0.2272.76

**Comment by let4be** [comment]
that's weird as there shouldn't be anything special on "Trash", "Contacts" and "Settings" afaik

**Comment by jrselzer** [comment]
Maybe it has something to do with the window size. I'm using a netbook with a rather small screen. Therefore only symbols are shown. Text is only visible when the mouse pointer hovers over the icon.

**Comment by let4be** [comment]
This makes sense - issue reproduced.
@piggyslasher can handle this I guess

**Comment by piggyslasher** [comment]
Hrmm. I'm trying my best to replicate this. I just loaded .com and I get the tooltip:
![image](https://cloud.githubusercontent.com/assets/1991125/7481148/8c34cd2e-f3a0-11e4-9f52-6c1f399c74a4.png)

And I can access my contacts:
![image](https://cloud.githubusercontent.com/assets/1991125/7481155/99eb7ac6-f3a0-11e4-9503-2458baa6fb17.png)

I need to recheck this again a few times. Thanks for the input.

**Comment by piggyslasher** [comment]
noticed the count badges are not aligned in the condensed view - created #561

**Comment by piggyslasher** [comment]
weird. I have no such issues.
![image](https://cloud.githubusercontent.com/assets/1991125/7488253/372830aa-f3fa-11e4-856a-d353a64cd61c.png)

works on ff/chrome

@let4be - can you please check please?

**Comment by piggyslasher** [comment]
Apologies. Tracked this down to the height of the screen being less as well. Fixed on develop.

**Comment by flixi** [comment]
IS this on prod yet. @piggyslasher @let4be

**Comment by let4be** [comment]
yes, can be closed
