### ISSUE TITLE
Better shortcuts bindings

### ISSUE THREAD

**Issue by let4be** [lavab/web#545]
There are some bindings that conflict with default wide-used browser hotkeys such as ctrl+t

**Comment by let4be** [comment]
@andreis @flixi @vLooz @mlooz please suggest your ideas regarding bindings we can use,
we need to get rid of current mapping as fast as possible

**Comment by vLooz** [comment]
Can't we just go with those wide-used browser hotkeys?

**Comment by andreis** [comment]
Where are the current bindings? Obviously don't override standard ones, but Ctrl+T sounds weird af. That's not what my specs said.

**Comment by let4be** [comment]
this task was delegated that's why...
will check this against https://trello.com/c/9AoYJDgd/42-keyboard-shortcuts-searchable-settings
no idea how we got ctrl+t as a binding

**Comment by andreis** [comment]
Me neither. Yay freelancers

**Comment by mlooz** [comment]
@andreis I can't see the trello yet. Can you give me a link to the current bindings?

**Comment by andreis** [comment]
@mlooz email me your email/trello username so I can add you

**Comment by andreis** [comment]
Also, keyboard shortcuts are WIP. I just added a few ones I consider common sense:

```?: help overlay for keyboard shortcuts
/: focus search bar
hjkl: vim-like navigation for emails (also, arrows)
c, n: compose new email
Ctrl/Cmd+Enter: send email
a: archive selected email
d: delete selected email
r: reply to selected email
i: inbox```

**Comment by andreis** [comment]
Nvm, added @moritzvonlooz

**Comment by let4be** [comment]
```
Andrei Simionescu [6:27 PM] 
@let4be: feature request (from me and other users): `Backspace` should delete emails, and `Ctrl/Cmd+Enter` should send them. Plz do this if it’s not too time consuming.```

**Comment by andreis** [comment]
Damn, you're fast :P

**Comment by let4be** [comment]
Ok, now time to actually code something from this :D
