### ISSUE TITLE
"Error occured" when trying to send encrypted mail to external address

### ISSUE THREAD

**Issue by jrselzer** [lavab/web#547]
OS: Win 7
Browser: Firefox 37.0.2

1) Add new external (i.e. not Lavaboom) address to address list
2) Get ASCII file containg this address' public key
3) Go to address book
4) Click on open padlock next to external address
5) Choose "upload key"
6) Choose file
7) Click upload
8) Wait for this process to complete
9) Open existing mail thread with this address
10) Click on reply
11) Type some text
12) Click on send
13) Error message "error occured" appears in mail editor window.

**Comment by jrselzer** [comment]
Error not only comes up when replying to an existing thread but also when writing a new mail.

**Comment by let4be** [comment]
can't reproduce this on the latest develop branch... we're merging this into master today

**Comment by let4be** [comment]
If someone manages to get this again, logs are welcomed
