### ISSUE TITLE
Weblinks in emails are moved to end of text

### ISSUE THREAD

**Issue by mlooz** [lavab/web#549]
Steps to reproduce:
- Send email to yourself, with link in first line and no link in second line.

Result:
In received email, second line is shown before first line.

**Comment by let4be** [comment]
unable to reproduce both with
1.
plain-text link
text
2.
<a href="">< /a>
text

**Comment by mlooz** [comment]
Possibly a Firefox problem.
Bug occurs with Firefox on .com and 1e6ca6e8f21216df143bfce43304d89305c5eb7a
Bug does not occur when sending emails with Chrome 1e6ca6e8f21216df143bfce43304d89305c5eb7a, didn't test on .com

Emails sent with Firefox are still shown jumbled when viewed in Chrome, implying a problem in the composition or sending process.

**Comment by let4be** [comment]
Thanks for the imformation @mlooz, will check

**Comment by mlooz** [comment]
On .com:
Emails sent with chrome are shown okay when viewed with Firefox.
Emails sent with Firefox to external account are shown jumbled in Firefox, but arrive okay in Thunderbird.

**Comment by let4be** [comment]
Looks like this is firefox specific bug in emailBody directive
https://github.com/lavab/web/blob/master/src/js/apps/AppLavaboom/directives/emailBody.js#L42-42
messes up positions of text and nested tags...

**Comment by let4be** [comment]
What is more weird why did it work in chrome...

**Comment by mlooz** [comment]
Weird indeed. No longer occurs with Firefox on 03d1fbcb7b55f65f0c7d32d08de911428c6ca099.
