### ISSUE TITLE
New Mail in Inbox is shown as "1" in mail counter, but doesn't appear in inbox

### ISSUE THREAD

**Issue by vLooz** [lavab/web#552]
Henrik send me a mail (lavaboom to lavaboom) and the inbox counter is showing it, but it is not in my inbox. Because I can't click the mail there, the counter would not disappear.

Henrik had some problems to send and receive lavaboom-to-lavaboom mails before (during the past days), but can send lavaboom-to-gmail mails.

The same time my brother send me an email, which made the counter switch to "2". This one appeared in the inbox just fine. When I selected it, the counter jumped back to "1", still without displaying Henriks Mail.

**Comment by let4be** [comment]
Such issues always require logs from developer console or telepathist with advanched extra-sensore abilities...

**Comment by vLooz** [comment]
I'm just a normal user writing to support ;-)

**Comment by let4be** [comment]
right, this is why we need to https://github.com/lavab/web/issues/279
without this we will be like without hands trying to track issues on production

**Comment by let4be** [comment]
Related logic has been updated, is it still the case?

**Comment by flixi** [comment]
@vLooz Can you check?

**Comment by vLooz** [comment]
nah, still showing me the "1" counter in my Inbox and no Mail from Henrik :(

**Comment by mlooz** [comment]
Initial problem reproduced right now on 6fefe6b61b702ee436d648d424e2955e4d36da3b, log is on https://gist.github.com/mlooz/372572195f1d527769e7.

Logging out and back in fixed the problem for me.

**Comment by vLooz** [comment]
mmh... I logged in and out on the ".com" version and on the "http://127.0.0.1" one, but it's till the same. Neither I see the mail in inbox, nor does the "1" counter go away. 
If you guys tell me how to send you my logs, I'm happy to provide all the info you might need.

**Comment by let4be** [comment]
open developer tools(F12 or google how to do this in your browser)
then look for console tab, copy and paste logs from console tab to gist

**Comment by vLooz** [comment]
Alright, hope that worked: https://gist.github.com/vLooz/d1193c94fe36f4b83780

**Comment by let4be** [comment]
@vLooz please:
1. open some working email
2. open developer tools and clear all console logs
3. open buggy email
4. copy newly appeared console logs

your previous logs are lacking important information

**Comment by let4be** [comment]
eh... no helping information , doesn't seem to be covered with logs

**Comment by vLooz** [comment]
damn...

**Comment by mlooz** [comment]
This too may be connected to https://github.com/lavab/api/issues/129
One way to reproduce:
1. Send email from external account to lavaboom account with subject "foo"
2. Delete thread in lavaboom
3. Send second email from external account to lavaboom account with subject "foo"

What happens:
Second email is sorted into the first thread, which is in the Trash folder. Inbox counter is increased, but email does not appear in Inbox, exactly as @vLooz described.

Felix, could you look into your trash and spam folders if there is a thread with the same subject?

**Comment by let4be** [comment]
Very good catch, @mlooz 
we thought about the same just without the n. 3 case

**Comment by let4be** [comment]
lavab/api#129 is most likely the real cause of this issue

**Comment by vLooz** [comment]
:D This indeed solved it @let4be. I've found the mail was in Trash. I put it back to inbox, and read it. After that the counter disappeared.

**Comment by let4be** [comment]
fun issue... @pzduniak asap

**Comment by vLooz** [comment]
actual log files: https://gist.github.com/vLooz/89b73399547cc1d66b2d

**Comment by vLooz** [comment]
actual log files: https://gist.github.com/vLooz/89b73399547cc1d66b2d

**Comment by vLooz** [comment]
More info about what probably caused this bug: 
The subject of Henriks Mail, that would not appear in Inbox was "Test". 
Andrei sent me a mail with the exact same subject a while ago and I moved it to trash.
Henriks mails apparently was connected to Andreis Mail as being part of same (deleted) thread because of the subject, even though the sender was completely different in both cases.

**Comment by let4be** [comment]
:DDD
There is other connected API issues:
https://github.com/lavab/api/issues/127
https://github.com/lavab/api/issues/122

**Comment by mlooz** [comment]
Good to know the email resurfaced! :-)
This makes https://github.com/lavab/api/issues/129 all the more urgent, in my opinion.

**Comment by vLooz** [comment]
Strange... 
I tried to reproduce this and send mails with subject "Test" from my gmail account to my lavaboom address. 
At first it was connected to the existing "Test" thread like described before. Then I deleted the thread. 
After that I kept repeating writing mails with "Test" to lavaboom. But then neither the deleted "Test" thread would be moved back to the inbox, nor the new "Test" mails would be moved to trash to be connected to the deleted old thread. The new mails just appeared in Inbox regularly, but the same time the old thread disappeared from Trash. It's gone. 
Two of the new emails had the exact same content. Could this be a hint?

**Comment by flixi** [comment]
It seems like it somehow counts the emails that I send as new inbox ones.
It also doesn'T show me the answers I put in anymore.

**Comment by pzduniak** [comment]
Fixed in lavab/api@144a1cfc971d959a2dd93fa10d22a576199cde6a

**Comment by mlooz** [comment]
@pzduniak, you fixed another issue with this commit, not the one starting the thread

**Comment by pzduniak** [comment]
The actual change was in ce4f3bb59472939c5c9485cb889baf18612e82f1, but I noticed one more issue: the thread matcher should ignore emails in trash and spam.
