### ISSUE TITLE
Some mails in Sent folder not being displayed

### ISSUE THREAD

**Issue by jrselzer** [lavab/web#556]
Two mails in my sent folder show an empty screen when I click on them.

**Comment by let4be** [comment]
This is probably related to emails post-processing,
logs from the console(email body required) would help to reproduce the issue

**Comment by jrselzer** [comment]
Sorry, where do I find the console logs? I have a portable Firefox running on a common Win 7 installation.

**Comment by let4be** [comment]
refresh the page with some empty label in the url first,
then just press F12 and clear the console logs
then select Sent label and select empty email
there should be some debug information in console regarding error + email bodies that parser was unable to process

**Comment by jrselzer** [comment]
"Initialize loader..." Sent:6:39
"loader: loading application" "utils" undefined Sent:6:1891
"loader.progress" 10 "Loading Lavaboom utils(1)..." Sent:6:2253
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create utils-vendor-8d127df912f56806b07b47b428837146829a6e90.js:1:3481
"loader loaded '/js/utils-vendor-8d127df912f56806b07b47b428837146829a6e90.js'" load { target: <script>, isTrusted: true, eventPhase: 0, bubbles: false, cancelable: true, defaultPrevented: false, timeStamp: 0, originalTarget: <script>, explicitOriginalTarget: <script>, NONE: 0, CAPTURING_PHASE: 1 } Sent:6:4449
"loader.progress" 20 "Loading Lavaboom utils(2)..." Sent:6:2253
"loader loaded '/js/utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js'" load { target: <script>, isTrusted: true, eventPhase: 0, bubbles: false, cancelable: true, defaultPrevented: false, timeStamp: 0, originalTarget: <script>, explicitOriginalTarget: <script>, NONE: 0, CAPTURING_PHASE: 1 } Sent:6:4449
"loader.progress" 30 "Checking..." Sent:6:2253
"loader: initializing application" "utils" undefined Sent:6:1177
"loader: calling rootScope.initializeApplication()" Sent:6:1349
"Calling accounts.get" Array [ "me" ] "..." utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2038
"accounts.get: " Object { body: Object, headers: Object, id: "1", status: 200, type: "response" } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2280
"checker: accounts.get(me) success" Object { body: Object, headers: Object, id: "1", status: 200, type: "response" } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:261:611
"Calling keys.get" Array [ "myaddress@lavaboom.com" ] "..." utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2038
"keys.get: " Object { body: Object, headers: Object, id: "2", status: 200, type: "response" } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2280
"checker: keys.get success" Object { body: Object, headers: Object, id: "2", status: 200, type: "response" } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:261:750
"loader: loading application" "AppLavaboom" Object { noDelay: true } Sent:6:1891
"loader.progress" 30 "Loading system libraries..." Sent:6:2253
"loader: initialized application" "utils" "with result" undefined Sent:6:1458
"loader loaded '/js/appLavaboom-vendor-c5fb03fd61985bbb85bbd9e36de182a39728d62f.js'" load { target: <script>, isTrusted: true, eventPhase: 0, bubbles: false, cancelable: true, defaultPrevented: false, timeStamp: 0, originalTarget: <script>, explicitOriginalTarget: <script>, NONE: 0, CAPTURING_PHASE: 1 } Sent:6:4449
"loader.progress" 35 "Loading openpgp.js..." Sent:6:2253
"loader loaded '/vendor/openpgp.js'" load { target: <script>, isTrusted: true, eventPhase: 0, bubbles: false, cancelable: true, defaultPrevented: false, timeStamp: 0, originalTarget: <script>, explicitOriginalTarget: <script>, NONE: 0, CAPTURING_PHASE: 1 } Sent:6:4449
"loader.progress" 40 "Loading templates..." Sent:6:2253
"loader loaded '/js/templates-c1e1b066a5131b1bff135836b1793119f1e06b66.js'" load { target: <script>, isTrusted: true, eventPhase: 0, bubbles: false, cancelable: true, defaultPrevented: false, timeStamp: 0, originalTarget: <script>, explicitOriginalTarget: <script>, NONE: 0, CAPTURING_PHASE: 1 } Sent:6:4449
"loader.progress" 45 "Loading Lavaboom..." Sent:6:2253
"loader loaded '/js/appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js'" load { target: <script>, isTrusted: true, eventPhase: 0, bubbles: false, cancelable: true, defaultPrevented: false, timeStamp: 0, originalTarget: <script>, explicitOriginalTarget: <script>, NONE: 0, CAPTURING_PHASE: 1 } Sent:6:4449
"loader.progress" 50 "Please wait..." Sent:6:2253
"creating state " "empty" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "empty.popup" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "modal" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "modal.popup" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.inbox" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.inbox.label" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.inbox.label.popup" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.inbox.label.popup.compose" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.inbox.label.popup.hotkeys" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.inbox.label.popup.download" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.contacts" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.contacts.popup" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.contacts.popup.compose" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.contacts.popup.hotkeys" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.contacts.popup.download" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.contacts.profile" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.contacts.profile.popup" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.contacts.profile.popup.compose" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.contacts.profile.popup.hotkeys" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.contacts.profile.popup.download" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.popup" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.popup.compose" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.popup.hotkeys" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.popup.download" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.general" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.general.popup" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.general.popup.compose" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.general.popup.hotkeys" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.general.popup.download" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.profile" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.profile.popup" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.profile.popup.compose" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.profile.popup.hotkeys" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.profile.popup.download" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.security" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.security.popup" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.security.popup.compose" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.security.popup.hotkeys" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.security.popup.download" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.plan" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.plan.popup" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.plan.popup.compose" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.plan.popup.hotkeys" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"creating state " "main.settings.plan.popup.download" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6375:2159
"construct Cache instance name: " "crypto cache" "options:" Object { ttl: 3600000, unfold: null, list: e/e.list() } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:301:121
"construct Cache instance name: " "default cache" "options:" Object { ttl: 60000, unfold: null, list: e/e.list() } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:301:121
"construct Cache instance name: " "threads cache" "options:" Object { ttl: 60000, list: [54]</module.exports</p<.list(), unfold: [54]</module.exports</d.unfold() } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:301:121
"construct Cache instance name: " "emails cache" "options:" Object { ttl: 600000, unfold: [54]</module.exports</d.unfold(), list: e/e.list() } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:301:121
"loader: initializing application" "AppLavaboom" Object { noDelay: true } Sent:6:1177
"loader: calling rootScope.initializeApplication()" Sent:6:1349
"i18n index loaded" Object { TRANSLATIONS: Object } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:345:367
"loader.progress" 51 "Initializing openpgp.js..." Sent:6:2253
"Initialize openpgp in multi-threading mode, workers count: " 4 utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:317:3965
"loader.progress" 56 "Authenticating..." Sent:6:2253
"Calling accounts.get" Array [ "me" ] "..." utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2038
"accounts.get: " Object { body: Object, headers: Object, id: "3", status: 200, type: "response" } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2280
"Calling keys.list" Array [ "myaddress" ] "..." utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2038
"keys.list: " Object { body: Object, headers: Object, id: "4", status: 200, type: "response" } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2280
"Key with fingerprint '19a7810c7930ad947f95dddb66d18ad40d50ed02' already imported..." utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:349:1853
"skip private key import - already existing" "19a7810c7930ad947f95dddb66d18ad40d50ed02" utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:321:658
"skip public key import - already existing" "19a7810c7930ad947f95dddb66d18ad40d50ed02" utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:321:1141
"Calling keys.get" Array [ "myaddress@lavaboom.com" ] "..." utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2038
"keys.get: " Object { body: Object, headers: Object, id: "5", status: 200, type: "response" } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2280
"loader.progress" 61 "Loading emails & contacts..." Sent:6:2253
"Calling contacts.list" Array [  ] "..." utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2038
"info" Object { body: Object, headers: Object, id: "6", status: 200, type: "response" } appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6571:5335
"calling original, cache key" "getLabels." utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:309:433
"Calling labels.list" Array [  ] "..." utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2038
"contacts.list: " Object { body: Object, headers: Object, id: "7", status: 200, type: "response" } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2280
"labels.list: " Object { body: Object, headers: Object, id: "8", status: 200, type: "response" } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2280
"Contact.fromEnvelope data" Object { data: Object, state: "ok", majorVersion: undefined, minorVersion: undefined } appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6507:2799
"contact" Object { id: "PhAiUo5z06WLwzWhXIJc", dateCreated: "2015-05-04T07:09:19.961999893Z", dateModified: "2015-05-04T07:09:19.961999893Z", isDecrypted: true, name: "$hidden", privateEmails: Array[0], businessEmails: Array[0], hiddenEmail: Object, isCustomName: a/this.isCustomName(), getFullName: a/this.getFullName(), 7 weitere… } appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6507:3014
"Contact.fromEnvelope data" Object { data: Object, state: "ok", majorVersion: undefined, minorVersion: undefined } appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6507:2799
"contact" Object { id: "Mpz5Utdo539cXdnkrtMN", dateCreated: "2015-05-04T11:36:55.598999977Z", dateModified: "2015-05-04T11:36:55.598999977Z", isDecrypted: true, name: "Jochim Selzer", firstName: "Firstname", lastName: "Lastname", companyName: "Companyname", privateEmails: Array[1], businessEmails: Array[1], 10 weitere… } appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6507:3014
"hotkeys.addGlobalHotkeys()" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6567:3130
"loader: initialized application" "AppLavaboom" "with result" Object { lbDone: "Done!" } Sent:6:1458
"loader.progress" 100 "Done!" Sent:6:2253
"CtrlInbox loaded" "xjsBCuwAmDJxTfsrc6ZM" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:317
"proxy requestList" "Sent" 0 15 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2477
"calling original, cache key" "requestList.Sent:0:15" utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:309:433
"loading emails list" "xjsBCuwAmDJxTfsrc6ZM" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6403:194
"calling original, cache key" "getThreadById.xjsBCuwAmDJxTfsrc6ZM" utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:309:433
"Calling threads.get" Array [ "xjsBCuwAmDJxTfsrc6ZM" ] "..." utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2038
"calling original, cache key" "getEmailsByThreadId.xjsBCuwAmDJxTfsrc6ZM" utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:309:433
"Calling emails.list" Array [ Object ] "..." utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2038
"Calling threads.list" Array [ Object ] "..." utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2038
"threads.get: " Object { body: Object, headers: Object, id: "9", status: 200, type: "response" } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2280
"emails.list: " Object { body: Object, headers: Object, id: "10", status: 200, type: "response" } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2280
"threads.list: " Object { body: Object, headers: Object, id: "11", status: 200, type: "response" } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2280
"thread manifest" "{"version":"1.0.0","headers":{"from":"myaddress@lavaboom.com","to":["targetaddress@lavaboom.com"],"subject":"3rd feedback"},"parts":[{"id":"body","hash":"43b410e4ea2deda64eb8ad1bd0d32436f48a11e9f2c321aad42ea67f62808d16","content_type":"text/html"}]}" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6531:1367
"inbox-threads" "Sent" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:2723
"proxy requestList" "Sent" 0 15 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2477
"calling original, cache key" "requestList.Sent:0:15" utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:309:433
"proxy requestList" "Sent" 0 15 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2477
"calling original, cache key" "requestList.Sent:0:15" utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:309:433
"wait $scope.isThreads" false appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6403:1828
"thread manifest" "{"version":"1.0.0","headers":{"from":"myaddress@lavaboom.com","to":["targetaddress@lavaboom.com"],"subject":"First feedback"},"parts":[{"id":"body","hash":"31cd113fdf156a1c20ce3ae36a75c437e9293484a8d0c0dc30899e9f63102f14","content_type":"text/html"}]}" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6531:1367
"thread manifest" "{"version":"1.0.0","headers":{"from":"myaddress@lavaboom.com","to":["targetaddress@lavaboom.com"],"subject":"3rd feedback"},"parts":[{"id":"body","hash":"43b410e4ea2deda64eb8ad1bd0d32436f48a11e9f2c321aad42ea67f62808d16","content_type":"text/html"}]}" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6531:1367
"thread manifest" "{"version":"1.0.0","headers":{"from":"Myname \u003cmyaddress@lavaboom.com\u003e","subject":"first","to":"\u003cmyname@privatemailaddres.de\u003e"},"parts":[{"hash":"3814ecc8b95dca12d45a455d415df001bbe16d15677d842f394c2497ce489163","size":319,"id":"body","content_type":"text/html"}]}" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6531:1367
"thread manifest" "{"version":"1.0.0","headers":{"from":"myaddress@lavaboom.com","to":["targetaddress@lavaboom.com"],"subject":"2nd feedback"},"parts":[{"id":"body","hash":"c73d945790604dd3c9993a9910f9339d852764719201d8515fd86a16503a9134","content_type":"text/html"}]}" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6531:1367
"requestList cache value is" Object { list: Array[4], isEnd: true } appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2791
"requestList cache value is" Object { list: Array[4], isEnd: true } appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2791
"inbox-threads" "Sent" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:2723
"proxy requestList" "Sent" 0 15 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2477
"requestList cache value is" Object { list: Array[4], isEnd: true } appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2791
"inbox-threads" "Sent" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:2723
"proxy requestList" "Sent" 0 15 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2477
"requestList cache value is" Object { list: Array[4], isEnd: true } appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2791
"inbox-threads selectedIndex 1: " -1 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:3259
"inbox-threads selectedIndex 2: " -1 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:3587
"scroll()" false false appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:4578
"proxy requestList" "Sent" 4 15 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2477
"requestList cache value is" Object { list: Array[4], isEnd: true } appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2791
"inbox-threads selectedIndex 1: " 1 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:3259
"inbox-threads selectedIndex 2: " 1 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:3587
"scroll()" false false appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:4578
"proxy requestList" "Sent" 4 15 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2477
"requestList cache value is" Object { list: Array[4], isEnd: true } appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2791
"inbox-threads" "Sent" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:2723
"proxy requestList" "Sent" 0 19 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2477
"requestList cache value is" Object { list: Array[4], isEnd: true } appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2791
"inbox-threads" "Sent" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:2723
"proxy requestList" "Sent" 0 19 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2477
"requestList cache value is" Object { list: Array[4], isEnd: true } appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2791
"requestList cache value is" Object { list: Array[4], isEnd: true } appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:2791
"inbox-threads selectedIndex 1: " 1 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:3259
"inbox-threads selectedIndex 2: " 1 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:3587
"inbox-threads selectedIndex 1: " 1 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:3259
"inbox-threads selectedIndex 2: " 1 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:3587
"inbox-threads selectedIndex 1: " 1 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:3259
"inbox-threads selectedIndex 2: " 1 appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:3587
"setThreadReadStatus decorator for threadId" "xjsBCuwAmDJxTfsrc6ZM" "labelName" "Sent" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:5408

**Comment by jrselzer** [comment]
When I click from a readable mail to an empty mail, this happens:

"hotkeys.clearHotkeys()" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6567:952
"hotkeys.addGlobalHotkeys()" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6567:3130
"CtrlThreadList $stateChangeStart" "main.inbox.label" Object { labelName: "Sent", threadId: "xjsBCuwAmDJxTfsrc6ZM" } appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:4190
"loading emails list" "xjsBCuwAmDJxTfsrc6ZM" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6403:194
"wait $scope.isThreads" true appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6403:1828
"setThreadReadStatus decorator for threadId" "xjsBCuwAmDJxTfsrc6ZM" "labelName" "Sent" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:5408

Another example

"setThreadReadStatus decorator for threadId" "xjsBCuwAmDJxTfsrc6ZM" "labelName" "Sent" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:5408
"hotkeys.clearHotkeys()" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6567:952
"hotkeys.addGlobalHotkeys()" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6567:3130
"CtrlThreadList $stateChangeStart" "main.inbox.label" Object { labelName: "Sent", threadId: "rUwzPnnL4xcXlDlIgTrW" } appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6411:4190
"loading emails list" "rUwzPnnL4xcXlDlIgTrW" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6403:194
"calling original, cache key" "getEmailsByThreadId.rUwzPnnL4xcXlDlIgTrW" utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:309:433
"Calling emails.list" Array [ Object ] "..." utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2038
"wait $scope.isThreads" true appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6403:1828
"emails.list: " Object { body: Object, headers: Object, id: "20", status: 200, type: "response" } utils-1b5767beeee121aaddd771e9ffa38c4498026eda.js:277:2280
"setThreadReadStatus decorator for threadId" "rUwzPnnL4xcXlDlIgTrW" "labelName" "Sent" appLavaboom-9d1ec7b698588662ab4120308e6c93739e06cf0b.js:6459:5408

**Comment by let4be** [comment]
the log should contain email bodies, are you sure this is the whole output?

**Comment by jrselzer** [comment]
Quite sure. I clicked "mark all" and copied it to clipboard.

**Comment by let4be** [comment]
Okay, I just tracked this down to be an API problem
opening a separate issue for this: https://github.com/lavab/api/issues/130
