### ISSUE TITLE
Userreport: Someone didn't get past initialization failed when he first logged in

### ISSUE THREAD

**Issue by flixi** [lavab/web#558]
Registration was completed successfully, but he couldn't access his mailbox.

OS: Win 8.1
Browser: Chrome and Firefox
Sync: Enabled.

**Comment by pzduniak** [comment]
I constantly experienced it. Some error with .startsWith not defined.

**Comment by let4be** [comment]
What steps should be taken to reproduce this?... I'm constantly creating new accounts for tests and haven't seen this so far

**Comment by flixi** [comment]
I wasn't able to get any logs.
I'm also not sure how to reproduce this.

**Comment by let4be** [comment]
Again, i'm trying to finish with the most annoying bugs today and then moving straight to
https://github.com/lavab/web/issues/279
without proper logs any more or less complex issue is a mystery.

**Comment by flixi** [comment]
But if @pzduniak gets the same result he might be able to shed some light on this.

**Comment by let4be** [comment]
Can this be closed? does it still happen after recent master update?
