### ISSUE TITLE
Compose/Select Recipient: Sort offered Recipients addresses encryption ability.

### ISSUE THREAD

**Issue by vLooz** [lavab/web#563]
Status Quo:
When I type in a name in the recipient field, e.g. "Moritz", I get a bunch of addresses, both secure and unsecure. 

![bildschirmfoto 2015-05-06 um 14 50 22](https://cloud.githubusercontent.com/assets/11177812/7493235/4155563e-f3ff-11e4-954b-78599730fcc7.png)
 
How I would like it to be:
If I type Moritz, show me Moritz’ secure Lavabooms address(es) on the top, after that the insecure.

**Comment by vLooz** [comment]
nice! :-)

**Comment by let4be** [comment]
I thought it's an super easy fix but then suddenly found an issue in how keys are being stored(lavaboom public keys and manually imported public key), now this should be unified
