### ISSUE TITLE
Settings/Sections: change Icon color to #9D9FA3

### ISSUE THREAD

**Issue by vLooz** [lavab/web#565]
![settings please change line colors](https://cloud.githubusercontent.com/assets/11177812/7493347/4f4417c0-f400-11e4-8ee6-969ef27aaef2.png)

**Comment by piggyslasher** [comment]
@vLooz - so its slightly darker than the text color - yes?

**Comment by vLooz** [comment]
actually the icon's are lighter than the text color

**Comment by vLooz** [comment]
![bildschirmfoto 2015-06-05 um 12 39 39](https://cloud.githubusercontent.com/assets/11177812/8004452/38a2e84c-0b80-11e5-8889-fe9ec5d739af.png)

**Comment by piggyslasher** [comment]
in develop
