### ISSUE TITLE
Contacts/Edit: Add & Delete circle size difference

### ISSUE THREAD

**Issue by vLooz** [lavab/web#568]
![bildschirmfoto 2015-05-06 um 16 54 52](https://cloud.githubusercontent.com/assets/11177812/7495868/e7a2d5fa-f410-11e4-922a-2ae4fa295285.png)

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/7953151/8891d61c-09f3-11e5-930b-b02d14984727.png)
