### ISSUE TITLE
compose URL breaking page load

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#577]
I was toggling various settings in compose screen and had a `url` in the location bar like so
```
http://127.0.0.1:5000/settings/general/compose?isSkipWarning=on&subject=&body=%3Csection+class%3D%22body+ng-binding%22%3E%3Cbr%2F%3E%3C%2Fsection%3E%3Cfooter+class%3D%22signature+ng-binding%22%3E%3Cp+class%3D%22text-center%22%3E%3Ca+href%3D%22http%3A%2F%2Flavaboom.com%22+target%3D%22_blank%22%3E%3Cstrong%3ESent+with+Lavaboom+-+your+secure+email+provider.%3C%2Fstrong%3E%3Cbr%2F%3EGet+your+own+address+at+to+lavaboom.com%3C%2Fa%3E%3C%2Fp%3E%3C%2Ffooter%3E
```

Which resulted in this error in `console.log`:

    Error: $location:nobase
    $location in HTML5 mode requires a tag to be present!

https://docs.angularjs.org/error/$location/nobase

Maybe not priority but maybe you know whats wrong @let4be

**Comment by let4be** [comment]
What? How did you ever manage to get such url @piggyslasher 
What email body is doing in location? o_O

**Comment by let4be** [comment]
There is only one reasonable explanation to this - some temporary issue with live-reload || code change you made

I'm closing this for now, if this appears in real-world application usage open another issue with proper description and logs.
