### ISSUE TITLE
Key backup format

### ISSUE THREAD

**Issue by let4be** [lavab/web#579]
we have the following internal key backup format in play:
`{
    "readme": "https://lavaboom.com/placeholder/help/backup-file",
    "body": {
        "key_pairs": {
            "name <name@lavaboom.com>": {
                "prv": "",
                "pub": ""
            }
        },
        "exported": "2015-05-07 11:43:00 +0300"
    },
    "bodyHash": "0d02fa36d1a2a7b28af58b085282e6c366f32220a51b114bdda696567e3d75265413ca2040297f7c1ec0cbfc187b76cea8c7f5235c33d2db3afdf8c1cdcf704d"
}`

there is also readme as you see, what should we put there?

**Comment by let4be** [comment]
@andreis @flixi ?

**Comment by andreis** [comment]
> https://lavaboom.com/help/keyring-backup

**Comment by let4be** [comment]
okay will update
