### ISSUE TITLE
Ninja attachments

### ISSUE THREAD

**Issue by let4be** [lavab/web#581]
Attachments details aren't visible,
![image](https://cloud.githubusercontent.com/assets/4147061/7512269/86a8cff8-f4b4-11e4-9fb2-5d51d1f0a7dc.png)

the gray text appears only mouse over
![image](https://cloud.githubusercontent.com/assets/4147061/7512277/95bcb6e4-f4b4-11e4-9aa6-25181847a4f9.png)

Where? develop
Win 7, Chrome Version 42.0.2311.135 m

**Comment by piggyslasher** [comment]
this was fixed ages sorry. sorry I didn't close it. attachments look even better now.

**Comment by piggyslasher** [comment]
will close after I push todays changes.

**Comment by piggyslasher** [comment]
closing for #788
