### ISSUE TITLE
Notification causes annoying content shifting

### ISSUE THREAD

**Issue by let4be** [lavab/web#582]
notification:
![image](https://cloud.githubusercontent.com/assets/4147061/7512391/3fa3605e-f4b5-11e4-80f3-b503ceea36db.png)

no notification:
![image](https://cloud.githubusercontent.com/assets/4147061/7512396/503471c4-f4b5-11e4-93b1-09d5491242e1.png)

Content is being shifted by height on the notification size
What is expected? notification displayed in a way that does not cause other content movement

Win 7, Chrome 42.0.2311.135 m

**Comment by let4be** [comment]
This is indeed is super annoying thing, please fix as soon as possible @piggyslasher

**Comment by piggyslasher** [comment]
sorry. am on it. i am restyling self dismissing notifications.

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/7593858/9ab133b4-f90f-11e4-8ec3-f294ab719d4c.png)

**Comment by piggyslasher** [comment]
Currently I've removed the 'jump' for all notifications and self dismissing ones are like this.
