### ISSUE TITLE
Trash icon in email

### ISSUE THREAD

**Issue by let4be** [lavab/web#583]
![image](https://cloud.githubusercontent.com/assets/4147061/7512875/a7a5750e-f4b8-11e4-8d7c-004eee1475f3.png)

hm... What is it supposed to do?
afaik we don't support manipulations over individual emails

**Comment by let4be** [comment]
Ok, regarding https://github.com/lavab/web/issues/370#issuecomment-95609266
we support deletion of individual emails from API side

But I'm still not sure should it be implemented, there are some consequences:
- where deleted email goes? We display only threads in the trash and if we delete emails individually will it mean thread will sit both in Trash and Inbox? 
- we can delete email without ability to restore but this goes against UX I guess.

This thing is not so simple as it might seem from the first sight - I'm currently deleting this button until we have a meaningful resolution to mentioned problems.

**Comment by let4be** [comment]
@andreis @pzduniak need your input on this

**Comment by let4be** [comment]
Currently button is deleted

**Comment by andreis** [comment]
Desired functionality is to be able to delete individual emails, but for now let's not offer the users this option.
