### ISSUE TITLE
Encrypted emails from external sources are not decrypted yet

### ISSUE THREAD

**Issue by mlooz** [lavab/web#584]
Steps to reproduce:
1. Download own public key
2. Encrypt test message with gpg: 
gpg --encrypt --recipient tester@lavaboom.com --armor | mail -s "Testsubject" tester@lavaboom.com
3. Open mail in Lavaboom

What happens:
Encrypted PGP block is shown

What should happen:
When recognizing a PGP block, an attempt is made to decrypt it with the available private keys.

**Comment by let4be** [comment]
Checking similar code anyway, enhancement is coming soon ;)

**Comment by let4be** [comment]
Currently just in develop

**Comment by mlooz** [comment]
Does not work for me on da0317ca3bfd4e9ead2684ee0e30fdc856325c2f (current develop).
Log is at https://gist.github.com/mlooz/f7c09d5930f697de0076

**Comment by mlooz** [comment]
Does this work for you? I went through the code with a debugger and the pgpRegex never catches because each line is evaluated individually.

**Comment by let4be** [comment]
This should be in the master and it works for me
The thing is openpgp envelope should be sent as-is without any html garbage between lines

**Comment by let4be** [comment]
@mlooz your log doesn't contain any useful information, could you please post email body?
There is download original email link now ;)

**Comment by mlooz** [comment]
Sure, I've tried plaintext emails and HTML emails.

Plaintext: https://gist.github.com/mlooz/1220c4986ee2e2231b47
HTML: https://gist.github.com/mlooz/c17ccff988b7258839cd

GPG and Enigmail create plaintext emails by default. However, on those the styling isn't even called, email addresses remain unlinked and also the GPG code is not called. Probably should open a separate issue for that.

**Comment by let4be** [comment]
@mlooz please try again :)

**Comment by let4be** [comment]
see also: https://github.com/lavab/mailer/issues/44
it may prevents delivery of such emails
