### ISSUE TITLE
External emails with empty subject don't arrive

### ISSUE THREAD

**Issue by mlooz** [lavab/web#585]
Steps to reproduce:
Send email from external account to lavaboom account with empty subject.

What should happen:
Email shows up in inbox, inbox counter increases, etc.

What happens:
Sender gets warning message that message 1YqJwo-0002Fe-N6 has not been delivered for three hours

**Comment by let4be** [comment]
Same here, reopen this in mailer

**Comment by paulhugel** [comment]
RE Bug #585 
tested Lavaboom 0.3.0
Safari 8.06 (10600.6.3)
OSX 10.10.3 Yosemite

and no errors reported in console mail received as expected
console web inspecter shown no warnings or errors
![test no subject entered](https://cloud.githubusercontent.com/assets/6466830/7616330/4498b8fa-f93f-11e4-8b9a-d5152795285b.png)



[Log] got server event  (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6546)
Object

[Log] event thread null (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6546)
[Log] calling original, cache key getThreadById.kOp6qc8FlA0TGsbafWbr (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 309)
[Log] Calling threads.get ["kOp6qc8FlA0TGsbafWbr"] ... (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 277)
[Log] threads.get:   (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 277)
Object

[Log] inbox-threads Inbox (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6462)
[Log] proxy requestList Inbox 0 22 (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6546)
[Log] requestList cache value is  (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6546)
Object

[Log] calling original, cache key getEmailsByThreadId.kOp6qc8FlA0TGsbafWbr (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 309)
[Log] Calling emails.list [ (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 277)
Object
] ...
[Log] inbox-threads selectedIndex 1:  -1 (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6462)
[Log] inbox-threads selectedIndex 2:  -1 (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6462)
[Log] emails.list:   (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 277)
Object

[Log] thread manifest {"version":"1.0.0","headers":{"cc":"","from":"Paul Garrett Hugel \u003ckiwikiu@riseup.net\u003e","to":"\u003cpaulhugel@lavaboom.com\u003e"},"parts":[{"hash":"9234435efa61a61dcb44ac0c2ea8f44efb714c96ea989c5b3a77dd4e62bfba47","size":873,"id":"xhfg3asz4nMFhie1R55r","content_type":"application/pgp-signature","filename":"signature.asc"},{"hash":"ca17f756bd421a11796a9a662a79eb0bb0a5ed70209e39bb5d11cd70e74fe91c","size":52,"id":"body","content_type":"text/plain"}]} (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6622)
[Log] email decoded  (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6606)
s
 {"version":"1.0.0","headers":{"cc":"","from":"Paul Garrett Hugel \u003ckiwikiu@riseup.net\u003e","to":"\u003cpaulhugel@lavaboom.com\u003e"},"parts":[{"hash":"9234435efa61a61dcb44ac0c2ea8f44efb714c96ea989c5b3a77dd4e62bfba47","size":873,"id":"xhfg3asz4nMFhie1R55r","content_type":"application/pgp-signature","filename":"signature.asc"},{"hash":"ca17f756bd421a11796a9a662a79eb0bb0a5ed70209e39bb5d11cd70e74fe91c","size":52,"id":"body","content_type":"text/plain"}]}
[Log] hotkeys.clearHotkeys() (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6666)
[Log] hotkeys.addGlobalHotkeys() (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6666)
[Log] requestListCached [ (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6490)
o
, 
o
, 
o
, 
o
, 
o
, 
o
, 
o
, 
o
]
[Log] CtrlEmailList is loading Inbox kOp6qc8FlA0TGsbafWbr (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6490)
[Log] emails has selected tid kOp6qc8FlA0TGsbafWbr (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6490)
[Log] replacing possible hidden messages... <pre>testing email sent to lava boom with no subject line</pre> (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6562)
[Log] replaced possible hidden messages... <pre>testing email sent to lava boom with no subject line</pre> (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6562)
[Log] setThreadReadStatus decorator for threadId kOp6qc8FlA0TGsbafWbr labelName Inbox (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6546)
[Log] Calling threads.get ["kOp6qc8FlA0TGsbafWbr"] ... (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 277)
[Log] threads.get:   (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 277)
Object

[Log] Calling threads.update ["kOp6qc8FlA0TGsbafWbr",  (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 277)
Object
] ...
[Log] threads.update:   (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 277)
Object

[Log] calling original, cache key getLabels. (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 309)
[Log] Calling labels.list [] ... (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 277)
[Log] labels.list:   (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 277)
Object
body: Object
headers: Object
id: "16"
status: 200
type: "response"
__proto__: Object

**Comment by let4be** [comment]
I think I know where the problem is @paulhugel, thanks for the report
Will fix this tomorrow
