### ISSUE TITLE
Empty emails again.

### ISSUE THREAD

**Issue by flixi** [lavab/web#587]
![bildschirmfoto 2015-05-07 um 14 24 13](https://cloud.githubusercontent.com/assets/707993/7515165/de962a52-f4c4-11e4-8d9b-0c365867215d.png)

Logs: https://gist.github.com/flixi/87c0550622a9ceda9582

**Comment by let4be** [comment]
Somehow email contained binary data...
I will check this in ~2 hours, need to finish with other stuff first

**Comment by let4be** [comment]
@flixi this particular email came malformed most likely, few possibilities here:
- it indeed came malfromed with unclosed tags and tons of NULL bytes in the end
- as lavaboom encrypts all email, there may be a bug on this stage that corrupted this email
- there might be a bug in openpgp.js

we somehow need to exclude this 1 by 1, to find the real cause

**Comment by let4be** [comment]
To display emails in secure way we perform validation over each email, the validation rules are more strict than validation rules of a typical browser.

  So if email was displayed without any validation in a separate browser window it _probably could_ have no visible issues, but when it comes to lavaboom and displaying emails _inside lavaboom's page_ we simply can't allow such freedom because we need to protect our users.

  Some percent of emails always will be blank/displayed with serious issues, because those emails simply do not match our rules of correctness and security.

**Comment by let4be** [comment]
Probably we should offer user a separate, more secure way of gathering access to emails - simply allow user to download complete raw html code of email

It will be opened outside of lavaboom domain so user will stay safe(without risk of losing privacy of his decrypted private keys or some other sensitive information) while being able to access such kind of email.

What do you think @andreis @flixi

**Comment by andreis** [comment]
Similar to "View Source" in email clients. Yep

**Comment by let4be** [comment]
Okay, going to implement this today

**Comment by andreis** [comment]
:+1:

**Comment by let4be** [comment]
I also want to add 
"Aw, Snap!"
"Something went wrong..." with appropriate icon and instruction for a user what to do if we can't display email internally inside lavaboom interface

Just like it implemented in chrome when page crashes ;)

What do you think, @andreis ?

**Comment by andreis** [comment]
:+1:

**Comment by let4be** [comment]
So from now on we shouldn't have any empty emails, but at least a short note to the user about what happened and what to do ;)

**Comment by mlooz** [comment]
I still get empty emails in the Sent-Folder, with no note or download button.
Should this be a separate issue?
Where: 97397eb915835b2c9a60a09a17f9bfcac89953ca
Browser: Firefox, Linux
Log:

    "hotkeys.clearHotkeys()" appLavaboom.js:12541:2
    "hotkeys.addGlobalHotkeys()" appLavaboom.js:12666:2
    "requestListCached" Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 10 weitere… ] appLavaboom.js:8237:2
    "CtrlEmailList is loading" "Sent" "K9QVkmCg3fgCC4jhsUze" appLavaboom.js:8242:1
    "emails has selected tid" "K9QVkmCg3fgCC4jhsUze" appLavaboom.js:8300:2
    "setThreadReadStatus decorator for threadId" "K9QVkmCg3fgCC4jhsUze" "labelName" "Sent" appLavaboom.js:9786:10

**Comment by let4be** [comment]
It's known issue caused by API/Mailer bug, nothing to do here just yet
