### ISSUE TITLE
Starred-Feature

### ISSUE THREAD

**Issue by vLooz** [lavab/web#594]
Status Quo:
When I star a mail, a copy appears in "starred" and the original moves to the top of my inbox.

What I'd like better:
The starred mail in inbox stays in the chronological order instead of moving to the top. 
From my pov, there is no need for a starred collection in the top of inbox, because thats what the actual "starred" folder is for.

**Comment by let4be** [comment]
This caused by api and how it implements sorting, need @pzduniak asap
