### ISSUE TITLE
Trash: Change "Empty Trash" Icon + Label

### ISSUE THREAD

**Issue by vLooz** [lavab/web#595]
Status Quo: To delete a mail from Trash, you hit the Trash icon - overlay label "Send to Trash".
This is a bit confusing, because the mail already is in Trash.

Better: Exchange the "Trash Icon" with the "Empty Trash" Icon and change the Label from "Send to Trash" to "Delete permanently"

![bildschirmfoto 2015-05-08 um 13 31 57](https://cloud.githubusercontent.com/assets/11177812/7535537/9ff95356-f586-11e4-804b-5b45f31bed00.png)

**Comment by piggyslasher** [comment]
ok so change tooltip in spam/trash to delete permanently.

**Comment by vLooz** [comment]
And change the icon please :-)
