### ISSUE TITLE
Private keys persistance and display

### ISSUE THREAD

**Issue by vLooz** [lavab/web#604]
background:
I just helped a friend of mine to Sign up on my browser on Safari. It has been a while, that I witnessed a complete SignUp process and ran into several interesting bugs.
I use my Lavaboom account via Safari. I have „private computer“ checkmarked and use KeySync.

SignUp-Process:
I logged out and went to „SignUp" to make her an account. I did NOT check the „this is a private computer“. She went through the process and Andrei generated a Token for her.

1a: In the Attention screen before PW, there is a „to“ missing. 
1b: The font was very thin and hardly readable on my retina. It has to be much thicker.
Issue: https://github.com/lavab/web/issues/605

Then she hit „Generate Keys“.

2: Key Generation took ages (about 5mins?) Andrei told me, that this is a Safari library related issue. Until we fix this, we need to advise the user to either use another browser (e.g. Chrome) or tell her, that it could take about 5mins.
Issue: https://github.com/lavab/web/issues/606

She got into her Inbox and opened the Compose screen.

3: When she typed in ‚felix.vlooz' in the "to“ field, it would be auto-completed to ‚felix.vlooz@lavaboom.com‘. Imo this should not happen. It gives you a weird feeling that your contacts aren’t save after all.
Issue: https://github.com/lavab/web/issues/607

Then she went to ‚Settings/General‘ and changed some settings there.

4: Every time, when she did change something, the whole form would be pushed down by the blue info header. Very annoying. The Info header is nice, but it should go over the form without moving it.
Issue: https://github.com/lavab/web/issues/608

Then she went to 'Settings/Keys‘ and there was a big surprise:

5: My(!) KeyPair was there, too. It was encrypted, but still…
I logged her out and logged myself in. I went to 'Settings/Keys‘ and I also had her encrypted KeyPair there. How can this be? 
Issue: https://github.com/lavab/web/issues/609

6: I then wanted to delete her KeyPair from my Key section, but I could not delete only hers. If a user isn't aware of (or doesn't fully trust) the fact, that his KeyPair is synced back via LB sync, he would be afraid to loose everything when deleting all keys. 
Issue: https://github.com/lavab/web/issues/610

7: Another bug. I could not backup my KeyPair from settings/keys.
Issue: https://github.com/lavab/web/issues/611

**Comment by let4be** [comment]
Regarding n5 - you used the same browser for two accounts,
we always store private keys in *encrypted* from in local storage(persistance)
not sure what can be done here
When private key is *encrypted* it carries no risk for the user keeping in mind he used strong password(and we do some checks to ensure so)

**Comment by mlooz** [comment]
@let4be 
What would happen in the following scenario:
Alice has chosen an easy password and disables autosync for security reasons. She trusts Bob.
Bob uses Alice's browser to create an account, chooses a very hard password and activates autosync. Alice's key shows up in Bob's account. Will her key then be synced to Lavaboom servers even though she never consented to it? If so, this is a huge leak! If not, it still makes users very uncomfortable.

**Comment by vLooz** [comment]
I'm aware of the fact, that they are encrypted. 
Still I think we should change the fact, that all keys in the cache are downloaded without checking which one fits the actual account. Imagine an internet café in Thailand, where a lot of Lavaboom users use one computer (e.g. Chaos Computer Club group holiday). They will get totally mad if they see all their keyPairs are in every ones account and can be downloaded from there. Especially regarding the fact, that the keypair (including private key) is encrypted only with the much weaker account passphrase. Once you get this (maybe because the user is lazy and always choosing the same PW) you can just download and decrypt his private key. Not good...

**Comment by let4be** [comment]
@mlooz her key won't be synced, if it does it's a big mistake from my side.

**Comment by let4be** [comment]
Then I'm voting for a new anonymous mode during sign in, if this mode is active keys won't be persisted   in the browser cache at all

**Comment by vLooz** [comment]
Why can't we just:
A) make the system check which user is about to log in right now and just downloads the regarding KeyPair?
B) Delete all Lavaboom synced KeyPairs from the cache, once the user has been logged out?

**Comment by let4be** [comment]
A) we don't download keys! they already resides in the browser local storage, even when user does not have Lavaboom opened! (in encrypted form)
B) we can't because Lavaboom Sync is optional, if we do this and user does not have LS/Backup he will lose access to his account

**Comment by vLooz** [comment]
A) ok, but still there could be a way to check which KeyPair is the correct one to be shown in Settings/keys, right?
B) Of course. I was talking about users, which have Lavaboom Sync.

**Comment by mlooz** [comment]
I think it is useful to distinguish between two cases. 

1. If key sync is activated, there is no need for the key to persist in the cache after logging out. Keeping it there decreases security, since it is easier to brute-force a key password than doing brute-force attempt on the login mask of lavaboom. I'm voting for suggestion B) of @vLooz 

2. If key sync is deactivated, the key needs to remain in local storage. Whether it is shown in other accounts or not does not make a difference security-wise, it is there anyway. However, it does make a big difference for the user experience.

**Comment by vLooz** [comment]
totally agreed @mlooz

**Comment by let4be** [comment]
So to sum up:
- we hide keys that do not belong to current account (security thru obscurity, huh?)
- we store encrypted private keys in session storage only if Lavaboom Sync is enabled and they will be automatically deleted as soon as user closed Lavaboom tab

**Comment by vLooz** [comment]
Sounds good @let4be. What do you guys think about this @andreis @pzduniak ?

**Comment by mlooz** [comment]
Well @let4be , you are right that hiding persistent keys from other accounts does not increase the security, since physical access gives you everything. However, I wouldn't call it security by obscurity, but a usability issue instead. By analogy, there is no doubt I could read my roommate's physical email if I really wanted to, but I still don't want it on my desk every morning.

**Comment by let4be** [comment]
you are right @mlooz, good analogy ;)

**Comment by andreis** [comment]
@vLooz Nothing to add to what Sergey said. :+1:

**Comment by let4be** [comment]
By the way all this magic with wiping private keys from local storage keyring as soon as keyring was synced via Lavaboom Sync seems to be error prone, the little mistake here(due to bug for example) and user loses his private key

No backup and bye, bye...

**Comment by let4be** [comment]
If we are going to stick with this I think we need to offer user make a backup as soon as he tried to disable Lavaboom Sync

**Comment by vLooz** [comment]
Thats a good idea. We could merge the keySync and BackUp screens during SignUp, sothat the user only has the choice between KeySync (recommended) or making a BackUp.

**Comment by let4be** [comment]
I like this, let's do so
Having _no_ Lavaboom Sync and _no_ key backup will result in account loss.

**Comment by andreis** [comment]
I use Lavaboom Sync and still like to backup. It's not a good idea to make this an exclusive choice.

**Comment by let4be** [comment]
it's just an initial choice @andreis 
you can easily backup in settings, here we just want to make sure you have Lavaboom Sync or key backup

**Comment by andreis** [comment]
Letting users download a backup of their keys is a well-received feature, and also showcases how the keyring feature works. If you want to avoid confusing the user, it can be something subtle, like a link. Example:

> Even if you use Lavaboom Sync, you can download [a backup of your keys](https://www.nsa.gov).

**Comment by vLooz** [comment]
The more I think about this from a UX perspective the more I think we should tune this whole topic down during sign-up and don't sell it as a choice, the user has to make. We could still leave a low-key checkmark "do not use lavaboom sync" for the super-paranoids - followed by the automatic (is that feasable?) download of the keyPair. But apart from that we don't bother the user with this choice at all. What do you think?

**Comment by andreis** [comment]
Simpler == better, so I agree. However can we have an "advanced options" type of thing with (1) yes/no to Lavaboom Sync and (2) download keyring button?

**Comment by andreis** [comment]
Also, something about the wizard format didn't feel quite right since the beginning, so the fewer steps the better. Ideally, we'd even manage to put everything in one screen.

**Comment by andreis** [comment]
We don't even need to let them choose a plan during registration, they just default to whatever type of free subscription their invitation code indicates (free/beta/supporter), and then can change the plan in the settings (we can also do the cheesy "Upgrade" visual cue that's quite common in SaaSes).

**Comment by flixi** [comment]
Alright, let's talk about the registrationn process again some time in the near future.

**Comment by andreis** [comment]
Meeting tomorrow at 15:00 unless you can't make it
