### ISSUE TITLE
Visual defects in SignUp page

### ISSUE THREAD

**Issue by vLooz** [lavab/web#605]
In the Attention screen before PW, there is a „to“ missing. 

The font was very thin and hardly readable on my retina. It has to be much thicker.

**Comment by piggyslasher** [comment]
is this all over the login screen or just the attention screen @vLooz ? we're using Roboto Light as you are using in your AI files.

**Comment by vLooz** [comment]
It's too thin all over the SignUp and LogIn screen. It's most likely my fault because it looked good on my retina in illustrator, which sadly is not the same on other screens in html :-)
Anyway if you could make all the fonts a bit thicker - at least for retina - it would improve readability big time @piggyslasher

**Comment by piggyslasher** [comment]
This has been fixed in develop. Please check. DM me on Slack if you're having trouble with your build.
