### ISSUE TITLE
SignUp: Solve safari library problem or at least warn the user/recommend another browser

### ISSUE THREAD

**Issue by vLooz** [lavab/web#606]
Key Generation during SignUp on my MacBook Pro with Safari took ages (about 5mins?) Andrei told me, that this is a Safari library related issue. Until we fix this, we need to advise the user to either use another browser (e.g. Chrome) or tell her, that it could take about 5mins.

**Comment by let4be** [comment]
@vLooz it may have problems with proper Web Crypto support if this is the case generation will be very slow

Generally generating 4096 RSA key is very cpu expensive operation, especially if it's being performed via javascript.

I agree we need some kind of warning there

**Comment by vLooz** [comment]
I think a info text before beginning key generation would be best here. 
Something like: "dear user, key generation could take up to 5 mins because of safari issues, bla..."

**Comment by flixi** [comment]
@vLooz Check support.lavaboom.com.

**Comment by paulhugel** [comment]
Yes same issue on key generation 5 minutes on Haswell i7 MacBook Air 
There was a warning to not close browser good work guys.

**Comment by let4be** [comment]
Going to update soon(in ~2 hours), openpgp.js added support for native keygen under Safari so it must work faster.

**Comment by let4be** [comment]
Live as `0.2.17`, 
@paulhugel could someone from Safari and Macos try to register a new account? ;)

**Comment by let4be** [comment]
I've also added simple performance test that should give user a better clue about ETA
