### ISSUE TITLE
Compose: Auto-fill with contacts the user should not know

### ISSUE THREAD

**Issue by vLooz** [lavab/web#607]
background:
I helped a friend to sign up in my browser, I also use for accessing my account. 
read https://github.com/lavab/web/issues/604 for whole process

what happened:
When she opened Compose and typed in ‚felix.vlooz' in the "to“ field, it would be auto-completed to ‚felix.vlooz@lavaboom.com‘. 
Imo this should not happen. It gives you a weird feeling that your contacts aren’t save after all.

what should happen:
no auto-fill for contacts, you do not have sent an email to before or saved in contacts

**Comment by let4be** [comment]
something isn't getting cleared when you logout.
Checking this

**Comment by mlooz** [comment]
Does this also happen with non-Lavaboom contacts?
From testing so far, it appears to be standard to autocomplete everything typed in the To-field with "@lavaboom.com"

For example, if I type "bill" in the To-field of the compose window, it will autocomplete to bill@lavaboom.com and show a little blue lock, even though I've never written to him before and haven't let anyone else use my browser.

**Comment by let4be** [comment]
This is indeed standard behavior and it carries _no_ security risks as it completes only @lavaboom.com part

**Comment by vLooz** [comment]
humm... I see. From a UX pov this might be a bit confusing though, if not worrying. As a user I might wonder if my email is also 'given' via auto-fill to complete strangers, who just try combinations of my first and last name. I'd get this nagging feeling, that my data is not treated  as private as Lavaboom promised me to.
I'd prefer, if the system would not auto-fill any address, that is not in my contacts or which I have used before. @let4be

**Comment by let4be** [comment]
Hm... @andreis , @pzduniak what do you think?

**Comment by mlooz** [comment]
We cannot completely hide the information who has an account at Lavaboom while still being compliant with standard emailing protocols.
When an external user writes an email to a non-existing address, the host is supposed to return a "Mail delivery failed" email. It is thus possible to figure out which address exists and which doesn't by simply sending messages to them.

**Comment by let4be** [comment]
But we can't remove this UX feature... Dunno from my POV it's totally ok to have as it is now, it just give user a little knowledge that such recipient exists

If you don't want to publish you First and Last name - don't use it in the email address register with some kind of pseudoname

**Comment by vLooz** [comment]
I am aware of that @mlooz and instead of a real security issue, it's more a security 'feeling' issue.
The reason why I'm so persistent with those things is the fact, that to most of our users we sell the feeling of security. Those users, who lack the tech skills to check on our open source code themselves, just have to trust us, that our claims are true. And this is why it's so very important that we cause as less disturbance of this security feeling as possible.

**Comment by vLooz** [comment]
And the user already will know that the address exist in the moment, the lock turns blue ;-) @let4be

**Comment by mlooz** [comment]
Okay then, I don't mind restricting autocomplete to contacts and previously encountered emails.
Do you want to remove the "@lavaboom"-suggestion, the blue lock confirming that this account exists, or both?

**Comment by vLooz** [comment]
I'd like to remove the lavaboom auto-completion. Once the whole lavaboom address is typed in by the user, the public key will be checked and the lock switches from grey to blue. Thats fine and necessary

**Comment by andreis** [comment]
I'd rather have it as an option in the settings, *off* by default. Obviously, with some text to describe what it does and why it's not creepy.

I quite like this feature.

**Comment by let4be** [comment]
Yea, we also need "developer mode" toggle to disable all those "my eyes can't see this" features :D

**Comment by flixi** [comment]
You could theoretically start an attack via a client to find out and browse through all available email adresssses.

**Comment by let4be** [comment]
@pzduniak said he is making limits on API, not sure what is the status but this should prevent such kind of abusive behavior

**Comment by flixi** [comment]
Good, but there is a toggle screen now?

**Comment by let4be** [comment]
not currently, there is a hidden option in settings(default: off)
if you want I can add a toggle to the settings

**Comment by flixi** [comment]
Yes, please do so.
