### ISSUE TITLE
Settings/Keys: My KeyPair appears in another user Key section.

### ISSUE THREAD

**Issue by vLooz** [lavab/web#609]
What has happened:
I helped a friend signUp on my browser (Safari), which I also use for accessing my account. I unchecked 'this is my computer' during her SignUp.
See https://github.com/lavab/web/issues/604 for what has happened

When she went to Settings/Keys My(!) KeyPair was there, too. It was encrypted, but still…
I logged her out and logged myself in. I went to 'Settings/Keys‘ and I also had her encrypted KeyPair there. This is bad!

What should have happened:
She should not get my KeyPair downloaded into her system, even if it's in the browser cache. And vice versa I should have her KeyPair in my Key section.

**Comment by let4be** [comment]
This is by design behavior and it carries NO security risk

**Comment by let4be** [comment]
closing, this is perfectly covered in https://github.com/lavab/web/issues/604
