### ISSUE TITLE
Settings/Keys: keyPair backup didn't work

### ISSUE THREAD

**Issue by vLooz** [lavab/web#611]
what happened:
I could not backup my KeyPair from settings/keys. When I hit the 'backup'-button, a new empty tab was opened, but no key file was downloaded.
See https://github.com/lavab/web/issues/604 for more background

what should have happened:
The key file download should start automatically.

**Comment by let4be** [comment]
Safari bugs ^^ this is still unresolved and I can't effectively troubleshot this problem due to absense of mac and safari

There was a huge discussion here:
https://github.com/eligrey/FileSaver.js/issues/129
https://github.com/eligrey/FileSaver.js/issues/12

**Comment by let4be** [comment]
This also affects all other download actions

**Comment by let4be** [comment]
If I could I would just advice users to boycott bugged safari that doesn't following accepted standards

**Comment by vLooz** [comment]
:D humm... Many apple users would be quite upset. 
Still we can recommend to use another browser.

**Comment by let4be** [comment]
There was a workaround but need to think how to properly apply it and not break currently used download method which FileSaver.js offers

@hyzhak do you have mac to test this?

**Comment by mlooz** [comment]
I have access to an old mac. What needs to be tested?

**Comment by piggyslasher** [comment]
we cant. unless we send info to the server this is impossible for a locally generated JS file in safari. and Apple aren't gonna fix this problem very soon. maybe, never. so we should focus on informational messages.
we can say **due to security concerns we dont sent any data to the Lavaboom server**. Hence, you can either use a browser like "chome" or "firefox"

**Comment by vLooz** [comment]
The most important info for the user is that key generation might take a while on a safari browser. I think thats the main thing we need to write on a note screen. We can provide a low-key "learn more" for the tech-savvy to open a new tab with more information.

**Comment by paulhugel** [comment]
I have mac with Safari and 100Mbit down and 5bit uplink
I have Apple Remote Desktop and Parallels Window7 Ultimate

If instructed can perform  specific requested function and corresponding Console Log and if available Full Report
Would be helpful to know What System Diagnostic Report  or can capture all messages for given time during requested function action and specific System Diagnostic Report can be captured.
![osx 10 10 3](https://cloud.githubusercontent.com/assets/6466830/7597409/05a33a90-f88f-11e4-9f50-da51b9b58547.png)
![safari 8 06 macintosh](https://cloud.githubusercontent.com/assets/6466830/7597424/1eace82e-f88f-11e4-8a92-f201e43ea337.png)

**Comment by paulhugel** [comment]
Hope This does not complicate Settings/Keys: keyPair backup didn't work #611

Went to Settings-->Security--> Backup keys 
output of screen capture with developer console view (no error reported ?)

next screen capture is snipet of new tab opened after initiating backup keys
![export keys safari macintosh](https://cloud.githubusercontent.com/assets/6466830/7597887/421430ee-f892-11e4-8c02-25c712f4a7a5.png)
![safari keyring backup snipet new tab opened](https://cloud.githubusercontent.com/assets/6466830/7597909/77cca07c-f892-11e4-8432-9181816606bc.png)

**Comment by let4be** [comment]
So, after reading the whole https://github.com/eligrey/FileSaver.js/issues/12

I consider displaying a warning for each save actions for users under Safari - it has a ton of inconsistences in this area. Can't be fixed effectively.
