### ISSUE TITLE
Contacts: give star more breathing space and change color

### ISSUE THREAD

**Issue by vLooz** [lavab/web#612]
I like the star in the contact list to indicate which contact has starred addresses. 
It would be perfect, if you can adjust the styling a bit, so that it fits the styling in the contacts email address forms. 

![bildschirmfoto 2015-05-08 um 18 27 12](https://cloud.githubusercontent.com/assets/11177812/7540989/f8fcf05e-f5b1-11e4-9030-77b2dfc3305b.png)

**Comment by piggyslasher** [comment]
done. ls check on develop when i close this.

**Comment by vLooz** [comment]
Ah, and while you guys are on it, please make the star in the contacts email address form "clickable", even when it's not in edit mode. thx :-) 
@piggyslasher @let4be

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/7953452/884cdd24-09f7-11e5-9c57-d12080a6900e.png)

![image](https://cloud.githubusercontent.com/assets/1991125/7953465/bd061d8c-09f7-11e5-95db-fd01968e9e07.png)

I've used our standard gray color for the star icon @vLooz - is that the color you want? Also - @let4be we need the 'star' button to be clickable even in non-edit mode. Assigning to you.

**Comment by let4be** [comment]
going to check this
@piggyslasher when you transfer issues _please_ rename them to have _meaningful names_ matching the actual issue

**Comment by piggyslasher** [comment]
Sorry, will rename them when I re-assign.
