### ISSUE TITLE
Button primary bad UI/UX in Web-Kit/Blink engine

### ISSUE THREAD

**Issue by kalicki** [lavab/web#613]
Hey guys,

Web-Kit/Blink engine (Google Chrome, ...) has a bug in color rendering in the primary button, gets a gray instead of white, what happens is that people who have vision problems (such as color blindness) has difficulties in reading the button.

![lavaboom](https://cloud.githubusercontent.com/assets/3674885/7541587/e6e1b91a-f58c-11e4-9057-912ea5dbff08.png)

My sugestion is remove:   
-webkit-text-fill-color: #cccbd0!important;

looks like this:
![lavaboom_fix](https://cloud.githubusercontent.com/assets/3674885/7541592/ed6d38f4-f58c-11e4-9c08-a495c243f679.png)

**Comment by piggyslasher** [comment]
I'm going to increase the font weight in buttons rather than use a vendor
prefix. will let you know when to check. good call. O also saw this problem.

**Comment by kalicki** [comment]
Basically they are the same, but -webkit-text-fill-color will take precedence over color if the two have different values.

Remove -webkit-text-fill-color.
Change font-weight: 300 to 500

:+1:

**Comment by piggyslasher** [comment]
yup. we're refined all font sizing, especially for retina displays. Should be in the master soon.

**Comment by piggyslasher** [comment]
I think we should unify our font sizes. currently as the design needs this. but as the lighter font weights simply don't render well on darker backgrounds, I'm going to remove 100 and only use 300, 400, 500. ideally it would be nice to just load two weights.

**Comment by kalicki** [comment]
Actually you're right, you'd better sit down and plan with Design solutions using optimized fonts because loading more than 2 sources is pretty bad.

I've used https://github.com/caiguanhao/grunt-ziti to Grunt some time ago is quite interesting, I don't know if exists to Gulp, but he's an optimized in the sources fonts.

**Comment by piggyslasher** [comment]
will do. I want to change the font to embedded dataURI and load them in media queries. 400,500 for non-retina and 300,400 for retina. when time permits. closing for now. its on the development branch :) Thanks again for the input @kalicki

**Comment by kalicki** [comment]
Exchange at least the color, because it is not good yet

-webkit-text-fill-color: #fff;
