### ISSUE TITLE
emailBody::process not called for plaintext emails

### ISSUE THREAD

**Issue by mlooz** [lavab/web#616]
Steps to reproduce:

1. Send plaintext email to lavaboom account, for example with Mailx:
    echo "Lorem ipsum test@lavaboom.com" | mail -s "Yet another test mail" tester@lavaboom.com
2. Open email in Lavaboom.

What happens: "test@lavaboom.com" is not a clickable link.

Steps to reproduce with local version and Debugger:

2. Sign in to local version of lavaboom.
3. Open debugger, set breakpoint at src/js/apps/AppLavaboom/directives/emailBody.js:182
 
What happens: Breakpoint is only triggered for HTML emails, not plaintext emails.

Where: .com and current master.
What: Firefox and Chrome, Ubuntu 14.04.
Causes https://github.com/lavab/web/issues/584 for me.

**Comment by let4be** [comment]
Heh, known thing.

In the beginning I suppose only text/html will have all those fancy emailBody.js functionality, but it seems text/plain needs the same

Will fix this tomorrow

**Comment by mlooz** [comment]
Having clickable links in plaintext emails has no urgency whatsoever. I only opened this because the decryption of external emails is handled by emailBody.js and it seems to have problems with HTML emails.

Maybe I've misunderstood the code structure, but how does ca59ca5b642eddb5ba3ebc95e7b195661c511a26 fix #584 for you if HTML PGP blocks cannot be decrypted and the decryption routine is not called for the plaintext emails?

**Comment by let4be** [comment]
see also: https://github.com/lavab/mailer/issues/44
it may prevents delivery of such emails
