### ISSUE TITLE
lagfest from firefox

### ISSUE THREAD

**Issue by let4be** [lavab/web#622]
It seems we have performance issues on Firefox

Where? .com
Firefox 37.0.2

**Comment by let4be** [comment]
hm... cannot reproduce it anymore both on current master and develop, reopen if you find client behavior unresponsive/slow

**Comment by piggyslasher** [comment]
seems fine on local copy but .com is a little slow.

**Comment by mlooz** [comment]
Cannot reproduce either. Does someone have performance logs of the server, for example with monit?
