### ISSUE TITLE
After deleting a private key, import button disappears

### ISSUE THREAD

**Issue by pzduniak** [lavab/web#623]
https://twitter.com/subterreign/status/597072652856070145

**Comment by let4be** [comment]
The thing is there is no import private key button currently and it's not possible to delete a single key as well - so this sounds weird

I suppose someone uses an outdated Lavaboom version, cache issue?

**Comment by flixi** [comment]
Solved?

**Comment by let4be** [comment]
not sure how did he manage to get such results

**Comment by flixi** [comment]
Is the import functionaility there though?

**Comment by let4be** [comment]
Starting from 0.2.13 it's here(deployed)
but this report is older
