### ISSUE TITLE
Please report any emails that client was unable to process and show

### ISSUE THREAD

**Issue by let4be** [lavab/web#625]
Lavaboom post processes each received email in order to:
- make plain text links clickable
- make plain text and regular emails clickable (compose screen opens) and add context menus to them
- automatically decode any embedded openpgp envelopes
- make email content safe to display, stripping out any dangerous elements such as script/style to prevent possible attacks on user that could lead to private key leaks(this includes sanitizing, css styles processing)

so now(start from 0.2.11) when client fails at one of those steps there will be explanation message saying
"something went wrong, we can't display this email, bla-bla-bla"

each such email(and others too) have a download button that should allow you to download original content of this email(.html or .txt file).
Please do so and report such emails here - this will help to debug such situations and make Lavaboom better

Thank you :)

**Comment by mlooz** [comment]
This was on .com right now, version 0.2.12.
A plaintext GPG email, which was not decrypted. The email itself is a couple of days old.

-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQIMAwGSptXCCi4KAQ//XvbstI0g6MPcF4OYY9tuKtDcVDh9pjdI0Pz+jstYtLMh
TtXmv5SY7sm8r7hgaUpgSKTUS9SE6fpIySMq0bDnVd+aQjViHyvFsnPC/D8xN97k
Vzh1b8qVaIhHeK7WggxS8VYP/IlrRpsmsi7JksOvhFSZZkDkKJlTAvQ1ZhEQJZXh
1zIlOfskMmXZ0Y9MLkQiez3kkvBtdL4ZzxPyqdcTQUMREj1M2SGPSVzXcaETXQAC
2WD05FwKu6Tp/gE91PqSHTLomw37aet3dvZMCEhJ6uSjbq/7KKu5ZR8HtvVJutT3
j34hbzVXqsUrOfmeKG+xbd3QAqAXsiyFxTEbVNVhHO7Cnl0aUKz+HBXzlbSVLU9G
UYjl5F6g/vztHdqcLYbvL3mB1pPHCJ5/jR8XqO3kVtGU6R9u4K7It9+jM1qvGUzz
SmygtaXa+qr7a/Fz+TMgmOpOP2ygqlf2hJbV0ClNXwUpUrGwBFRCMkSON+x8JH3p
HJt2SYe14tiII/dd1r0NC+j4pcfBEk/N+YI+S7AAI8aTgjdByz1LC+A0rAJEtSOn
ZjbtkdipZkKiysnrTUDKg4KOZP5dZxYHQfPBrYTiJpRiz62dKe2+PedGQ46vr9PH
TdtAKN2AKQG7hoLgZmuhL/BmgH1kif4Xmcr2Lys0YNnddDiJG4Fc7N157srfBAnS
VAEHF3nLpPfdhZedVnaHSiRV+KTiyzUijr4wwyAPXy/9YqZ0YJ5zNmoWnjm53Ixs
ISShyb4k+xIlhQEssVpKdaf44BJnG958SpJNKz2AyvUt7N9ZMw==
=PmQP
-----END PGP MESSAGE-----

**Comment by flixi** [comment]
![bildschirmfoto 2015-05-11 um 17 08 48](https://cloud.githubusercontent.com/assets/707993/7568109/3ff05ed2-f801-11e4-9312-40d84a4a05cc.png)

**Comment by flixi** [comment]
blob:https://mail.lavaboom.com/ddcbb2d2-0cc0-4313-9f36-3da31ce9c2f5

**Comment by paulhugel** [comment]
blob:https://mail.lavaboom.com/f8d13760-9dbc-41af-911b-81503f6ee758
![hello lavaboom com christine from l unable to process and show 625](https://cloud.githubusercontent.com/assets/6466830/7596932/3985a68e-f88c-11e4-8d6e-9b6fea0e63b5.png)

**Comment by let4be** [comment]
This doesn't work(probably issue with downloading js-generated stuff we're currently investigating)
basically there should be .txt / .html file downloaded

**Comment by lealex9999** [comment]
Okay, I experience a "Something went wrong while displaying this email. To continue, try to open the original email or download it"
Here is screenshot 
![bug](http://i.imgur.com/sdryrlO.jpg)
Also, I've experienced a problem when working with "open original email".
I think I will file a separate bug for that

**Comment by let4be** [comment]
it doesn't seem to be useful anymore, closing this
