### ISSUE TITLE
Style new compose screen formatting tool

### ISSUE THREAD

**Issue by let4be** [lavab/web#626]
So, I'm adding "pre" tool to allow writing plain/text emails as asked in https://github.com/lavab/web/issues/546

![image](https://cloud.githubusercontent.com/assets/4147061/7553495/56e178c2-f704-11e4-8e4b-eb66db5c1ab9.png)

need to add proper icon to this

Where? develop

**Comment by piggyslasher** [comment]
yeah. thats fixed. the left/right justify icons are not showing. something wasnt right with the icons i used this latest time. i wanted thinner icons. I'll sort it out.

**Comment by flixi** [comment]
Don't display H1 H2 H3, but make them indicators of how large the text will be so #H1 ##H2 ###H3

**Comment by piggyslasher** [comment]
@let4be could you look into adding dropdown support into the textangular toolbar?

https://github.com/fraywing/textAngular/issues/397

and more specifically this gist seems to add dropdown support.

https://github.com/gorgias/gorgias-chrome/blob/98f9f73fb77f023f870475624bdaf0858cdb832a/src/background/js/editor-toolbar.js#L72-L116

This issue is fixed. Let me close when its in develop.

**Comment by piggyslasher** [comment]
And yes @flixi - the heading icons are more intuitive now. just need to get this to display properly.

**Comment by kalicki** [comment]
@piggyslasher Look this..

https://github.com/froala/angular-froala
https://github.com/TerryMooreII/angular-wysiwyg
https://github.com/daviferreira/medium-editor

**Comment by piggyslasher** [comment]
Yeah we reviewed medium & wysiwyg. We settled on textangular because of a few reasons. It handles drag & drop better. If anything this would be a major change. And we would only make it after we release 2.1 or somewhere down the line.

**Comment by piggyslasher** [comment]
Thanks for your input @kalicki - appreciate it. And we already have our own fork of textAngular by @let4be

**Comment by piggyslasher** [comment]
@vLooz - can I assign this to you?

Here's the way it currently looks.

![image](https://cloud.githubusercontent.com/assets/1991125/7589369/e175d4d2-f8f4-11e4-8bc0-9d5cdc2c7c7d.png)

I'll assign this to you while we get the final icons.

**Comment by vLooz** [comment]
This is related to this issue https://github.com/lavab/web/issues/255 @piggyslasher

**Comment by vLooz** [comment]
https://cloud.githubusercontent.com/assets/11177812/6595683/c6d5c7a6-c7ec-11e4-8839-b9314d25f047.jpg

**Comment by piggyslasher** [comment]
Yup. We have to wait for dropdown support on textAngular.
