### ISSUE TITLE
. in Email addresses isn't shown

### ISSUE THREAD

**Issue by flixi** [lavab/web#628]
![screen shot 2015-05-09 at 18 24 04](https://cloud.githubusercontent.com/assets/707993/7554256/922b56a2-f720-11e4-8df2-6410ecb09239.png)

**Comment by flixi** [comment]
![bildschirmfoto 2015-05-10 um 14 50 32](https://cloud.githubusercontent.com/assets/707993/7554316/0f61430e-f724-11e4-92f5-a6685e62d6c0.png)

**Comment by flixi** [comment]
And one more, saying he's missing the . in his interface but on the emails outgoing it's here

**Comment by let4be** [comment]
Got it, will fix
