### ISSUE TITLE
Sanatizer goes wild

### ISSUE THREAD

**Issue by flixi** [lavab/web#629]
If you paste a text inside the compose window, all of the formatting goes away.

**Comment by let4be** [comment]
where does it happen? master/develop?

**Comment by let4be** [comment]
What kind of text did you try to insert @flixi ?

If this is just a regular text without any formatting except new lines - yes this formatting will go away as editor is in html mode

develop branch has new mode for inserting pre-formatted text(pre button) exactly for such situations

**Comment by flixi** [comment]
Yes, only text with line breaks.

**Comment by let4be** [comment]
So we need to decide what kind of behavior do we want,

currently on develop there is a separate mode which adds PRE element
and when you insert text with line breaks inside this PRE it preserves the formatting

we could make it default behavior and simply convert all lines breaks to <br/> tags when user pastes text inside editor

What do you think?

**Comment by flixi** [comment]
Yes, i like this, it takes the friction away.

**Comment by let4be** [comment]
Eh, it seems to be some bug in textAngular we're using
I will check it more deeply as currently it indeed wipes all formatting of text...

**Comment by let4be** [comment]
The underlying problem:
sanitizer runs before paste event and removes all new lines from the text... which makes impossible to properly replace them with <BR> tags

**Comment by let4be** [comment]
so, caused by: https://github.com/fraywing/textAngular/issues/686

**Comment by let4be** [comment]
I will do a fork and PR today later
