### ISSUE TITLE
Proper export Public Key for Users

### ISSUE THREAD

**Issue by flixi** [lavab/web#632]
Please add an option to export a public key and a public key only.

**Comment by let4be** [comment]
This is a bit of a mess currently, we have 2 designs mixed and deployed at master...

**Comment by let4be** [comment]
Made 
![image](https://cloud.githubusercontent.com/assets/4147061/7559632/679b652e-f7c2-11e4-8cc6-49456c6b30f1.png)
export public key only from a given keypair
