### ISSUE TITLE
Spam Folder: No need for "star" button 

### ISSUE THREAD

**Issue by vLooz** [lavab/web#635]
Please remove the star button from the upper right panel @piggyslasher 
I don't think it happens very often, that someone want to star a mail right from trash :-) 

![bildschirmfoto 2015-05-11 um 16 16 48](https://cloud.githubusercontent.com/assets/11177812/7566838/751021d6-f7f9-11e4-9c25-22fde57c1413.png)

**Comment by let4be** [comment]
indeed :D

**Comment by let4be** [comment]
removed both from Spam and Trash
