### ISSUE TITLE
Apparent lack of unicode support

### ISSUE THREAD

**Issue by andreis** [lavab/web#642]
Is this from us? If so, web or api?

**Comment by andreis** [comment]
![screen shot 2015-05-12 at 17 38 05](https://cloud.githubusercontent.com/assets/1249760/7591367/cb386d78-f8cd-11e4-8d68-253de935bf3b.png)

**Comment by let4be** [comment]
I blame Mailer, but I may be wrong
https://github.com/lavab/mailer/issues/46

**Comment by andreis** [comment]
I blame Obama

**Comment by andreis** [comment]
It's quite an embarrassing bug, tbh. :p

**Comment by let4be** [comment]
so, caused by https://github.com/lavab/mailer/issues/48

**Comment by pzduniak** [comment]
![even from fields work?!](http://qs.lc/vd9y2)

**Comment by andreis** [comment]
Is that your actual name?

**Comment by andreis** [comment]
Piótr

**Comment by andreis** [comment]
Superficial comment about how this library is rather unproven (if you end up using it) https://github.com/mathiasbynens/q-encoding
