### ISSUE TITLE
Import Open PGP  sec/pub keypair  and decrypt for use at lava boom.com

### ISSUE THREAD

**Issue by paulhugel** [lavab/web#650]
@LavaBoomHQ said  
https://twitter.com/LavaboomHQ/status/598007509048283136?cn=cmVwbHk%3D&refsrc=email

![twitter import from keyserver](https://cloud.githubusercontent.com/assets/6466830/7598492/455d4c78-f896-11e4-9875-8846c497528a.png)

On lavaboom.com Imported  using Settings-->Security--> Import keys
my sec/pub keypair from GPGTools GPG Keychain as A3F48305.asc

Import successful but lock was orange and system asked for decryption 
unable to decrypt using  either lavaboom password or my paul@nko.org secret passphrase
(note* I did not add user ID for paulhugel@lavaboom.com)
Could not delete keypair paul@nko.org because it was not decrypted

Tech support deleted the mangled keys I imported.

I currently have lavaboom synch enabled

Using GPGTools GPG Keychain 
I can add paulhugel@lavaboom.com to   sec/pub A3F48305.asc  paul@nko.org
Update key to key server hkps://hkps.pool.sks-keyservers.net
Then I can export sec/pub A3F48305.asc with  newly added user paulhugel@lavaboom.com

Lavaboom documentation says import keys as .txt but does not mention .asc format

Is the following apropriate  on Mac to convert exported keypair to .txt?

When I export from GPGTools GPG Keychain A3F48305 I can add the extension .txt so output would be A3F48305.txt

Can I safety try ?

Is it possible to switch keys when sending mail like is possible outside of lava boom.com?

Or will the problem of can't decrypt secret key happen 
and again 
I won't be able to delete my key thats not decrypted?
![add user id lavaboom com](https://cloud.githubusercontent.com/assets/6466830/7599006/5faea302-f89a-11e4-8f28-a0b7328fa0a5.png)

**Comment by paulhugel** [comment]
Attempted to import sec/pub keypair  A3F48305.txt

import successful 

Errors reported in Safari Console attempting to decrypt


[Error] Error
d (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 317)
m (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 317)
authenticate (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 317)
(anonymous function) (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6610)
(anonymous function) (utils-vendor-4414d23ae1ebe103a269c22510f88cece77da46f.js, line 6620)
e (utils-vendor-4414d23ae1ebe103a269c22510f88cece77da46f.js, line 6522)
(anonymous function) (utils-vendor-4414d23ae1ebe103a269c22510f88cece77da46f.js, line 6526)


![sec pub pgp imported](https://cloud.githubusercontent.com/assets/6466830/7618671/632928d0-f94f-11e4-9a9a-c280300424cc.png)

**Comment by pzduniak** [comment]
I was about to reopen it :) It's an issue with decryption, right? Does anything happen when you enter the passphrase?

**Comment by paulhugel** [comment]
yes in safari console

details the issue of code ?


[Error] Error
d (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 317)
m (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 317)
authenticate (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 317)
(anonymous function) (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6610)
(anonymous function) (utils-vendor-4414d23ae1ebe103a269c22510f88cece77da46f.js, line 6620)
e (utils-vendor-4414d23ae1ebe103a269c22510f88cece77da46f.js, line 6522)
(anonymous function) (utils-vendor-4414d23ae1ebe103a269c22510f88cece77da46f.js, line 6526)

**Comment by paulhugel** [comment]
Yes  shown in Safari Console

[Error] Error
d (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 317)
m (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 317)
authenticate (utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js, line 317)
(anonymous function) (appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js, line 6610)
(anonymous function) (utils-vendor-4414d23ae1ebe103a269c22510f88cece77da46f.js, line 6620)
e (utils-vendor-4414d23ae1ebe103a269c22510f88cece77da46f.js, line 6522)
(anonymous function) (utils-vendor-4414d23ae1ebe103a269c22510f88cece77da46f.js, line 6526)

**Comment by pzduniak** [comment]
Is your private key encrypted?

**Comment by paulhugel** [comment]
sec/pub pgp are always encrypted on import
then the password requirement to decrypt produces the error code above in Safari console
I believe the there is a related issue below ?

 "Separate step "enter private key password" when key is encrypted with different password #267" 

Would it be reasonable to merge the two bugs #650 and #267 ?

**Comment by paulhugel** [comment]
Note* This time  I updated the user ID to include paulhugel@lavaboom.com 
![sec pub key imported w paulhugel lavaboom com](https://cloud.githubusercontent.com/assets/6466830/7621773/0b174c38-f965-11e4-9383-8e306ec96d33.png)

**Comment by let4be** [comment]
Please: don't use Safari for now, Firefox/Chrome/Opera/IE should work better
Small hack hint: you can remove all keys from account by simply disabling Lavaboom Sync and clearing browser cache(or session/local storage manually from developer tools F12)

**Comment by paulhugel** [comment]
Aloha,

Please advise how to proceed
I did toggle lavaboom  Sync to clean the sec/pub key that could not be decrypted

Is there a utility to convert an exported Open PGP  self signed sec/pub keypair  in .asc or .txt to the .json format that Lavaboom  web might have less trouble with?

Mac OS 10.10.3
Chrome 42.0.2311.152 (64-bit)
Firefox 37.0.2

First Refreshed key from key server—>
Exporting sec/pub keypair using GPGTools beta 6 GPG Keychain saved as—> A3F48305.txt



Lavaboom web 0.3.0
Served by marge

Import sec/pub open pgp keypair into Lavaboom.com Settings—>Security—> Import Keys



Using Firefox developer tools errors reported on decrypting keypair A3F48305.txt


Error: Nothing to decrypt in a public key
Stack trace:
[45]</d.prototype.decrypt@https://mail.lavaboom.com/vendor/openpgp.js:9:26332
[20]</module.exports</d@https://mail.lavaboom.com/js/utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js:317:1099
[20]</module.exports</m@https://mail.lavaboom.com/js/utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js:317:1307
[20]</module.exports</this.authenticate@https://mail.lavaboom.com/js/utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js:317:5772
p/</h<@https://mail.lavaboom.com/js/appLavaboom-ebc4a555380746b6df4a3af3cb81e072cb55f056.js:6610:1609
f/l<@https://mail.lavaboom.com/js/utils-vendor-4414d23ae1ebe103a269c22510f88cece77da46f.js:6620:473
e@https://mail.lavaboom.com/js/utils-vendor-4414d23ae1ebe103a269c22510f88cece77da46f.js:6522:72
nf/n.defer/c<@https://mail.lavaboom.com/js/utils-vendor-4414d23ae1ebe103a269c22510f88cece77da46f.js:6526:155
 utils-1c709a3537af0921fa3bb02ac50043ea3ed530b7.js:317:1127

"canceled" utils-vendor-4414d23ae1ebe103a269c22510f88cece77da46f.js:6584:324


Source of error inside: https://mail.lavaboom.com/js/utils-vendor-4414d23ae1ebe103a269c22510f88cece77da46f.js

Error&&(a.stack?a=a.message&&-1===a.stack.indexOf(a.message)?"Error: "+a.message+"\n"+a.stack:a.stack:a.sourceURL&&(a=a.message+"\n"+a.sourceURL+":"+a.line));return a}function e(a){var b=c.console||{},e=b[a]||b.log||E;a=!1;try{a=!!e.apply}catch(l){}return a?function(){var a=[];r(arguments,function(b){a.push(d(b))});return e.apply(b,a)}:function(a,b){e(a,null==b?"":b)}}return{log:e("log"),info:e("info"),warn:e("warn"),error:e("error"),debug:function(){var c=e("debug");return function(){b&&c.apply(a,

**Comment by let4be** [comment]
A lot of related issues have been fixed since 0.3.0
More fixes coming today-tomorrow, I'm closing this for now
