### ISSUE TITLE
Contacts not saved - add auto-save on navigating out

### ISSUE THREAD

**Issue by tyrotex** [lavab/web#651]
I successfully sent an unencrypted email to a recipient.
I then added that recipient to my Contacts list, including their public key.  It seems there should be "Save" button after entering the contact, but it seems to work, as I could switch away from "Contacts" then back again and the entry is still there.
However, when I went to compose another email to that recipient, LB was still saying it would be unencrypted, i.e. it was not picking up the recipient from my contacts list.
After logging out and back in again, my contacts list was empty, so it seems the contact was never really added/saved.
I tried this with TorBrowser and Safari with the same results.  I assumed that TorBrowser was clearing cookies, etc, and that may be clearing my contacts.  But, Safari should work.

**Comment by let4be** [comment]
When you create a new contact, it opens in edit mode

You can freely change it, add emails or navigate away from it and come fill later

But to save it you need to press top-right button :)

![image](https://cloud.githubusercontent.com/assets/4147061/7612118/74f17a6c-f991-11e4-8010-a3ce8b5d708e.png)

Are you sure you saved the contact?

**Comment by let4be** [comment]
Probably we should add a warning when user leaves a page and if he presses no - discard the changes
@vLooz ?

**Comment by vLooz** [comment]
What about autosave instead? Is that feasable?

**Comment by let4be** [comment]
Sounds good, will implement

**Comment by tyrotex** [comment]
@let4be Thanks for that.  My bad!  I did not even see the very tasteful cross/tick in the black bar.  Perhaps they could be a little thicker and a stronger color, just to ensure that they are more easily seen.
Autosave would also be good, but I think it's more a UI issue at present

**Comment by piggyslasher** [comment]
We had an autosave mechanism in the beginning but it was not quite usable.
The display and edit modes needed to be separated. Also we have things such
as key discovery in the edit page which wasn't really easy to use when
autosave was on.
