### ISSUE TITLE
keyring backup json file has a broken link.

### ISSUE THREAD

**Issue by straikongit** [lavab/web#652]
The keyring backup json file refers to https://lavaboom.com/faq/keyring-backup. The Server responds with 404.

**Comment by let4be** [comment]
This is known and is in our todo, just material isn't ready

**Comment by andreis** [comment]
Most likely it will have a link similar to:
http://support.lavaboom.com/knowledge_base/topics/getting-started-25

**Comment by andreis** [comment]
Please replace URL with this:

https://lavab.groovehq.com/knowledge_base/topics/backing-up-your-keyring

Keeping the issue open as I still need to write the article.

**Comment by andreis** [comment]
> Keeping the issue open as I still need to write the article.
