### ISSUE TITLE
Better key metadata

### ISSUE THREAD

**Issue by andreis** [lavab/web#656]
![screen shot 2015-05-13 at 10 51 36](https://cloud.githubusercontent.com/assets/1249760/7606975/0a83a1c4-f95e-11e4-883d-49c13f25d4d9.png)

The `Name` field, for example

**Comment by andreis** [comment]
As it's a simple task might be a good one for @hyzhak  to familiarise himself with the code.

**Comment by let4be** [comment]
sry @andreis ... Worked on a similar thing, couldn't let this issue live any longer ^^

**Comment by andreis** [comment]
:+1:
