### ISSUE TITLE
Contacts import

### ISSUE THREAD

**Issue by let4be** [lavab/web#663]
Many users ask for contacts import feature, basically there are few formats we may want to support:
google csv
outlook csv
apple vCard (.vcf)

might be useful:
https://github.com/nilclass/vcardjs
https://github.com/mholt/PapaParse

we may also want to ask about this during signup once this implemented

**Comment by andreis** [comment]
Based on volume

* Gmail
* Yahoo
* Hotmail

Based on target market

* Hushmail
* Protonmail
* Fastmail

**Comment by let4be** [comment]
We now have gmail csv and vcard import functionality :)

**Comment by let4be** [comment]
outlook csv is also here now :)

**Comment by let4be** [comment]
okay closing this for now, will be deployed tomorrow
