### ISSUE TITLE
Browser alert!

### ISSUE THREAD

**Issue by Im4JAR** [lavab/web#664]
Shows the "upgrade browser" bar , even though safari is on the newest version.  

![bildschirmfoto 2015-05-13 um 18 37 16](https://cloud.githubusercontent.com/assets/10942269/7615680/7a3eb4ae-f99f-11e4-8df3-d0aa5cebb32a.png)

**Comment by let4be** [comment]
Safari tends to have different compatibility issues with the modern web standards Lavaboom is based at:
- problems with downloading js-generated files
- problems with webcrypto on some versions

This particular warning means openpgp.js was unable to use webcrypto in your browsers - this means all encryption/decryption/key-gen operations will be _extremely_ slow

@Im4JAR, could you please try to open Lavaboom with Firefox or Chrome and post the result here?
