### ISSUE TITLE
Plugin architecture

### ISSUE THREAD

**Issue by let4be** [lavab/web#679]
we had a talk with @andreis and ... we want to have a possibility to extend Lavaboom web with optional plugins, they will be:
- hosted in a separate repo 
- being pulled and bundled by gulp as a part of Lavaboom building process
- follow common architecture and concepts

for example: 
- https://github.com/lavab/web/issues/661,
- https://github.com/lavab/web/issues/661 version for enterprise users saying "You are awesome", "Lavaboom says hi", etc...
- closed source admin plugin

**Comment by let4be** [comment]
So, created `web public plugins` repo
The draft structure/readme is available at: https://github.com/lavab/web-plugins
see sample plugin

Going to integrate this into gulp build system now

**Comment by andreis** [comment]
I'd like using individual repos. I suggest using https://github.com/lavab-plugins

This way we can let people build their own plugins if they want, and we keep memberships neat and tidy.

Another option is to use `https://github.com/lavab/web-sample` type names for plugin repos

**Comment by andreis** [comment]
Or, we can have `https://github.com/lavab/web-:plugin_name:` for core plugins, and `https://github.com/lavab-plugins/:plugin_name:` (or `https://github.com/lavab-contrib/:plugin_name:`) for community plugins.

**Comment by andreis** [comment]
Either way, I would:

* check out how Atom does it and what lessons we can learn from there
* have an API for plugins
* have some guidelines for writing them
* add some plugin tools - stats, debugging, etc

**Comment by let4be** [comment]
Today I was just mostly playing with gulp/browserify integration(in free time), i.e. git clone/pull and some browserify magic.

I would like to avoid having a separate build system for each plugin, instead I want them to follow a common structure and architecture,
lavab/web will clone/pull && build them, connect to the application in the right order and execute(loader.js).

For core plugins I would like to have all them in a single repo as it's much simpler to make changes and push them at one step.
For user plugins we can go with separate repos, sure

**Comment by let4be** [comment]
@andreis so I came up to the following specification, feel free to add/modify/suggest

2 types - custom plugin and angular plugin
- custom: very simple plugin is being assembled using browserify only and nothing else, doesn't have any restrictions on directory structure
- angular: relies on predefined directory structure, same as `web`

Browserify(with some magic) allows us to require `*.less` and `*.jade` files thus plugins will be almost self-contained, exceptions: images, fonts - we need to copy this into `dist/fonts/plugins/[plugin-name]` and `dist/img/plugins/[plugin-name]`., actually we could even put fonts inside `less`

Each plugin can be concatenated with existing application and loaded at different stage, there is a list of 4 existing applications:
- `Loader`
- `LavaboomUtils` - shared logic for the next 2 apps
- `AppLavaboom` - primary app
- `AppLavaboomLogin` - login/signup app

Each angular plugin can be connected with existing angular application: 

- loading in the same `angular.js module`
this allows us to do pretty low level things as decorating services

- be connected as a separate `angular.js module`
uses higher level communication

Low level communication API:
```
host.registerPlugin(name, options)

options = {
    version: 'string with plugin version',
    description: 'string with plugin description',
    messageHandler: 'callback for handling messages from another plugins',
    initialize: 'plugin initialization routine, returns promise'
}

host.sendMessage(toPluginName, msg)
host.broadcastMessage(msg)
```

There will be a angular.js wrapper for this api, thus we will be able to comfortable create plugins both using angular or any other framework. Though for `core` plugins I think we should use angular.

Each plugin is being hosted in a separate repo.

I also suggest to refactor our code base and finally make applications separate and being assembled as plugins, we already have 4 almost separate application types so it should be relatively easy to do.

**Comment by piggyslasher** [comment]
Wow. Nice work guys. I'm for separate repos under a separate account as
Andreis (lavab-plugins) because we can use gulp-gitmodified to update the
plugins from its repo during gulp, if anything is changed. That way we have
a self updating plugin system. This is the way gulp and grunt do it.

**Comment by let4be** [comment]
@piggyslasher It's already implemented using gulp-git, just clone and pull basically

**Comment by andreis** [comment]
@piggyslasher I agree with Sergey, let's have all core (i.e. mandatory for the app to run) in `lavab/web`.

`github.com/lavab-plugins` will act like a package manager, so that you can import a plugin by name instead of full path. Examples:

* `admin-ui` will go in `lavab-plugins`, so you import it by name
* the plugin that writes the name of a random supporter in the loader is something specific to use, so we can put it in a repo in `lavab` and load it by URL `https://github.com/lavab/web-supporters`

*Question* Should I rename `lavab-plugins` to `lavab-contrib`?

**Comment by let4be** [comment]
Basic plugins arch was implemented some time ago,
docs are at https://github.com/lavab-plugins/sample readme
