### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by Adam24** [lavab/web#682]
i used to be able to login and generate keys but now I'm unable to sign in AT ALL.  it just tries to sign in and then it does nothing.  sign in button turns gray for a few seconds and then turns blue with no loading screen.

**Comment by let4be** [comment]
Hi @Adam24 

Probably there was just a temporarily issue, please try to refresh browser page(ctrl + F5) and try again
If this doesn't help please open developer console(F12) there should be console logs. This may help to get the real cause of the problem

Thanks!

**Comment by Adam24** [comment]
here is the log.  It sent requests to sock.js but failed to do something else:
initialize crypto with  Object {isPrivateComputer: false, isShortMemory: false} provided Object {}
cryptoKeysStorage.js:22 CryptoKeysStorage created, isPrivateComputer: false isShortMemory: false loadOnlyForEmails: [] isLoadDecrypted: true
LavaboomAPI.js:44 Calling tokens.create [Object] ...
lavaboom-api.js:203 sockjs: sending a message {"id":"10","type":"request","method":"POST","path":"/tokens","body":"{\"type\":\"auth\",\"username\":\"adamthechespin\",\"password\":\"456d22e36b3b88775da120b197ce708826624f9774c5bdb6cd78f9e3ffa04520\"}","headers":{"Content-Type":"application/json;charset=utf-8","Authorization":"Bearer a9Zn5DRxxLqXXmqOjkMa"}}
LavaboomAPI.js:49 tokens.create:  Object {body: Object, headers: Object, id: "10", status: 201, type: "response"}
LavaboomAPI.js:44 Calling accounts.get ["me"] ...
lavaboom-api.js:203 sockjs: sending a message {"id":"11","type":"request","method":"GET","path":"/accounts/me","body":"null","headers":{"Authorization":"Bearer caZFFhMDFmeBvR0CdBkq"}}
lavaboom-api.js:203 sockjs: sending a message {"id":"12","type":"request","method":"GET","path":"/addresses","body":"null","headers":{"Authorization":"Bearer caZFFhMDFmeBvR0CdBkq"}}
LavaboomAPI.js:49 accounts.get:  Object {body: Object, headers: Object, id: "11", status: 200, type: "response"}
2angular.min.js:102 TypeError: Cannot read property 'map' of undefined
    at https://mail.lavaboom.com/js/utils-0250e29af9f2aa854ca06eae19c4e50629ee3fe2.js:6805:5216
    at tryCatch (https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:2701:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:2874:22)
    at GeneratorFunctionPrototype.Gp.(anonymous function) [as next] (https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:2910:19)
    at onFulfilled (https://mail.lavaboom.com/js/utils-0250e29af9f2aa854ca06eae19c4e50629ee3fe2.js:2026:19)(anonymous function) @ angular.min.js:102(anonymous function) @ angular.min.js:76(anonymous function) @ co.min.js:1tryCatch @ browser-polyfill.js:2701invoke @ browser-polyfill.js:2874Gp.(anonymous function) @ browser-polyfill.js:2910onRejected @ index.js:80

**Comment by andreis** [comment]
Just wanted to say that the cross-platform shortcut is `Ctrl/Cmd+Shift+R` :smile:

**Comment by andreis** [comment]
Btw, killed your auth token, as anyone could've impersonated you with it. :)

```
r.db('prod').table('tokens').get('a9Zn5DRxxLqXXmqOjkMa').delete()

Executed in 106ms. 1 row returned
{
"deleted": 1 ,
"errors": 0 ,
"inserted": 0 ,
"replaced": 0 ,
"skipped": 0 ,
"unchanged": 0
}
```

**Comment by let4be** [comment]
Will check this tomorrow
Thanks for the logs :)

**Comment by Adam24** [comment]
ok.

On Thu, May 14, 2015 at 4:46 PM, let4be <notifications@github.com> wrote:

> Will check this tomorrow
> Thanks for the logs :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lavab/web/issues/682#issuecomment-102178956>.
>



-- 
--Adam Robertson-- (write back)

**Comment by let4be** [comment]
@Adam24 issue should be fixed in master, please await for deploy

**Comment by Adam24** [comment]
Ok, thanks.

On Friday, May 15, 2015, let4be <notifications@github.com> wrote:

> @Adam24 <https://github.com/Adam24> issue should be fixed in master,
> please await for deploy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lavab/web/issues/682#issuecomment-102370898>.
>


-- 
--Adam Robertson-- (write back)

**Comment by let4be** [comment]
did the fix help you to get in, @Adam24 ?

**Comment by Adam24** [comment]
Haven't tried but I will soon.

On Friday, May 15, 2015, let4be <notifications@github.com> wrote:

> did the fix help you to get in, @Adam24 <https://github.com/Adam24> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lavab/web/issues/682#issuecomment-102453327>.
>


-- 
--Adam Robertson-- (write back)

**Comment by Adam24** [comment]
it caused an initialization failed error just like i've been having many times.  PLEASE FIX, @let4be.
