### ISSUE TITLE
Style changes for "served by" and version

### ISSUE THREAD

**Issue by andreis** [lavab/web#685]
See left-bottom corner

![screen shot 2015-05-14 at 23 51 18](https://cloud.githubusercontent.com/assets/1249760/7643253/fbf6bade-fa97-11e4-9108-68e243b94195.png)

Please:

* change the order of the messages
* use a darker colour to de-emphasise them (#999999 in the screenshot)

**Comment by piggyslasher** [comment]
so you want to show the copyright message on top @andreis ?

**Comment by andreis** [comment]
Totally

**Comment by piggyslasher** [comment]
the icons are darker already. they only light up on hover.

**Comment by let4be** [comment]
Probably even
```
© Lavaboom 2015
0.3.3 served by Marge
```

**Comment by andreis** [comment]
:+1:
