### ISSUE TITLE
Can't send attachments to non-lavaboom recipients

### ISSUE THREAD

**Issue by stratacast1** [lavab/web#687]
When sending an attachment to a non-lavaboom user, the file fails to upload and the email will not send. So far I have tested sending a public key .asc file, jpg, png, and odt file. I've tried sending an email with an attachment to a gmail, hotmail, and att domain email.

**Comment by let4be** [comment]
@stratacast1 thank you for the report, bug is confirmed

**Comment by let4be** [comment]
First of all, need to implement this: https://github.com/lavab/web/issues/691

**Comment by let4be** [comment]
Fixed only for plain-text attachments, binary unencrypted attachments will require some additional work

**Comment by let4be** [comment]
Reopened with details, in: https://github.com/lavab/web/issues/692
