### ISSUE TITLE
Feature Wish use existing OpenPGP sec/pub keypair

### ISSUE THREAD

**Issue by paulhugel** [lavab/web#688]
Testing lavaboom web 0.3.1
OSX 10.10.3
Firefox 38.01

On signup can we have option to 
1.) Use existing PGP  keypair
OR
2.)Generate new keypair using the reserved username at lavaboom.com
(currently there is no lock on restricting new users to reserved username so there could be large database of secured usernames which are not utilized)

Has anyone successfully imported and decrypted a 
GPGTools beta 6  sec/pub key export from GPG Keychain into
https://mail.lavaboom.com/settings/security

I still can't  decrypt my current sec/pub fingerprint d922 b7b1 3a4d 9bf9 0927 dca1 7a14 4b7d a3f4 8305
after its added to https://mail.lavaboom.com/settings/security

As I type in the  characters for my pas-phrase of  imported sec/pub key Errors are reported with each keystroke  input (see below)

Firebug Console:

Errors: 
Nothing to decrypt in a public key
[45]</d.prototype.decrypt()openpgp.js (line 9)
[52]</module.exports</m()utils-0...3fe2.js (line 6773)
[52]</module.exports</l()utils-0...3fe2.js (line 6773)
[52]</module.exports</this.authenticateByEmail/<()utils-0...3fe2.js (line 6773)
[52]</module.exports</this.authenticateByEmail()utils-0...3fe2.js (line 6773)
i/<()utils-0...3fe2.js (line 6805)
tryCatch()utils-v...7203.js (line 2701)
invoke()utils-v...7203.js (line 2874)
defineGeneratorMethod/Gp[method]()utils-v...7203.js (line 2910)
onFulfilled()utils-0...3fe2.js (line 2026)
f/<()utils-v...7203.js (line 6590)
Pe/this.$get</n.prototype.$eval()utils-v...7203.js (line 6604)
Pe/this.$get</n.prototype.$digest()utils-v...7203.js (line 6601)
Pe/this.$get</n.prototype.$evalAsync/<()utils-v...7203.js (line 6604)
e()utils-v...7203.js (line 6518)
nf/n.defer/c<()utils-v...7203.js (line 6522)
	

...sion_algorithms:22,key_server_preferences:23,preferred_key_server:24,primary_use...

SOURCE:  
https://mail.lavaboom.com/vendor/openpgp.js     
openpgp.js  (line 9)

d.prototype.xor=ja,d.prototype.andNot=la,d.prototype.not=ma,d.prototype.shiftLeft=na,d.prototype.shiftRight=oa,d.prototype.getLowestSetBit=qa,d.prototype.bitCount=sa,d.prototype.testBit=ta,d.prototype.setBit=va,d.prototype.clearBit=wa,d.prototype.flipBit=xa,d.prototype.add=za,d.prototype.subtract=Aa,d.prototype.multiply=Ba,d.prototype.divide=Da,d.prototype.remainder=Ea,d.prototype.divideAndRemainder=Fa,d.prototype.modPow=Va,d.prototype.modInverse=Ya,d.prototype.pow=Ma,d.prototype.gcd=Wa,d.prototype.isProbablePrime=Za,d.prototype.toMPI=$a,d.prototype.square=Ca},{"../../util.js"

SOURCE: 
https://mail.lavaboom.com/js/utils-vendor6d747fe03913b25a37542b9a6cd249f62bfe7203.js      
utils-vendor6d747fe03913b25a37542b9a6cd249f62bfe7203.js  (line 6580)

Error&&(a.stack?a=a.message&&-1===a.stack.indexOf(a.message)?"Error: "+a.message+"\n"+a.stack:a.stack:a.sourceURL&&(a=a.message+"\n"+a.sourceURL+":"+a.line));return a}function e(a){var b=c.console||{},e=b[a]||b.log||E;a=!1;try{a=!!e.apply}catch(l){}return a?function(){var a=[];r(arguments,function(b){a.push(d(b))});return e.apply(b,a)}:function(a,b){e(a,null==b?"":b)}}return{log:e("log"),info:e("info"),warn:e("warn"),error:e("error"),debug:function(){var c=e("debug");return function(){b&&c.apply(a,

**Comment by paulhugel** [comment]
Lavaboom 0.4.2
OSX 10.10.3
Firefox 38.01
TextEdit 1.10
GPGTools beta 6

I used to get get failure warnings when importing to keyring  "no secret key found"

There is a workaround for importing sec/pub key pair

I had to  reverse the order of keys displayed in key file.

1)Export GPGTools GPGKeyring key pair  (include secret key)  save as .txt extension
2)Open file in TextEdit
2)reverse the  display order of keys so secret key displays first 

Screen shots show reversal of order for sec/pub key in order to be acceptable to successfully import to the keyring.


So this time I was able to import key pair and then decrypt with a secret key password

![pgp key reversed](https://cloud.githubusercontent.com/assets/6466830/7900699/62a242be-0702-11e5-93ae-e74b87c3dfa1.png)

Second screen shot shows new sec/pub key added to lavaboom keyring

![screen shot 2015-05-30 at 6 55 10 pm](https://cloud.githubusercontent.com/assets/6466830/7900720/94124a6a-0702-11e5-8177-86fe781f9e6d.png)

.

**Comment by let4be** [comment]
The thing should work without this magic as recently there was a fix, could you please try again without reversing?

**Comment by let4be** [comment]
@paulhugel support added and going to be deployed to mail.lavaboom.co in the next 2 hours ;)
Thank you for this report it helped to catch the cause of the problem

**Comment by paulhugel** [comment]
Problem persists cannot import secret/pub key   created from GPG Tools A3F48305.asc
I have to  edit key file --> reverse order (position in file) of sec/pub key
OSX 10.10.3
Chrome 43.0.2357.124 (64-bit)
GPG Suite Beta 6
GPG Keychain V 1.2
Lavaboom mail server Version (unlisted) blank
![no private key found](https://cloud.githubusercontent.com/assets/6466830/8120467/183ce02a-103b-11e5-932c-ca5ef24d4dba.png)
