### ISSUE TITLE
Inbox:Email is shown encrypted. What has gone wrong and what can I do?

### ISSUE THREAD

**Issue by vLooz** [lavab/web#694]
Thats what I see when I open a mail from a friend of mine. This has not happened before with this contact, nor with other Mails I got. I didn't get any KeyPair warning, and there is only one decrypted KeyPair in Settings/Keys. 

What could have caused this? And how can I decrypt this message?

Furthermore I think we need a warning in the future when something like this happens.

![bildschirmfoto 2015-05-15 um 11 27 55](https://cloud.githubusercontent.com/assets/11177812/7650338/8c515b2c-faf5-11e4-970d-65d9409446fd.png)

**Comment by let4be** [comment]
1st. send with another software(see https://www.mailvelope.com/)
I'm not currently sure is this supported

I think this user just copy-pasted the encrypted message in compose screen.
Technically it should be supported, but probably it was done wrong.

@vLooz Please download original email body(.html or .txt) and post it there

**Comment by vLooz** [comment]
Ah, I was thinking that. thx for the info!

Thats the title, when I hover over it:

![bildschirmfoto 2015-05-15 um 12 21 05](https://cloud.githubusercontent.com/assets/11177812/7651083/e3e13efa-fafc-11e4-916d-4f32a0fd8c38.png)

**Comment by let4be** [comment]
Most likely he simply encrypted this email with someone else's public key

**Comment by let4be** [comment]
@vLooz UX updates are welcomed here, this functionality has been made on a knee :D

**Comment by vLooz** [comment]
I think we can use our normal blue line notification overlay here to tell the user, that this mail could not be decrypted because of... sender used wrong public key? 

Furthermore we could offer to open a reply draft to this mail with the users correct public key attached.
Draft text could be something like:
"Dear <contacts first name>,
I unfortunately couldn't open your mail, because it was encrypted with the wrong public key. 
I attach my correct public key for you.
Best wishes,
<users first name>

What do you think @let4be @andreis ?
