### ISSUE TITLE
Settings/security allows import of public keys

### ISSUE THREAD

**Issue by jrselzer** [lavab/web#696]
After importing a public key as text file, the imported key is listed as

Imported Name
<mymailaddress@lavaboom.com>

It should be

Imported name
<imported.name@somewhere.tld>

**Comment by let4be** [comment]
I don't think it's currently possible to implement
privatekey's userId has the following format `name <email@somewhere.ltd>`

As soon as you import private key into Lavaboom it replaces the `<email@somewhere.ltd>`  with @lavaboom but preserves name

so it becomes `name <your-lavaboom-user-name@lavaboom.com>`
We later user this information to filter keys under settings and show only private keys that belong to currently logged in account(as there may be multiple accounts on the same PC)

What would you advice here @andreis ?

**Comment by jrselzer** [comment]
Sorry, I didn't describe the issue properly:I want to enhance my keyring, so that I can write an encrypted mail to an external (i.e. not Lavaboom) address. Therefore I get a textfile of the target's _public_ key. I import this public key using "Setting > Security > Import Keys" and get the result I described above.

**Comment by let4be** [comment]
Wait, what :D

It is not supposed to be used for public key import... Settings/security is only for _your own_ private keys/backups(which contain both private and public keys)
How did it ever allow you to import public key, interesting...

To import public key of desired contact, please go to Contacts section, create a contact, email then click a lock icon and upload obtained public key ;)

**Comment by let4be** [comment]
I will need to add some more checks there

**Comment by jrselzer** [comment]
Ah, that explains it :) The obvious follow-up question now is: How do I get rid of the key that I should not have imported this way?

**Comment by let4be** [comment]
1. make sure you have a proper backup of your private key
i.e. do export under settings/security and check if there is proper private key backed up
2.a. clear browser cache
2.b less invasive - open developer console(F12) and remove everything from local && session storages
3. refresh the page and login again
4. if Lavaboom Sync was disabled or you just don't see your private key - import from backup

I hope it helps you, @jrselzer 
and thanks for this report ;)

**Comment by jrselzer** [comment]
Solved itself :) The previously imported public key has vanished after logout. It seems like the system recognized it as invalid because the private key was missing.

Thanks for your quick help @let4be and have a nice weekend!
