### ISSUE TITLE
SignUp/LogIn: Items are not vertically centered

### ISSUE THREAD

**Issue by vLooz** [lavab/web#698]
Safari:

![bildschirmfoto 2015-05-15 um 15 35 09](https://cloud.githubusercontent.com/assets/11177812/7653744/5c0fb940-fb18-11e4-8a30-2409dfc1af4d.png)

on my iPhone 6 (Safari) it's shifted so far up, I can't even see the whole flame:

![a94d1eb4-fb18-11e4-87c6-5c3360fb9912](https://cloud.githubusercontent.com/assets/11177812/7653824/ec7c2022-fb18-11e4-8749-6ba65e7a62f1.jpg)

**Comment by vLooz** [comment]
![image](https://cloud.githubusercontent.com/assets/11177812/7653785/a94d1eb4-fb18-11e4-87c6-5c3360fb9912.jpg)

**Comment by piggyslasher** [comment]
:) yes. will update this today.

**Comment by piggyslasher** [comment]
#668

**Comment by piggyslasher** [comment]
use 1vh on middle panel with a scroll on mobile devices.

**Comment by piggyslasher** [comment]
I will be re-writing the login screens with the new sign-in procedure. will close this and focus on #730.
