### ISSUE TITLE
Signup/Login logo doesn't load immidiately which causes content blinking/shifting

### ISSUE THREAD

**Issue by let4be** [lavab/web#699]
![image](https://cloud.githubusercontent.com/assets/4147061/7653780/065a13e8-fb21-11e4-911b-9e87f9b23415.png)
need to reserve logo's space even if the logo isn't loaded yet

**Comment by piggyslasher** [comment]
good idea. btw - what devices is that screenshot from? Android/Chrome?

**Comment by piggyslasher** [comment]
for a < 1kb file I have no idea why there is a lag.

**Comment by let4be** [comment]
the lag is very small but noticable, screenshot is from windows 7, chrome(where I noticed the lag)

**Comment by piggyslasher** [comment]
font looks extra thick there. i probably need to add a non-retina/high-res media query for the fonts.

**Comment by piggyslasher** [comment]
ah crap the loader had its own image, linking to the heavy SVG w/ PNG we were using. fixed.

**Comment by let4be** [comment]
awesome, this bug was hurting my eyes for months :+1:
