### ISSUE TITLE
Issue when sending my public key to a newly created contact you will find 4 times the key attached

### ISSUE THREAD

**Issue by Tourountzis** [lavab/web#703]
Testing lavaboom web 0.3.3 served by marge
OS : Windows 7 Build 7601 (Service Pack 1)
Browser : Firefox 38.0.1

Issue when sending my public key to a newly created contact you will find 4 times the key attached in the mail.

![lavaboom1](https://cloud.githubusercontent.com/assets/1280228/7666462/8c1528ea-fbe6-11e4-8cd4-314fe5251eee.png)
![lavaboom](https://cloud.githubusercontent.com/assets/1280228/7666463/8c17279e-fbe6-11e4-8de3-710a9be4f348.png)

**Comment by let4be** [comment]
hey @Tourountzis 
Could you please describe what steps did you take to get such result?
I'm trying different things and can't reproduce this

**Comment by let4be** [comment]
Ok it seems I found a problem, fix is in the way

**Comment by Tourountzis** [comment]
Thank you so much for the fast response (y)

**Comment by let4be** [comment]
Fixed in master, will deploy ~ in 1 hour :)
