### ISSUE TITLE
Bug in modal when sending attachment

### ISSUE THREAD

**Issue by kalicki** [lavab/web#704]
Why is it that can not attach?
Error in style for attachment.

![captura de tela 2015-05-16 as 14 27 46](https://cloud.githubusercontent.com/assets/3674885/7667259/1e0c3298-fbd8-11e4-8db7-206286776f3b.png)

**Comment by kalicki** [comment]
I'm helping in the premium version and could access the first time, but a shame that has errors.

@vLooz Is not it better increase the weight of the font, it is very thin.

**Comment by let4be** [comment]
https://github.com/lavab/web/issues/692
not supported yet, but will be soon
