### ISSUE TITLE
Show different plans in Settings > Subscription

### ISSUE THREAD

**Issue by andreis** [lavab/web#705]
Someone panicked because they paid for a supporter account and only saw "1,000MB" .

Please:

* show different plans for free/beta/supporter type accounts (500MB, 1GB, 2GB)
* change "1,000MB" to "1GB"

**Comment by andreis** [comment]
@let4be @piggyslasher

**Comment by andreis** [comment]
![screen shot 2015-05-16 at 8 25 48 pm](https://cloud.githubusercontent.com/assets/1249760/7667473/c1f4bdea-fc09-11e4-8775-f517512d77d7.png)

**Comment by vLooz** [comment]
In case you still need the guidelines @piggyslasher 

![bildschirmfoto 2015-05-18 um 12 06 49](https://cloud.githubusercontent.com/assets/11177812/7678696/7f89f9ea-fd56-11e4-9bb4-a7822e305a64.png)

![bildschirmfoto 2015-05-18 um 12 06 40](https://cloud.githubusercontent.com/assets/11177812/7678697/80743d2a-fd56-11e4-8155-cf09463a3ceb.png)

**Comment by let4be** [comment]
it looks different...

**Comment by vLooz** [comment]
Those are the old guidelines. They never really changed ;-)

**Comment by andreis** [comment]
The `1,000MB` just burns my eyes. Can we make it 1GB?

**Comment by let4be** [comment]
@andreis it's changed and deployed, do you see another version? ...

**Comment by andreis** [comment]
![screen shot 2015-05-18 at 14 37 41](https://cloud.githubusercontent.com/assets/1249760/7680939/c30b1e6e-fd6b-11e4-9fff-23bc8c2e9b7f.png)

1. The beta and supporter plans must be hidden (unless you have them, of course)
2. Maybe add "premium" with 15GB storage and a new feature, "Use your own domain". It should have a "coming soon" overlay or something.
3. Add the "access to early Lavaboom features"  feature to Beta and Supporter.

**Comment by let4be** [comment]
@andreis why can't we display all available plans and highlight what plan do you have currently?
it's broken for your account because you have superuser account type

**Comment by vLooz** [comment]
I agree with @andreis, that in general we should not offer options, the user can't chose at the moment. 

If we want to advertise something as "coming soon", that's fine, but not before we have discussed and decided about all the included features. As long as thats still WIP, we should show any premium or business related plans, imo @let4be.

**Comment by vLooz** [comment]
btw, please let me have a look at the UI, before you deploy new or changed elements @let4be 
That's what I'm paid for ;-)

**Comment by andreis** [comment]
> The beta and supporter plans must be hidden (unless you have them, of course)

I'm saying beta and supporter are only available to the people who have them, the general public shouldn't be aware of them.

On second thought, maybe we need to have supporter shown for people with non-supporter accounts, and have a link to our indiegogo campaign. "Get a supporter account for life for as little as $17"

**Comment by andreis** [comment]
Just in case I managed to confuse you, I will just explain what I want to be shown for the two current possible account types, beta and supporter:

### beta

* free - COMING SOON overlay
* beta - green check
* supporter - GET IT ON INDIEGOGO overlay
* premium - COMING SOON overlay

### supporter

* free - COMING SOON overlay
* supporter - green check
* premium - COMING SOON overlay

**Comment by let4be** [comment]
@vLooz i'm currently just changing how it behaves
@piggyslasher will deploy his "how it looks" changes laters

**Comment by andreis** [comment]
We also need a small label with how much time you have left from a subscription. It should be "Unlimited" for free/beta/supporter/premium-lifetime and "Expires on DD Month YYYY".

As for how to implement it, I suggest adding a `subscription` field to the `account` data model (I'd rather avoid `app_data` when possible, to avoid implicit, less maintainable, specs). Suggestion:

```
account
+- subscription
+-+- type ["free"]
+-+- base_storage [0.5]
+-+- total_storage [0.5]
+-+- started [time.Now()]
+-+- duration [0]
+- perks
+-+- 0
+-+-+- name: share_twitter
+-+-+- date time.Now()
+-+-+- space: 0.2
+-+- 1
+-+-+- name: referral
+-+-+- date time.Now()
+-+-+- space: 0.5
+-+-+- user: andrei (or user_id)
```

Where brackets indicate default values and a `duration` of 0 indicates an unlimited subscription.

**Comment by vLooz** [comment]
Do we have the exact features for the premium account yet @andreis @flixi? If not, I'd not recommend to advertise it just yet.

**Comment by andreis** [comment]
€3 per month, €30 per year, 15GB, custom domains (john@domain.com handled by us)

**Comment by piggyslasher** [comment]
@andreis - custom domains can have a 'coming soon' appended to the title. At least people will know we have big plans. I will spruce up the design now.

**Comment by andreis** [comment]
:+1: I can't wait to see the finished thing

**Comment by vLooz** [comment]
connected to this https://github.com/lavab/web/issues/737
Will post the updated Plan UI mocks there once they are finished

**Comment by piggyslasher** [comment]
closing this. will continue convo on #737
