### ISSUE TITLE
Sent email to ProtonMail, received date was wrong

### ISSUE THREAD

**Issue by TurkeyMan** [lavab/web#707]
The email as received by ProtonMail had this date: `01/01/1970 10:00 am (46 years ago)`
Not sure if bug exists on your side or theirs.

**Comment by pzduniak** [comment]
What a great example of how you shouldn't develop software :) We don't send out a "Date" header with our email, so it seems that ProtonMail defaults to "0", which is the beggining of unix epoch - 1st January 1970. I'll sort it out today.

**Comment by pzduniak** [comment]
Fixed in lavab/mailer@890478c81752ba921eb4d389f80f47cb5af11d30
