### ISSUE TITLE
Emails between secure providers are not secure

### ISSUE THREAD

**Issue by TurkeyMan** [lavab/web#708]
I didn't see a record of this issue, but I think it's the single most important issue to resolve shared by all the emerging secure email providers.
Without cooperation between secure email providers to make sure all emails between providers are fully secure, I don't see how we can ever expect a world where peoples email communications are reliably secure. I already have friends scattered between at least Lavaboom, ProtonMail, Tutanota, etc.

Can this issue be updated regularly with progress on the issue? It is of critical importance.

**Comment by mlooz** [comment]
Right now there is a manual workaround if all providers allow exporting own public keys and importing foreign keys, both of which Lavaboom supports.
Step 1: Ask your recipient for their public key or get it from a keyserver
Step 2: Create contact within Lavaboom, add recipient's public key
Step 3: Send encrypted email

As of now, this email will be encoded with a pgp manifesto to hide the subject from prying eyes. Not all clients can read pgp manifestos yet, this is outside of our control.

For the automatic communication of public keys between secure email providers, an issue exists already: https://github.com/lavab/web/issues/495
