### ISSUE TITLE
Even if an email from Groove ends up in the inbox, it's unreadable

### ISSUE THREAD

**Issue by pzduniak** [lavab/web#709]
![ticket](http://qs.lc/dgs8h)

You can easily reproduce it yourself + here's the result

https://lavab.slack.com/files/pzduniak/F04SNN5T1/f2ifs3owph6dzvxajzld__1_.html

**Comment by let4be** [comment]
Because this email is not a valid html @pzduniak - it's malformed
We don't deal with malformed html email...

```<span style='font-weight:300;color:#AAA';>schmecklefrecker@lavaboom.com on May 14, 2015 at 7:15pm wrote:</span>```

> ';>
isn't valid

**Comment by let4be** [comment]
We might consider another ways of sanitizing but there are not so much alternatives available
tho, there is:
https://github.com/punkave/sanitize-html

**Comment by let4be** [comment]
hm hm hm on the other hand standard domParser has no problems parsing this piece of html...
so I might just run thru it as a first step, then rebuild the html before feeding it to $sanitize

**Comment by pzduniak** [comment]
Have you considered using that Google library that I linked?
18 maj 2015 10:56 "let4be" <notifications@github.com> napisał(a):

**Comment by let4be** [comment]
as far as I was able to understood it's not completely client based software
https://developers.google.com/caja/docs/gettingstarted/
They are referring to using their JS api i.e. code will be sent to the server.

Even if we manage to host our own server it won't be acceptable as goes against zero knowledge policy we follow.

**Comment by pzduniak** [comment]
https://code.google.com/p/google-caja/wiki/JsHtmlSanitizer
18 maj 2015 11:20 "let4be" <notifications@github.com> napisał(a):

**Comment by let4be** [comment]
@pzduniak this seems to be an epic library, it works on all malformed html where angular.js sanitizer fails miserable :)
nice
