### ISSUE TITLE
gulp wishlist

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#712]
- [x] when I update font file (/fonts/style.css) the less generation doesn't trigger even though its included in `lavaboom.less`
  - [x] jslint errors quite the server. would be nice to keep server running after showing the error
  - [x] can we have a `gulp` option like `--no-bower-update` to run the `gulp` without doing a bower update? That way my command for running the server everytime is `cd ~/Sites/lavaboom-web/ && npm install && gulp --no-bower-update`. This helps when the Internet is bad.

**Comment by let4be** [comment]
@piggyslasher you can use
`NO_BOWER_UPDATE=1 gulp` now
