### ISSUE TITLE
 Notitfications: "Looks like this browser is too slow..."

### ISSUE THREAD

**Issue by vLooz** [lavab/web#715]
For some days I'm getting those notifications:

![bildschirmfoto 2015-05-15 um 17 55 38](https://cloud.githubusercontent.com/assets/11177812/7678841/96b2698a-fd57-11e4-882d-a1ad2a2fe210.png)

What's that supposed to mean? I'm using the most actual safari and the client worked well with it. Speed was just fine.
I agree that we need a warning before signUp, especially before key generation, but not every time when I log in. Please consider changing it.

**Comment by vLooz** [comment]
And please get rid of the trash cans already. It's just a bad and confusing use of the icon.

**Comment by let4be** [comment]
Safari is poorly compatible with Lavaboom - tons of UX issues, starting from generally much slower crypto on some versions till poor support of file saving(which isn't going to change)

But I will check this one, probably some bug

**Comment by vLooz** [comment]
I understand and I can imagine that it's an absolute pain in the ass to code for a troubled platform like this. Still I'd like to ask you to keep in mind that between 4-14% (depends on the stats you look on) of all internet users use safari for desktop (iOS makes even has 43% marketshare) and they don't really care what problems there are in the development. They just want to use Lavaboom with their favorite platform and get frustrated if it's not working. So on the long run, to just abandon Safari and accept bad UX for Safari users is not an option.

**Comment by let4be** [comment]
It's actually weird, @vLooz please post browser version string
and if possible open the developer console, print window.crypto there in an input and show me the value

regarding http://caniuse.com/#feat=cryptography
the latest Safari should support webcrypto

generally if openpgp can't use webcrypto Lavaboom works slower(especially key generation and large emails/attachments)

we may remove the notifiation or make it appear just once(but then most users just close it and forget)

**Comment by vLooz** [comment]
from a UX-POV this would be the options:

A) (best): We can run Lavaboom an Safari at competitive speeds. No need for any user bothering 
B) We warn her once during SignUp, so she doesn't close the window during KeyGeneration, because it's too slow. Apart from everything is so quick, we don't need to do anything about it.
C) We only warn before SignUp and in situations, when the user is seriously slowed down at what he wants to do. 
D) We do it like it's now: we warn everytime and train the user to ignore notifications alltogether - but only after she got seriously annoyed for several times ;-)

**Comment by let4be** [comment]
Okay I got what you're saying @vLooz sounds totally reasonable
will change how we emit notifications in the next update

**Comment by vLooz** [comment]
Sounds good @let4be! 
Apologies for my grumpy tone today! I had a bad weekend.

**Comment by piggyslasher** [comment]
trash can icons were removed last week.

**Comment by vLooz** [comment]
on the .com version or the dev branch @piggyslasher?

**Comment by vLooz** [comment]
on the .com version or the dev branch? @piggyslasher

**Comment by piggyslasher** [comment]
@vLooz - can we close this? I've already removed the trash icon ages ago.

**Comment by vLooz** [comment]
Yes, let's close it for now.
