### ISSUE TITLE
Inbox: Reply-button-bar is masking mail content

### ISSUE THREAD

**Issue by vLooz** [lavab/web#722]
@flixi just let me know, that he doesn't like the way, the "reply-button-bar" is overlaying the mail content

![bildschirmfoto 2015-05-18 um 15 18 38](https://cloud.githubusercontent.com/assets/11177812/7681526/3d1853c0-fd71-11e4-92e9-f3371ae79fad.png)

I'd prefer if there is a horizontal stripe (44px high) of extra free space of at the end of every mail, where the button-bar is located without masking anything. 

The same time we might think about reducing the button-bar. It proved to be a big to large and dominant in everyday use. I'd recommend to change it to this:

![2015-05-19_move 3 buttons into mail-2-04](https://cloud.githubusercontent.com/assets/11177812/7704329/062ef530-fe3e-11e4-9b32-7a6ee69bbf38.png)

It button bar will sit right in this new free stripe, next to the bottom end of the mail. The button at the far right is right-aligned with the textblock at the top of the mail (the one providing date & time).

connected to issue https://github.com/lavab/web/issues/350

**Comment by piggyslasher** [comment]
So were completely removing the  gray background and shoeing it on hover?

**Comment by vLooz** [comment]
Yes, exactly. 
The Buttons become visible, when the cursor hovers anywhere over the mail.
