### ISSUE TITLE
hexadecimal string in new messages

### ISSUE THREAD

**Issue by srpelissier** [lavab/web#723]
I'm accessing the client using Firefox on linux. Last week-end the laptop crashed badly: it could not boot. Luckily I was able to restore the filesystem such that it could start, but I could not log in the account I was using before: I made a new one. Until then the laptop was working fine.

Then I noticed a problem and realized, with your support's help, than my passphrase was gone. After retyping the passphrase I was able to see my inbox. But whenever I compose a new message I see a 16 bytes hexadecimal string in the body, it was not there last week. An example: 
e441fd206aee50d378ce1330a5fa5f17. (1)

Everytime I log out and back in, I need to re-enter the passphrase, maybe that's expected. (2)

Are (1) and (2) actual problems? Are they related? Is that related to the crash which prevents me from logging in under my old linux account?

**Comment by srpelissier** [comment]
Now using 0.3.4, same thing.

**Comment by let4be** [comment]
Thank you for the report @srpelissier 
I think I know where it grows from...

**Comment by let4be** [comment]
> Everytime I log out and back in, I need to re-enter the passphrase
You can select "this is a private PC", so it will remember you for some time
without this session expires after tab close and you will need to re-enter login&&pasword to get back.

**Comment by srpelissier** [comment]
OK. There was another issue. (1). Is that expected?

**Comment by let4be** [comment]
(1) should be fixed now starting from 0.3.5
please check and let us know
