### ISSUE TITLE
Routing improvements

### ISSUE THREAD

**Issue by andreis** [lavab/web#728]
1. Make it so that clicking on the logo or Inbox goes to `https://lavaboom.com`. This will make for pretty (and backwards-compatible) URLs when bookmarking for example.
2. ~~Change `https://lavaboom.com/label/Sent` to `https://lavaboom.com/sent` for default/system labels. Custom (i.e. user-defined) labels will use the `/label/:name:` format.~~ Never mind, just make label names lowercase. e.g. `Sent` becomes `sent`.

**Comment by andreis** [comment]
Wrt the plugin architecture, the router should configure itself dynamically using plugin manifests. For example, core plugins like the "email viewing" plugin :smile: will declare it uses `/label/:name:` URLs, and so on. Then the router should build itself from the information provided.

Does this sound reasonable, @let4be?

**Comment by andreis** [comment]
I'm derailing this into a plugin conversation, but I'd just like to mention that plugins are only built once, at "compile" time (i.e. when running gulp). JS is already a pretty crappy choice for security, allowing `web` to load plugins at runtime would be a gaping security hole. To summarise, when building you can choose which plugins you want to use, and then the build gets hashed and optionally signed.

**Comment by let4be** [comment]
Sounds good @andreis, need to test how this works when routes are being declared across dependant angular.js modules that belong to the same app...

**Comment by let4be** [comment]
`https://github.com/lavab/web/blob/master/src/js/helpers/angularApplication.js` will help us in this :)
