### ISSUE TITLE
links not clickable

### ISSUE THREAD

**Issue by srpelissier** [lavab/web#731]
Version 0.3.5.

The links in the mails I received from hello@lavaboom.com at the beginning cannot be clicked. For example, in the message "Subject:Getting started with Lavaboom" is a link Go to contacts: nothing happens when I click on it.

**Comment by piggyslasher** [comment]
@pzduniak - I can help you with formatting this if you send me the html.

**Comment by let4be** [comment]
Thank you for the report @srpelissier ;)
It's new sanitizer, fix is on the way

**Comment by let4be** [comment]
Will deploy in ~1 hour with other fixes

**Comment by srpelissier** [comment]
thanks for the fix
