### ISSUE TITLE
Key import not working

### ISSUE THREAD

**Issue by mrgnz** [lavab/web#735]
I tried to import the json key file into lavaboom because I created it on a mobile device and now want it on another computer. The machines are running linux, (fedora 21 or arch). I tried it with google chrome and with firefox, both the latest versions.

After clicking on import, I have to chose a file I want to import. After navigating to the file and selecting it I click on ok to proceed. Then nothing happens. The selection window disappears and I see the security page again. There is no indication, that the browser is doing something. No loading sign, nothing. Still the only clickable button on the security page is to import a key.

**Comment by let4be** [comment]
Hey @mrgnz 
What Lavaboom version is displayed in the left bottom corner?
Are there any errors in the developer console(F12)?

Thank you for the information

**Comment by mrgnz** [comment]
The version is 0.3.6

console output is
added from state is main.settings Array[2]
ctrlSettingsSecurity.js:47keyring-updated Array[0]
cryptoKeys.js:61 skip public key import - already existing
095a6cfbefd9d3810fa7501f9d617de6b7b0f479
crypto.js:181 initialize crypto with  Object {isPrivateComputer: false,
isShortMemory: true, email: "mrgnz@lavaboom.com"} provided Object {}
cryptoKeysStorage.js:36 CryptoKeysStorage created, isPrivateComputer: false
isLavaboomSync: true loadOnlyForEmails: ["mrgnz@lavaboom.com"]
isLoadDecrypted: true
LavaboomAPI.js:44 Calling contacts.list [] ...
lavaboom-api.js:203 sockjs: sending a message
{"id":"17","type":"request","method":"GET","path":"/contacts","body":"null","headers":{"Authorization":"Bearer
92SuoEWD0IKeeWL2N2oW"}}
ctrlSettingsSecurity.js:47 keyring-updated []
ctrlSettingsSecurity.js:47 keyring-updated []
ctrlSettingsSecurity.js:47 keyring-updated []
LavaboomAPI.js:49 contacts.list:  Object {body: Object, headers: Object,
id: "17", status: 200, type: "response"}

let4be <notifications@github.com> schrieb am Di., 19. Mai 2015 um 12:14 Uhr:

**Comment by let4be** [comment]
Could you please open .json keyring you exported before and check is there a 
```
"prv": [ ... ]
```

entry which contains `-----BEGIN PGP PRIVATE KEY BLOCK-----`

**Comment by mrgnz** [comment]
There is the prv section but it contains nothing: "prv": []

let4be <notifications@github.com> schrieb am Di., 19. Mai 2015 um 12:32 Uhr:

**Comment by let4be** [comment]
it means your private key wasn't exported/properly generated, it could happen due to various reasons
currently `web` should show a notifications regarding the import result

regarding your problem you can only generate a new key pair now., would be nice to get more details on how you generated and exported this keyring backup in the first time - most likely something went wrong at this stage

**Comment by mrgnz** [comment]
Well, I used google chrome on my Android device as lavaboom did not show
the notice that mobile devices are not supported until after the key
generation. I then used the browser to export it, uploaded it to a server
of mine and downloaded the json file on my own desktop machine. thats it
basically.

let4be <notifications@github.com> schrieb am Di., 19. Mai 2015 um 14:29 Uhr:

**Comment by let4be** [comment]
For now I can only advice you into generating a new key(it's supported from settings/security)
