### ISSUE TITLE
SignUp / KeyGeneration: We need time estimates for different browser types

### ISSUE THREAD

**Issue by vLooz** [lavab/web#741]
Initial Key Generation might take some minutes depending on the browser type and version.
To avoid that confused users may think it has frozen and close the window, we need to give them a rough time estimate how long it might take.

We'd like to do it like this:

< 10 seconds: no estimation displayed, because key generation is more or less instant.

10 seconds - 5 mins: "key generation might take up to 5 minutes. Do not close this window."

> 5 mins: We show a warning screen before (!) the first SignUp screen: "Dear User, because your browser is an older version, Key generation at the end of the SignUp might take up to 15 minutes. To enjoy Lavaboom at full speed, we recommend to first update your browser to the newest version."

When the user still wants to continue anyways, we display a bit more info about the reason why key generation takes so long: 
"Like mentioned before, you are using an older version of your browser, which doesn't support "new tech". Without it we need to use "old tech", which is far slower.  
When you want to use your the waiting time, you could learn more about Lavaboom (link)."

**Comment by let4be** [comment]
This is already implemented but maybe I will need to tweak settings.
Before the actual 4096 bit key gen operation I execute small performance test to estimate the ETA
