### ISSUE TITLE
Replying is hard in threads with long emails or lots of replies

### ISSUE THREAD

**Issue by pzduniak** [lavab/web#743]
There should be a button for easy replying to longer threads, as it will probably fit our UI well. Gmail does it otherwise by collapsing old, already read emails:

![Example](http://qs.lc/eqzsq)

**Comment by let4be** [comment]
we have this now
![image](https://cloud.githubusercontent.com/assets/4147061/7978654/66c597f0-0aa0-11e5-8fef-64046c8ec7e5.png)
