### ISSUE TITLE
Left Panel: Please change icon color back to #9D9FA3 in not-selected state

### ISSUE THREAD

**Issue by vLooz** [lavab/web#748]
currently the icons are white (#ffffff), even when the are not selected or hovered upon. It's too bright and it's hurting Andreis' and my eyes, everytime we look on it - thats why the important label ;-)

Please change it back to #9D9FA3!

![bildschirmfoto 2015-05-19 um 17 36 25](https://cloud.githubusercontent.com/assets/11177812/7706945/9eb4c4a6-fe4d-11e4-80e2-af22527c9335.png)

**Comment by piggyslasher** [comment]
I've fixed this a few days ago already. its on develop branch.

**Comment by vLooz** [comment]
ah, great! sorry for bothering you.

**Comment by vLooz** [comment]
I just checked it and we might have a little problem here. The colors are the same but they don't look the same probably because of antialiasing effects. See screenshots.

We need to enhance the "white-ness" of the icon and text in the selected fields somehow. Do you have any idea? @piggyslasher 
 
![bildschirmfoto 2015-05-19 um 19 41 24](https://cloud.githubusercontent.com/assets/11177812/7709740/76408caa-fe5f-11e4-9195-94aefc8d1fb5.png)

**Comment by piggyslasher** [comment]
again the bug with the light text on a non-white background. yes. let me check this. its possible.

**Comment by vLooz** [comment]
cool! appreciated! Weren't you on your way to sleep btw? ;-)
