### ISSUE TITLE
Mail content not shown from non-encryption sender

### ISSUE THREAD

**Issue by vLooz** [lavab/web#750]
Posting this on behalf of @JuliaZimmermann 
She is using google chrome on a brand-new iMac. 
The sender was not using encryption.

An important mail content was not shown at all. 
Let me know if you guys need more info. 

![bildschirmfoto 2015-05-19 um 15 19 17](https://cloud.githubusercontent.com/assets/11177812/7707213/12f7abd4-fe4f-11e4-840f-ff5b21faaa0a.png)

**Comment by let4be** [comment]
Impossible to troubleshot without logs, please open such issues only with provided logs or at least original email content(download email button)
Reopen if you have this details.
