### ISSUE TITLE
Inbox: Refresh Icon

### ISSUE THREAD

**Issue by vLooz** [lavab/web#751]
It looks like we need to give impatient users (and those who don't trust the up-to-date-ness of our client) a way to refresh the inbox.

For Trackpad and Smartphone/Tablet use, @andreis suggested a pull-down-gesture of the inbox list to trigger refreshing it. For good old Desktop Pc users and mouse click lovers, we need a icon for that. I suggest to put it in the right corner of the mail list panel:

![icon_refresh inbox](https://cloud.githubusercontent.com/assets/11177812/7708168/3945f340-fe54-11e4-9830-1c46a8d623a0.png)

Let me know @piggyslasher once you start implementing this. I'll provide you with the refresh icon then.

**Comment by piggyslasher** [comment]
will add a button for @let4be to code the function.

**Comment by vLooz** [comment]
nice! Is there an easy way to animate that things, so it will rotate? The color could turn full white, while it's doing it.

**Comment by piggyslasher** [comment]
can. i'll add a loading mode that has the icon rotate and be white.

**Comment by piggyslasher** [comment]
https://slack-files.com/files-pri-safe/T0393U6R6-F04U2F6QS/icon_refresh_inbox.svg?c=1432057053-18560711801c07720cc6200aa1bc042c5b2fb37a
for reference. here's the icon.

**Comment by vLooz** [comment]
nice! looking forward to see it! :-)

**Comment by andreis** [comment]
Me too! :smiley:

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/7957735/41bb1022-0a1c-11e5-91f5-08dc65eb8837.png)

![image](https://cloud.githubusercontent.com/assets/1991125/7957740/4d295efa-0a1c-11e5-830f-3ec5571cdf06.png)

Assigning to @let4be so he can map the refresh button properly.

**Comment by let4be** [comment]
@piggyslasher in which branch is it?

**Comment by let4be** [comment]
Seriously... I searched this issue for 15 min and it's closed, lol
Whatever, refresh button should work now
