### ISSUE TITLE
Error "Expected to see a private key..."

### ISSUE THREAD

**Issue by paulhugel** [lavab/web#753]
.037 served by marge
38.01 Firefox
10.10.3 OSX
https://mail.lavaboom.com/settings/security
import secret/pub key pair produces error  "Expected to see a private key..."
failed to import working sec/pub key pair  Paul Garrett Hugel A3F48305

![screen shot 2015-05-19 at 2 42 17 pm](https://cloud.githubusercontent.com/assets/6466830/7717172/576b735c-fe38-11e4-9e9b-b7c60a865423.png)

**Comment by andreis** [comment]
Thank you for your report @paulhugel 

Design comment, do we need a trash bin icon next to `OK`? I know it confused me when I first saw it. Also, cleaner == better (?)
cc @vLooz

**Comment by andreis** [comment]
Also, @paulhugel, here's how the UI should look like: https://github.com/lavab/web/issues/737

We're doing our best to implement that and adjust it for most browsers and devices.

**Comment by let4be** [comment]
It seems to be an error, will fix

**Comment by piggyslasher** [comment]
Trash icon was removed couple of weeks back. It is in /lavab/develop.
