### ISSUE TITLE
Inbox email not charging

### ISSUE THREAD

**Issue by mizmiz666** [lavab/web#754]
![lavaboom_bug](https://cloud.githubusercontent.com/assets/4542812/7721344/6cc6b214-fec6-11e4-9a9f-304e80785871.png)

Cannot access the inbox since at least web version 0.3.4 up to 0.3.7.

The bug occurs on every browser I tried (Tor Browser, Firefox 37-38, Chromium, etc.)

Note that everything else is accessible.

Here's the error log:

"Error: t is undefined
[74]</module.exports</a.formatAddress@https://mail.lavaboom.com/js/appLavaboom-177080d908420d56d783023fcfa7a89e84b8b8f5.js:6622:2054
[74]</module.exports</a.parseAddresses/<@https://mail.lavaboom.com/js/appLavaboom-177080d908420d56d783023fcfa7a89e84b8b8f5.js:6622:1953
[74]</module.exports</a.parseAddresses@https://mail.lavaboom.com/js/appLavaboom-177080d908420d56d783023fcfa7a89e84b8b8f5.js:6622:1904
c@https://mail.lavaboom.com/js/appLavaboom-177080d908420d56d783023fcfa7a89e84b8b8f5.js:6626:612
r/<@https://mail.lavaboom.com/js/appLavaboom-177080d908420d56d783023fcfa7a89e84b8b8f5.js:6626:1676
tryCatch@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:2701:37
invoke@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:2874:22
defineGeneratorMethod/Gp[method]@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:2910:14
onFulfilled@https://mail.lavaboom.com/js/utils-9f5edb9bda3f4b8a225d68007c1e1822a8c26362.js:2026:15
f/<@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6590:113
Pe/this.$get</n.prototype.$eval@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6604:11
Pe/this.$get</n.prototype.$digest@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6601:98
Pe/this.$get</n.prototype.$evalAsync/<@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6604:100
e@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6518:72
nf/n.defer/c<@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6522:155
" utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6580:324

"Error: e is null
[57]</module.exports</d.unfold@https://mail.lavaboom.com/js/appLavaboom-177080d908420d56d783023fcfa7a89e84b8b8f5.js:6554:189
e/this.put/<@https://mail.lavaboom.com/js/utils-9f5edb9bda3f4b8a225d68007c1e1822a8c26362.js:6757:1151
e/this.put@https://mail.lavaboom.com/js/utils-9f5edb9bda3f4b8a225d68007c1e1822a8c26362.js:6757:1115
w/<@https://mail.lavaboom.com/js/appLavaboom-177080d908420d56d783023fcfa7a89e84b8b8f5.js:6554:2671
tryCatch@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:2701:37
invoke@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:2874:22
defineGeneratorMethod/Gp[method]@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:2910:14
onFulfilled@https://mail.lavaboom.com/js/utils-9f5edb9bda3f4b8a225d68007c1e1822a8c26362.js:2026:15
f/<@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6590:113
Pe/this.$get</n.prototype.$eval@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6604:11
Pe/this.$get</n.prototype.$digest@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6601:98
Pe/this.$get</n.prototype.$evalAsync/<@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6604:100
e@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6518:72
nf/n.defer/c<@https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6522:155
"

**Comment by let4be** [comment]
@mizmiz666 thank you for the report :)
I'll check and let you know

**Comment by let4be** [comment]
Should be fixed in develop branch, we will deploy this fix in a few days with all other updates
Keep an eye on `web` version, 0.4.0 is coming soon ;)

**Comment by mizmiz666** [comment]
Fixed indeed. Thank you very much.
