### ISSUE TITLE
Can't use password manager to sign in

### ISSUE THREAD

**Issue by Mitchou** [lavab/web#755]
I'm personally use Save in Cloud password manager with Chrome extension.
When I try to login in Lavaboom, I've got this message on both fileds:
This field is required
Username and password was paste correctly, but I have to enter a space and delete it to sucessful log in.

**Comment by let4be** [comment]
Thank you for the report @Mitchou 
bug was reproduced

**Comment by let4be** [comment]
tracked down to: https://github.com/angular/angular.js/issues/1460

**Comment by let4be** [comment]
Fix is in develop, will be deployed tomorrow with the rest of improvements/fixes

**Comment by piggyslasher** [comment]
Username field is still blank for me with LastPass. Password field is
filled in. This happened about two weeks ago. Before that it was okay. I
thought it was a bug with LastPass.

**Comment by Mitchou** [comment]
Bug came back !
