### ISSUE TITLE
HTTPS identity not verified

### ISSUE THREAD

**Issue by kalicki** [lavab/web#760]
![captura de tela 2015-05-20 as 10 31 43](https://cloud.githubusercontent.com/assets/3674885/7726884/97714794-fedb-11e4-9a65-e8241d3f45d4.png)
Chrome 42

https://www.ssllabs.com/ssltest/analyze.html?d=mail.lavaboom.com

**Comment by pzduniak** [comment]
Could you tell me what hashes are used in your chain?

**Comment by pzduniak** [comment]
https://forum.startcom.org/viewtopic.php?f=15&t=15929

Probably somehow also applies to Ubuntu.

**Comment by kalicki** [comment]
I didn't understand what you want ...

**Comment by pzduniak** [comment]
Let me explain it. First of all click the lock icon, go to connection and open certificate information. Then go to details and try to find SHA1 there. If it's not there, then click on "certification path" (or something similar), open the second certificate in the path (intermediate cert), go to its details and again try to find SHA1. If there's no "SHA1" anywhere, then I don't understand what causes the bug.

**Comment by kalicki** [comment]
![captura de tela 2015-05-20 as 12 53 48](https://cloud.githubusercontent.com/assets/3674885/7730230/60962b72-feef-11e4-8934-ce564f432603.png)


This is only information SHA-1 via fingerprints, is this?

**Comment by pzduniak** [comment]
Could you take a screenshot of the StartCom Class 2 Primary Intermediate Server CA info? Is SHA256 on the fingerprints list?

**Comment by kalicki** [comment]
![captura de tela 2015-05-21 as 08 44 20](https://cloud.githubusercontent.com/assets/3674885/7747936/18c06c52-ff96-11e4-8984-df84507173fd.png)
![captura de tela 2015-05-21 as 08 44 22](https://cloud.githubusercontent.com/assets/3674885/7747937/19477eea-ff96-11e4-98c1-45ed4de228a0.png)

**Comment by kalicki** [comment]
@pzduniak ideia?

**Comment by kalicki** [comment]
For some reason, is nromal!!!

**Comment by joergG** [comment]
can we close this?

**Comment by kalicki** [comment]
yes

**Comment by kalicki** [comment]
@joergG  This error is happening again... in https://mail.lavaboom.com/

**Comment by kalicki** [comment]
![captura de tela 2015-07-17 as 10 00 04](https://cloud.githubusercontent.com/assets/3674885/8747570/c1c2cb0a-2c6a-11e5-8ff4-411f67686cb4.png)
