### ISSUE TITLE
Subject line sometimes not properly encoded

### ISSUE THREAD

**Issue by jrselzer** [lavab/web#767]
Sorry, I have not found a way to reproduce this behaviour. Hope you have a chance to examine it anyway.

Sometimes even mails I wrote and sent with Lavaboom have broken subject lines like

=?utf-8?Q?Cryptoparty-Ank=C3=BCndigungstext?=

It actually should read "Cryptoparty-Ankündigungstext" (with a German u umlaut).

**Comment by pzduniak** [comment]
Here we go again, @let4be you implemented client-side encoding, right?
22 maj 2015 07:06 "jrselzer" <notifications@github.com> napisał(a):

**Comment by let4be** [comment]
not yet, still in todo

**Comment by pzduniak** [comment]
Is this a Lavaboom to Lavaboom email?

**Comment by pzduniak** [comment]
Ah yes, I finally understand it. lavab/web needs to support decoding of the subject lines.

**Comment by let4be** [comment]
Duplicate of https://github.com/lavab/web/issues/746

**Comment by jrselzer** [comment]
It only seems to affect Lavaboom mails going to external addresses, but I'll keep testing.
