### ISSUE TITLE
UI glitch in Settings in Ubuntu > Firefox

### ISSUE THREAD

**Issue by andreis** [lavab/web#770]
Probably there is more stuff like this. Installing VirtualBox has paid off :smile:

![img](http://i.imgur.com/fZJPEbG.png)

**Comment by piggyslasher** [comment]
yikes. @mlooz - you were using FF/Linux quite a bit to test the system right? I'll check on my VirtualBox later.

**Comment by andreis** [comment]
The joys of *modern* web programming/design.

**Comment by mlooz** [comment]
Will test tomorrow morning.

On 25. Mai 2015 13:49:44 MESZ, piggyslasher <notifications@github.com> wrote:
>yikes. @mlooz - you were using FF/Linux quite a bit to test the system
>right? I'll check on my VirtualBox later.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/lavab/web/issues/770#issuecomment-105216755

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mlooz** [comment]
Can reproduce - I just never saw how it was supposed to look and didn't recognize it as a bug! Thought it was some obscure design which is hip right now among the UI crowd. ;-)

Will keep an eye open for similar things.
