### ISSUE TITLE
made changes to jade files, but new gulp system is trying to lint it :)

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#783]
I just saved the `_compose_email.jade` file and it went through a linting process.
![image](https://cloud.githubusercontent.com/assets/1991125/7806901/bc9c9834-03b8-11e5-8929-6ba82a4d4b82.png)

if possible please push fix for this as its wasting time when I edit jade files :) thanks.

**Comment by let4be** [comment]
lol, oh yea :D
