### ISSUE TITLE
Jumbled Subject Titles

### ISSUE THREAD

**Issue by joojoopills** [lavab/web#786]
Apologies if this has been brought up before, but when forwarding emails or checking them in your Sent folder, they show up with odd symbols.

Examples:
=?utf-8?Q?Fwd:_How's_it_going=3F?=
=?utf-8?Q?Hi?=

**Comment by let4be** [comment]
Known issue, we're working on this and update is coming today-tomorrow with lots of other fixes
caused by https://github.com/lavab/web/issues/746

**Comment by joojoopills** [comment]
Thanks again! You guys are doing great work.

**Comment by piggyslasher** [comment]
You're welcome. Thanks for supporting us by creating and issue.
