### ISSUE TITLE
Changed subject when forwarding, but new subject name isn't used. Mail uses older subject.

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#794]
Editing of subject during forward doesn't work.

**Comment by let4be** [comment]
It's how feature is implemented from API side
I think this is by design, @pzduniak ?

**Comment by pzduniak** [comment]
But there is no forwarding impl in the API :o

**Comment by let4be** [comment]
Maybe this was fixed, but I can't reproduce this on the latest develop
reopen if find again, this time with logs
