### ISSUE TITLE
Email view looks like crap

### ISSUE THREAD

**Issue by andreis** [lavab/web#800]
![screen shot 2015-05-28 at 11 21 35](https://cloud.githubusercontent.com/assets/1249760/7856808/32419188-052c-11e5-9e5a-b5b00aca6a24.png)

Chrome 43.0.2357.81 (64-bit)
OS X 10.10.3

What can we do to make it better?

**Comment by piggyslasher** [comment]
its on develop. needs to be merged. #788

**Comment by piggyslasher** [comment]
latest version is on .com @andreis

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/7858170/c45f7f58-0568-11e5-8c30-f1babc1407fc.png)

**Comment by andreis** [comment]
Fantastic!
