### ISSUE TITLE
Contacts gone wrong

### ISSUE THREAD

**Issue by andreis** [lavab/web#809]
I18n doesn't work.
Adding a contact doesn't work.

https://gist.github.com/andreis/3abadc348242eddb6e96

![screen shot 2015-05-28 at 22 09 41](https://cloud.githubusercontent.com/assets/1249760/7870015/b2bf3360-0586-11e5-859b-3842298b00e6.png)

**Comment by let4be** [comment]
Damn... It worked for sure on my PC. Will check the first thing tomorrow morning.

**Comment by andreis** [comment]
Just want to add that this is a bug reported by Julie, but she doesn't have a Github account yet :)

**Comment by andreis** [comment]
Also, wow, quick fix. Well done!
