### ISSUE TITLE
Language auto-detect

### ISSUE THREAD

**Issue by let4be** [lavab/web#814]

**Comment by let4be** [comment]
First needs https://github.com/lavab/api/issues/141 implemented

**Comment by andreis** [comment]
Can't the mirroring of the `Accept-Language` header be done by whoever is serving the static files? I'm pretty sure this is not an API feature. The API should work the same no matter what language a client chooses to display.

**Comment by let4be** [comment]
you're right @andreis it's not an API ticket
currently we use nginx to serve static files so we could just add this logic here

I need this before user logs in, as early as possible to show `web` in the most suitable language
And regarding http://stackoverflow.com/questions/1043339/javascript-for-detecting-browser-language-preference
using navigator.language is not the best idea(i.e. we need to examine request language headers)

**Comment by andreis** [comment]
I wasn't suggesting using that, I was suggesting saving the user's language preference in Settings.
