### ISSUE TITLE
"This is not spam button" doesn't behave correctly if email was put in spam folder by spam filter.

### ISSUE THREAD

**Issue by kevnu** [lavab/web#815]
I received an email that went straight to my spam folder. It was not spam so I clicked the "This is not Spam"  button above the email. I expected the email to be put back in my inbox, but instead it seems like it got deleted.

I marked a test email from my inbox as spam and then selected the "This is not Spam" button which resulted in the email going back to my inbox, so it looks like the problem is for emails that go directly to the spam folder.

**Comment by pzduniak** [comment]
Fixed in mailer.
