### ISSUE TITLE
Empty email!

### ISSUE THREAD

**Issue by flixi** [lavab/web#817]
https://gist.github.com/flixi/e2f53bcfb1f2d88753f9
![bildschirmfoto 2015-06-02 um 20 15 25](https://cloud.githubusercontent.com/assets/707993/7943603/c7d7d3b4-0965-11e5-8ba5-220469068585.png)
Emails from Twitter don'T work, and from DHL neither, the same issue I suppose.

**Comment by piggyslasher** [comment]
I'm also getting this... all text seem to be stripped. here's the sent email in gmail
![image](https://cloud.githubusercontent.com/assets/1991125/7952791/ec66b046-09ed-11e5-9359-453b86562296.png)

Here's the received email in lavaboom:
![image](https://cloud.githubusercontent.com/assets/1991125/7952793/fa834d9c-09ed-11e5-969c-673c13cadf3a.png)

**Comment by piggyslasher** [comment]
ok this is even more f'd up. I replied to this email (the image was there, but no text) and i received this in gmail:
![image](https://cloud.githubusercontent.com/assets/1991125/7952850/bfe38106-09ee-11e5-89af-9ae2d490c6e3.png)

**Comment by let4be** [comment]
I just checked and indeed - only picture shows and no text.
The thing is email came without text from API, most likely Mailer somehow damaged it before encoding and giving via API
see: https://github.com/lavab/mailer/issues/51

**Comment by let4be** [comment]
Actually it seems it was mistake in `web`... Going to be fixed soon

**Comment by let4be** [comment]
I've fixed very similar bug in `web` but those issues are confirmed to be different, @pzduniak asap

**Comment by let4be** [comment]
Need this to be worked on: https://github.com/lavab/mailer/issues/51

**Comment by joergG** [comment]
@let4be - can we close this issue? since we have a separate bug in lavab/mailer#51?

**Comment by let4be** [comment]
sure, this is caused by lavab/mailer#51 and appear only on unencrypted emails
most likely mailer has issues with parsing

There were some debates about switching to front-end email parsing - exactly the same we do for pgp/mine now, but looks like we postponed this idea.

It could simplify whole thing and help to get rid of some bugs

@andreis what's your input on this
because right now we have front-end mail parsing + back-end mail parsing on mailer's side

**Comment by joergG** [comment]
so FE-mail parsing would bring huge benefits? how much effort would that be? (just to get a feeling)
