### ISSUE TITLE
Quotation support

### ISSUE THREAD

**Issue by let4be** [lavab/web#821]
How should we ever process quotes in emails, there is no single standard on this but it would be nice to have quotes formatted in the same style for better UX
see: http://en.wikipedia.org/wiki/Posting_style

basically each email client uses their own format, + there are 2 modes - html and text...

currently it's a bit of a mess, we have own html template for this:

https://github.com/lavab/web/blob/feature/advanched-email-styling/src/apps/LavaMail/blocks/inbox/repliedEmail.jade

and it uses semantic markup, similar as gmail does(`blockquote` tag)

But it doesn't seem to be enough, for example we display headers differently(sent by ..., date, bla-bla-bla)

@andreis: ideas?

**Comment by piggyslasher** [comment]
we can just use the angular ui-bootstrap collapse. let me see if i can get this to work. it should be straightforward.

**Comment by let4be** [comment]
The problem is not how to display this, but how to recognize the pattern when quoting happens from another client like gmail, thunderbird whatever

**Comment by andreis** [comment]
As you said, there's no single standard. Quoted emails can be before or after reply, can use HTML tag or `>` or tabs. We only need to support the basic scenarios, to figure out what data to hide. It's not a huge issue if we miss 10% of emails, we can refine this later.

**Comment by piggyslasher** [comment]
@let4be can we close this for now? we now have collapsed replies.
