### ISSUE TITLE
Style blockquote-collapse button

### ISSUE THREAD

**Issue by let4be** [lavab/web#826]
![image](https://cloud.githubusercontent.com/assets/4147061/8004878/5b6fc064-0b8c-11e5-992b-caf2a054b5db.png)

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/8034419/05ba327c-0e1a-11e5-85d8-89389ed2f76e.png)

**Comment by piggyslasher** [comment]
@vLooz - temporary styling for now. let me know if you want something better.

**Comment by vLooz** [comment]
Looking good so far. Let's leave it like this for now :-)

**Comment by piggyslasher** [comment]
@let4be - assigning this to you. When we click the refresh button we have duplicate collapse toggles.
![image](https://cloud.githubusercontent.com/assets/1991125/8035285/c38c1994-0e21-11e5-99d3-ee318cc59a2c.png)
