### ISSUE TITLE
Style import contacts window

### ISSUE THREAD

**Issue by let4be** [lavab/web#830]
I had some free time while most of other things were blocked and implemented basic import contacts functionality
see: https://github.com/lavab/web/issues/663

This needs styling
![image](https://cloud.githubusercontent.com/assets/4147061/8007661/e97c9d14-0ba5-11e5-9944-5eb3aaee4309.png)

**Comment by let4be** [comment]
related: https://github.com/lavab/web/issues/826

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/8034932/1de8e82a-0e1f-11e5-998b-0e5ce549df4b.png)

@vLooz - this should be good for now i think

**Comment by vLooz** [comment]
nice! well done :-)
