### ISSUE TITLE
Roboto is still fetched from a remote server

### ISSUE THREAD

**Issue by pzduniak** [lavab/web#840]
https://www.reddit.com/r/privacy/comments/391t2c/ama_with_the_german_team_of_lavaboom/crzoc04

**Comment by let4be** [comment]
I already said about this :)
@piggyslasher asap

**Comment by piggyslasher** [comment]
#490 - will make this a priority. roboto is a massive font that was hard to encode as baseURI because we were using 4 font weights. now were using two. let me have another go.

**Comment by piggyslasher** [comment]
i've now gotten dataURI to work. I'm trying to see how I can reduce file sizes. I want to only load two weights per device (300, 400 for retina & 400,500 for non-retina).

http://aurelio.audero.it/blog/2013/07/02/how-to-solve-the-problem-of-font-face-inside-media-queries/#better-approach-updated

Seems like using dataURI has its disadvantages. Will check this again. But for now, the develop branch has the update. No more Google.
