### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by let4be** [lavab/web#850]
use 

```git fetch --all && git reset --hard origin/master```
instead of `git pull`

so we could rollback when needed and use the same deploy command
what do you think @pzduniak ?

**Comment by pzduniak** [comment]
Is there any particular reason for that? If you keep a clean copy of the
repo on the server, you can just git pull, docker build and em and then
start it.

**Comment by let4be** [comment]
well I had to do `git reset --hard` on master today in order to rollback to the previous version
in this way `git pull` didn't fetch this rollback, it simply thought local version has more recent commits

**Comment by pzduniak** [comment]
It's only a command that you're running. Right now you prettymuch have to `cd ~/web && git pull && docker build -t "lavab/web" . && docker rm -f web-master && ~/docker/runners/web-master.sh"

**Comment by let4be** [comment]
oh right, being stupid today ^^
