### ISSUE TITLE
Class .global-mail-actions overrides .navbar-right-buttons

### ISSUE THREAD

**Issue by kalicki** [lavab/web#851]
The class (CSS/LESS) .global-mail-actions width cannot be 100%, otherwise it overrides the class .navbar-right-buttons

![lavaboom](https://cloud.githubusercontent.com/assets/3674885/8084851/a1e41268-0f63-11e5-8dd6-5cdb304e10f4.png)

**Comment by piggyslasher** [comment]
Thanks, fix is done. Put some extra padding on the `:last-child`. Should be
on development branch soon.

**Comment by kalicki** [comment]
And when aligning other and not only at last?

**Comment by piggyslasher** [comment]
using `pointer-events: none`. please check. on develop. related to #722. fixed.

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/8281479/f1549e38-191a-11e5-97ab-c801f9a051d5.png)
reopen if problem persists. should work fine now.
