### ISSUE TITLE
Style validation errors for password change in settings/security

### ISSUE THREAD

**Issue by let4be** [lavab/web#865]
![image](https://cloud.githubusercontent.com/assets/4147061/8178545/a53ca278-1417-11e5-872f-6ef5b0a0975d.png)

**Comment by vLooz** [comment]
![865_changepassword-05](https://cloud.githubusercontent.com/assets/11177812/8520708/1e50e154-23dd-11e5-845a-95b85ed37bd4.png)

**Comment by piggyslasher** [comment]
![image](https://cloud.githubusercontent.com/assets/1991125/8669195/109ded40-2a45-11e5-89f9-c6b92f239ab3.png)

**Comment by joergG** [comment]
@ALL - also new waffle-rule: when an issue is done (FE,BE,UI) from your pov, you'll do the dev-test and afterwards push it to testing. fvl and me (sometimes andrei) will test it and move it on then!

**Comment by vLooz** [comment]
Hey @piggyslasher. Do I understand this correctly, that you guys decided to use a reduced UI for the password handling instead of implementing my mocks? just for me to know.

**Comment by joergG** [comment]
@piggyslasher - like we said in the meeting, it's gonna stay in TESTING until fvl, andrei or I tested it  :-)
-> In this case it should be @vLooz, right?

**Comment by joergG** [comment]
@vLooz - could you have a look on staging  if this has been implemented correctly, please?

**Comment by vLooz** [comment]
staging is mail.lavaboom.io, correct @piggyslasher ?

**Comment by joergG** [comment]
@vLooz - yes

**Comment by vLooz** [comment]
To be honest, the password change area is more buggy then before.

**Comment by joergG** [comment]
@piggyslasher - did you actually merge this already?

**Comment by piggyslasher** [comment]
I merged it into develop but has @let4be put it on staging? And yes, the switch position is off. Fixed, will merge soon.

**Comment by joergG** [comment]
@piggyslasher - let us know when this is on staging.

**Comment by joergG** [comment]
@piggyslasher - let us know when this is on staging, please.

**Comment by piggyslasher** [comment]
It is there. Please check again.

**Comment by vLooz** [comment]
It's working well from my pov and we can push it to fix the error.
Still I would like to see my new UI implemented in the near future :)

**Comment by joergG** [comment]
@vLooz - what does this mean? is this specific issue solved? then we should push it to "to ship".

**Comment by piggyslasher** [comment]
Honestly, all this validation that we're using is redundant. I think we should just use the basic HTML5 validation next time @let4be. No need any angular stuff. Plus this method is completely mobile friendly.

http://www.the-art-of-web.com/html/html5-form-validation/
