### ISSUE TITLE
now that settings/security has been split to two pages, opening key to show details brings up a change password prompt

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#868]
clicking on this:
![image](https://cloud.githubusercontent.com/assets/1991125/8188955/9e88a5c0-148b-11e5-9a5e-db797b343517.png)

opens this:
![image](https://cloud.githubusercontent.com/assets/1991125/8188980/c2dc8554-148b-11e5-967b-04ad13bd06cb.png)

:D

**Comment by let4be** [comment]
wow, how did this happen :O
