### ISSUE TITLE
weird formating

### ISSUE THREAD

**Issue by resanden** [lavab/web#880]
![lb-weird](https://cloud.githubusercontent.com/assets/12735210/8336904/0cb99bc2-1aa8-11e5-91a0-83037b0577ec.png)

![lb-weird2](https://cloud.githubusercontent.com/assets/12735210/8336999/8ab54a6c-1aa8-11e5-9820-cca350ebdd9b.png)

firefox 38 on linux mint 17.1

**Comment by piggyslasher** [comment]
We pushed a lot of updates regarding this in the develop branch. It should be on  `.com` soon.

**Comment by piggyslasher** [comment]
Closing this for now. Please reopen if you still have issues.
