### ISSUE TITLE
Same icon used for Add Contact and Import Contact

### ISSUE THREAD

**Issue by StuartLRM** [lavab/web#883]
Issue Description
-----------------------
In the Contacts screen the icon for importing a contact (e.g. import csv or vCard) is the same as the icon for manually adding a contact (by entering their details)

Reproduction
------------------
1. Log onto https://mail.lavaboom.com
2. Navigate to Contacts or go to https://mail.lavaboom.com/contacts 
3. Observe that there are two identical icons near the top of the screen next to the Search function

See screenshot
![contacts_icons](https://cloud.githubusercontent.com/assets/10669126/8347210/dcfbc8fa-1b48-11e5-8da6-11f9678232c4.png)

**Comment by piggyslasher** [comment]
this has been fixed on our development branch. It should be on `.com` soon. Sorry about that.
![image](https://cloud.githubusercontent.com/assets/1991125/8374104/2301e4f6-1c25-11e5-8c25-6fec2e6eb5ca.png)
