### ISSUE TITLE
Not receiving emails sent to GoDaddy-forwarded email

### ISSUE THREAD

**Issue by KomorebiCo** [lavab/web#892]
I am not receiving emails to my GoDaddy email address. The domain is with GD, but the email is just a forwarding address to a Gmail account. I can receive emails addressed from Lavaboom directly to this same Gmail account.

I can post the GD settings if it will be helpful.

**Comment by andreis** [comment]
I'm sorry to hear that @KomorebiCo. Could you tell me if it works now?

**Comment by KomorebiCo** [comment]
Sorry for the delay. I am now receiving emails to the GoDaddy email immediately. 5 days ago I received an email to the same domain but there was an 18-hour delay.
