### ISSUE TITLE
DraftsFeature - Performance in Windows

### ISSUE THREAD

**Issue by joergG** [lavab/web#903]
Draft-Folder not displaying anything apart from loading-icon for several minutes. Sometimes the warning “page doesn’t answer” appears. [Jörg/Tested Windows 7/Chrome Version 43.0.2357.130 m AND Jörg/Tested Windows 7/with Firefox 39.0 (never seems to quit)]
![drafts_folder_performance](https://cloud.githubusercontent.com/assets/12829397/8527260/0fea3cbc-240c-11e5-89f2-428dfd66165b.jpg)

**Comment by let4be** [comment]
What cpu do you have? I hope it's not single core :)

**Comment by let4be** [comment]
Also made them loading in parallel, same as with threads
soon on .io

**Comment by joergG** [comment]
@let4be - It's an ancient DualCore (2,13GHz)  :-)

**Comment by joergG** [comment]
send a desktop-movie to @let4be - (too big for github)
problem still seems to be there.

**Comment by joergG** [comment]
At least now the behaviour is the same in firefox and chrome  :-)
this is from FF:
![drafts_perf](https://cloud.githubusercontent.com/assets/12829397/8647858/00794ea8-295c-11e5-943a-5ab776e7431a.jpg)

**Comment by joergG** [comment]
in Chrome I cannot get into compose view anymore after trying to save a draft:
![drafts_perf_chrome](https://cloud.githubusercontent.com/assets/12829397/8648027/73e7d6e2-295d-11e5-908e-4f3e67ca84fe.jpg)

**Comment by joergG** [comment]
problem is gone with fresh user-accoount! thx

**Comment by let4be** [comment]
Such stuff is common on .io because we store data structure with version(data 1.0) and then code changed to handle (data 2.0)
https://github.com/lavab/web/issues/849 is planned to mitigate such class of issues in production

**Comment by joergG** [comment]
@piggyslasher - I don't get why you moved this issue back? For me it was done...
