### ISSUE TITLE
DraftsFeature - Autosave seems to produce meanless drafts

### ISSUE THREAD

**Issue by joergG** [lavab/web#904]
A lot of drafts without content appear in the drafts folder. Those cannot be deleted. [Jörg/Tested Windows 7/Chrome Version 43.0.2357.130 m]

A lot of drafts without content appear in the drafts folder. Those can be deleted. [Felix/Tested on Mac/Safari]

![meanless_drafts](https://cloud.githubusercontent.com/assets/12829397/8527392/b32c2e30-240c-11e5-8634-0e781a2ff988.jpg)

**Comment by let4be** [comment]
Needs testing from fresh account

**Comment by joergG** [comment]
At least I don't see this behaviour anymore. But now Compose View doesn't close anymore when pressing "Save Draft". Will create a new issue.

**Comment by joergG** [comment]
ok, suddenly cannot repoduce the last mentioned bug:
"Compose View doesn't close anymore when pressing "Save Draft".
won't create new issue though!
