### ISSUE TITLE
DraftsFeature - Changes in existing drafts cannot be saved

### ISSUE THREAD

**Issue by joergG** [lavab/web#905]
After opening an already existing draft, changes are not changed anymore.
[Felix/Mac/Safari]
After discussing the thing with fvl, we wouldn't show the drop-down again in this case. If anyone makes changes on an already existant draft, these changes will be saved by closing the copose-window. no options displayed.

**Comment by let4be** [comment]
Should be fixed, pls check on https://mail.lavaboom.io/

**Comment by joergG** [comment]
@vLooz - Can you please test this because I cannot save  a draft at all  :-(

**Comment by let4be** [comment]
@joergG this is really weird
pls try to create a new account and let me know if this happens on it too

**Comment by joergG** [comment]
BUT, with the fresh user: Compose View is not closing upon "Save Draft" and not saving anything (FF and Chrome)  :-(
I will create a new issue therefore...

**Comment by let4be** [comment]
Console logs from develop tools(f12) might help here
