### ISSUE TITLE
Compose View showing error message after sending Email

### ISSUE THREAD

**Issue by joergG** [lavab/web#913]
- Tried to send a Testmail to my posteo.de-account
- Mail is delivered ACCURATELY to posteo-inbox without problem
- BUT error-message pops up within lavaboom-compose-view (doesn't close)

This is in Chrome:
![error-message-sent-email](https://cloud.githubusercontent.com/assets/12829397/8651351/751a6e74-2978-11e5-897c-18dd3de5b868.jpg)

This is in IE and FF accordingly:
![error-message-sent-email_ie](https://cloud.githubusercontent.com/assets/12829397/8651400/d958c14c-2978-11e5-968a-451f2073ddee.jpg)

**Comment by joergG** [comment]
@vLooz - please check for mac  :-)

**Comment by vLooz** [comment]
/Users/Felix/Desktop/Bildschirmfoto 2015-07-13 um 16.50.23.png

**Comment by vLooz** [comment]
I tried the same with sending to my gmail-address and this time the signature was shown double:
<img width="915" alt="bildschirmfoto 2015-07-13 um 17 18 34" src="https://cloud.githubusercontent.com/assets/11177812/8653215/649a7a98-2983-11e5-8f8c-245514b2b044.png">

**Comment by joergG** [comment]
I also had the double-signature behaviour in Chrome specifically (see above)
@piggyslasher - since email is sent properly, this is somehow related to UI interpreting signals wrong?

**Comment by piggyslasher** [comment]
Sorry, but is @let4be's turf. He needs to fix this.  Assigning to @let4be

**Comment by let4be** [comment]
This supposed to be fixed on .io, pls check

**Comment by joergG** [comment]
ok, thx so much @let4be! going to close this one.
