### ISSUE TITLE
Drafts: Please remove the additional (-->) button at the bottom

### ISSUE THREAD

**Issue by vLooz** [lavab/web#930]
I guess that you guys wanted to give the user more options here. However, I think that it will confuse him and will end up as some extra interface noise. Please remove it :-)

<img width="762" alt="bildschirmfoto 2015-07-14 um 12 12 04" src="https://cloud.githubusercontent.com/assets/11177812/8672717/502adfa4-2a31-11e5-8f64-b4ee8d2d2454.png">

**Comment by joergG** [comment]
this is a duplicat! closing it therefore.
