### ISSUE TITLE
Settings/Right panel: Keep a 44px of extra space

### ISSUE THREAD

**Issue by vLooz** [lavab/web#932]
How it is right now:
When there is a modal stripe notification popping up during some changes in Settings, it's always in danger to overlay the content below the header. 

Solution:
Keep 44px of extra space/distance between Header and the next element (next Headline), making the minimal distance 88 px instead of 44 px, to have enough space for notification modals popping up between them and the header.

<img width="832" alt="bildschirmfoto 2015-07-14 um 14 42 32" src="https://cloud.githubusercontent.com/assets/11177812/8673600/26a014c2-2a38-11e5-9699-b80715e678a4.png">

**Comment by joergG** [comment]
@piggyslasher - On staging?

**Comment by vLooz** [comment]
Looks good. Ship! :-)
